### ISSUE TITLE
Access to the ContainerHost link creation

### ISSUE THREAD

**Issue by xinchen10** [Azure/amqpnetlite#1]
Requested by user on CodePlex:  
"Is there a way to tie into the link creation of the Amqp.Listener.ContainerHost type? Here is my use case. This application will be acting as an AMQP server. There will be many client connections. Each client will get its own partition of a particular resource on the server. Since the AMQP 1.0 specification states that a link ID must be unique (section 2.6.1) I was thinking of using the link creation event to automatically partition the client resources with its link ID."

**Comment by xinchen10** [comment]
Fixed:https://github.com/Azure/amqpnetlite/commit/d3324b946eeded087581ce3cafcb16585bd9fab0

**Comment by rr118** [comment]
The example Examples/Listener/Listener.ContainerHost/Program.cs does not show the link processor getting invoked. I have not been successful at getting the link processor to work. 

It looks like the issue is in ContainerHost.AttachLink. If a MessageProcessor or RequestProcessor exists then the method returns true before ever getting to the link processor. I think the link processor should be called only if a MessageProcessor or LinkProcessor is found.

**Comment by rr118** [comment]
I have modified the code to demonstrate what I was envisioning. If you agree with the changes I will add tests and create a pull request.

https://github.com/rr118/amqpnetlite/commit/6262a760cdd827dc1ffd7ffbf54413e4fe2e7ebe

**Comment by xinchen10** [comment]
Message/RequestProcessor processes messages targeting a specific address, and LinkProcessor handles attach commands that can contain any address. Since they both can be registered with the container host, I chose to let message processor take precedence. Link processor is invoked only when no message/request processor is registered at the given address.

I think this behavior allows both basic and advanced control of message processing. If you just want to process messages at an address without worrying about link management, use MessageProcessor. If you need to perform different actions for different processors, use LinkProcessor. 

Did you register a MessageProcessor at an address and also a LinkProcessor, and hope to invoke the LinkProcessor by attaching to that address? 

I will update the API documentation to have more information about this behavior.
