### ISSUE TITLE
Existing clients can still send data when the ContainerHost is closed

### ISSUE THREAD

**Issue by rr118** [Azure/amqpnetlite#10]
If the ContainerHost is closed existing clients can still send data. Is this the expected behavior? If so I think there should be an option to close all existing connections when the host is closed. In the case that we close the listeners because we are shutting the broker down we need to make sure that we stop all incoming data so the broker resources can be cleaned up. Here is an example to reproduce the behavior. Thanks for the help.

    [TestClass]
    class TestClass
    {
        private const string Endpoint = "amqp://guest:guest@localhost:5762";
        private static readonly Uri Uri = new Uri(Endpoint);
        private static readonly Address Address = new Address(Endpoint);
        private const string MsgQueue = "queue";
        private const string LinkName = "link";

        [TestMethod]
        public void Reconnection_ServerGoesDownBeforeSendingData2()
        {
            var host = new ContainerHost(new List<Uri>() { Uri }, null, Uri.UserInfo);
            host.RegisterMessageProcessor(MsgQueue, new MessageProcessor());
            host.Open();

            var connection = new Connection(new Address(Endpoint));
            var session = new Session(connection);
            var sender = new SenderLink(session, LinkName, MsgQueue);

            host.Close();

            sender.Send(new Message("a"));

            sender.Close();
            session.Close();
            connection.Close();
        }
    }

    class MessageProcessor : IMessageProcessor
    {

        public int Credit
        {
            get { return 300; }
        }

        public void Process(MessageContext messageContext)
        {
            Console.WriteLine("Message received: {0}", messageContext.Message.Body as string);
            messageContext.Complete();
        }
    }

**Comment by rr118** [comment]
Pull request https://github.com/Azure/amqpnetlite/pull/12

**Comment by xinchen10** [comment]
Fixed https://github.com/Azure/amqpnetlite/commit/c223213fe3d5553417f602a7d7ccf72b4d56ea14
