### ISSUE TITLE
Cannot receive from an existent queue marked as durable=true

### ISSUE THREAD

**Issue by raffaeler** [Azure/amqpnetlite#101]
I configured a client and a server simple app using amqpnetlite library.
The backend is rabbitmq (latest).

The configuration is simple: 
- 1 exchange routing to a queue
- 1 queue

The client successfully post to /exchange/myexchange/key
The server can successfully receive only if the queue is configured as non-durable
If the queue is created as durable, the error is the following:

`RECV (ch=0) end(error:error(condition:amqp:precondition-failed,description:PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'durablequeue' in vhost '/': received 'false' but current is 'true'))`

How can I use durable queues?

**Comment by raffaeler** [comment]
The solution is to specify an Attach in the ReceiverLink.
The Source in the Attach must specify 1 (alias of true) for the Durable property.

There is a lack of documentation and samples.

If you are in trouble, use the Trace:
Trace.TraceLevel = TraceLevel.Frame;
Trace.TraceListener = (f, a) => Console.WriteLine(String.Format(f, a));

**Comment by robreeves** [comment]
@raffaeler Perhaps you could contribute your example to the examples section of the project if the existing examples do not cover your use case.

https://github.com/Azure/amqpnetlite/tree/master/Examples

**Comment by raffaeler** [comment]
I was looking for samples because I first need to understand the APIs (which are undocumented).
For example the Trace object comes from a StackOverflow thread. This results in a huge loss of time while some basic samples would help.

Even if I could create a successful demo on my side (spending an entire day), this does not mean it is the correct way to write it.
I would expect you to document the APIs or create a bunch of samples showing how to interop with the most popular messaging scenarios (like rabbitmq, mqtt, etc.).

**Comment by robreeves** [comment]
@raffaeler The public API is commented within the code, which you can browse using object browser in Visual Studio. 

Is this example what you were looking for?

https://github.com/xinchen10/amqpnetlite/blob/master/Examples/Interop/Interop.Client/Interop.Client.cs

I don't disagree that more documentation and examples are needed. This project is much younger than RabbitMQ. That is why I was hoping you contribute your example to help someone else avoid the same problem. I'm just a user like you.

**Comment by raffaeler** [comment]
I have seen a similar example in this repo but didn't help me much.
I don't know which is your backend, but the syntax to access exchanges, topic, and queue must be adjusted in order to interop with 0.9.
Then after spending hours in a unknown error I discovered the trace and understood that the durable setting had to be changed. Finally I understood how to change that. The point here is spending many hours when the authors could write better than anyone else some better code.
That is all, take my complain to OSS in general ...

**Comment by emomon23** [comment]
Having the same issue.  raffaeler - can you just paste you code here at least to set that durable property?

**Comment by raffaeler** [comment]
@emomon23 here is my code. It is pretty old as I abandoned this client due to the lack of documentation.
I hope it will help you!
```
            var address = new Address("amqp://localhost:5672");
            var connection = new Connection(address);
            var session = new Session(connection);

            Attach recvAttach = new Attach()
            {
                Source = new Source()
                {
                    Address = queuename,
                    Durable = 1,
                },

                Target = new Target()
                {
                    Durable = 1,
                }
            };

            ReceiverLink receiver = new ReceiverLink(session, "request-client-receiver", recvAttach, null);
```
