### ISSUE TITLE
UWP app crashes after receiving some messages

### ISSUE THREAD

**Issue by jornbeyers** [Azure/amqpnetlite#102]
Currently I'm using AmqpNetLite in a Universal Windows Application. After receiving some AMQP messages (around 5) the UWP app crashes. Am I using the correct approach to receive multiple messages?

`            string entity = Fx.Format("/devices/{0}/messages/deviceBound", DEVICE_ID);

            ReceiverLink receiveLink = new ReceiverLink(session, "receive-link", entity);
            Message received = new Message();

            try
            {
                while (true)
                {
                    received = receiveLink.Receive();
                    if (received != null)
                    {
                        receiveLink.Accept(received);
                        byte[] body = received.Body as byte[];
                        if(body != null)
                        {
                            string command = Encoding.UTF8.GetString(body);
                            Debug.WriteLine(command);

                            Logger($"command: {command}");
                        }                            
                    }                    
                }                
            }
            catch(Exception ex)
            {
                Logger($"{DateTime.Now}::Exception while listening on IoTHub: {ex.Message}");
                Debug.WriteLine(ex.ToString());
            }

            receiveLink.Close();`

**Comment by xinchen10** [comment]
@jornbeyers Do you have the callstack for the crash? Do you see the traces from the catch block in your log?

**Comment by jornbeyers** [comment]
@xinchen10 no I don't see any traces in the catch block... 
If I debug my application the program exits with code 1 (0x1), is it possible that this happens because I use ThreadPool instead of Thread?

Here are the last lines before the app stops:

`The thread 0x91c has exited with code 0 (0x0).
[07:52.739] RECV (ch=0) transfer(handle:0,delivery-id:1,delivery-tag:0E0466F82469704B9699D49C65AE0EA2,message-format:0,more:False,batchable:False) payload 363
[07:52.786] SEND (ch=0) disposition(role:True,first:1,settled:True,state:accepted())
The program '[3860] backgroundTaskHost.exe' has exited with code 1 (0x1).`

Can you confirm that I'm using the correct approach to receive multiple AMQP messages?

**Comment by xinchen10** [comment]
@jornbeyers Calling receive in a loop to get multiple messages is fine. I tried the same code in a UWP app in simulator against the Service Bus and I was able to receive 5000 messages. There is an unhandled exception and we need to find what is it to figure out the root cause.

**Comment by xinchen10** [comment]
Please reopen this issue if it still happens. Some more information (e.g. if you could run it under debugger and capture the crash callstack) would help us find the root cause.
