### ISSUE TITLE
Pushing messages to client. OnFlow and OnDisposition responsibilities?

### ISSUE THREAD

**Issue by robreeves** [Azure/amqpnetlite#103]
I am implementing a listener with a LinkProcessor. I want to attach client receiver links. The listener will  push unsolicited data to the clients. This is similar to MonitoringLinkEndpoint here.

https://github.com/Azure/amqpnetlite/blob/master/Examples/PeerToPeer/PeerToPeer.Receiver/Program.cs

I am trying to make sure that I understand the responsibilities of LinkEndpoint.OnFlow and LinkEndpoint.OnDisposition. Right now I primarily care about the case where the broker pushes unsolicited data to the client. 

_MonitoringLinkEndpoint.OnDisposition_
It seems like the example is missing the client and server coordinating when a message is settled. Shouldn't PeerToPeer.Server.Client call receiver.Accept or receiver.Reject after it receives and processes a message (line 159)? Then shouldn't PeerToPeer.Server.MonitoringLinkEndpoint.OnDisposition handle the accepted or rejected delivery message states? 

_MonitoringLinkEndpoint.OnFlow_
Is the only performative request that needs to be handled is updating the credits? I just want to make sure I am not missing anything

Right now the library provides a way to easily receive messages on the server (IMessageProcessor) and easily reply to request messages (IRequestProcessor). In my opinion, there is a hole for the use case that the server/broker wants to push messages unsolicited. It would be really nice to have the AMQP low level details abstracted away. Something like IMessagePusher that can push a message to a client subscribed to a source address and handle on the flow controls like maintaining credit behind the scenes. I think this could be a fairly common pattern. However, everyone may want to do this in a slightly different way so it could be tricky to provide an abstraction that works for most cases. Just a thought...

**Comment by xinchen10** [comment]
@robreeves you are correct on both. The client should accept the message after receiving it. This is a bug in the example.

OnFlow event is primarily for updating credits on the listener side. Since the Fields property is also made available in this event, your application could use it to pass some custom data without needing another channel but this would become an app specific logic.

I understand what you said about publishing messages. How about an abstract class ReceivingLinkEndpoint which handles disposition and link credit automatically and you only need to implement a "Task<Message> GetMessageAsync()" method?

**Comment by robreeves** [comment]
@xinchen10 Thanks for the info about the example and quick response. Could you elaborate more on what you envision for ReceivingLinkEndpoint.GetMessageAsync? My goal is for the links on the listener side to publish unsolicited messages to links on the client side. So the listener side link is the sender and the client side link is the receiver link. Does ReceivingLinkEndpoint live on the listener side? Does GetMessageAsync push data to the client?

On the client side I assume I'd use ReceiverLink.ReceiveAsync to receive messages. At a quick glance it seems like ReceiverLink already handles all of the credit logic on the client side.

**Comment by xinchen10** [comment]
The name is confusing. I was referring to an abstract class on the listener side that handles flow and disposition. Maybe it is better to call it SourceLinkEndpoint or something similar. It will call GetMessageAsync in a loop as long as there are credits and as soon as the implementation of that method returns a message, the SourceLinkEndpoint will push it to the client. This is purely a server side implementation.

**Comment by robreeves** [comment]
It makes perfect sense now. That sounds like it would work for me. My only concern is that if a client accepts/rejects the message that the SourceLinkEndpoint gets notified. This will allow me to know when it is safe to forget the data I sent or react to invalid data.

**Comment by robreeves** [comment]
@xinchen10 You mentioned in the MonitoringLinkEndpoint example it was a bug that the client link did not call accept/reject. In the case that the client does settle the message, could you elaborate on what the responsibilities of LinkEndpoint.OnDisposition are? I am having trouble piecing it together because a lot of the examples do not do anything in OnDisposition. 

I have a rough skeleton here with TODOs as the markers for what I am unsure of. I am only worried about outbound messages from the listener link to the client link.

        public override void OnDisposition(DispositionContext dispositionContext)
        {
            if (dispositionContext.Settled)
            {
                switch (dispositionContext.DeliveryState.Descriptor.Code)
                {
                    case 0x24: //accepted (See Amqp.Framing.Codec.Accepted, which represents section 3.4.2 in the AMQP 1.0 spec.)
                        //TODO - do i need to clean up any resources here (i.e. call MessageContext.Complete())?
                        break;
                    case 0x25: //rejected (See Amqp.Framing.Codec.Rejected, which represents section 3.4.3 in the AMQP 1.0 spec.)
                        //TODO - signal the message was not received to whatever object generated the message. do i need to clean up any resources?
                        break;
                    default:
                        WriteError($"Unexpected delivery state '{dispositionContext.DeliveryState.Descriptor}'. Only accepted and rejected are supported.");
                        break;
                }
            }
            else
            {
                //TODO - do I need to worry about intermediate delivery states?
            }
        }

**Comment by xinchen10** [comment]
@robreeves OnDisposition notifies the message source that (1) a delivery state has changed on the remote side, and/or (2) the delivery was settled by the remote peer. Settlement means that the protocol stops tracking the delivery state change for a given delivery. 

A message source has the option to send messages unsettled or settled (by setting the SndSettleMode and RcvSettleMode fields when a listener link is being attached). Settled mode means best effort (the message source does not care what happened to the message) and no disposition notification will happen. If the message source needs to lock some resources for the message, it should react to dispositions to manage that resource. For example, on Accepted outcome, the message source may remove the message from the queue and delete the storage. On Released outcome, the message source may unlock the message and make it available to other readers. The logic for handling different outcomes is application specific. Most of the time this part has to be done regardless of the Settled flag on disposition. As a best practice, if the message source does not want to track the state change for a given message, it should call context.Complete(). I will update the examples with more details.

**Comment by robreeves** [comment]
Thanks, @xinchen10. Just to let you know, right now we are going with using the ILinkProcessor because we have application specific logic that we want to execute when a link is attached, which cannot be done at the same time as using one of the higher level abstractions. We will use link processor, and implement a LinkEndpoint to receive messages from clients and a LinkEndpoint to push messages to clients. That is why I am really trying to understand OnFlow and OnDisposition.

This issue has kind of split into two parallel discussions 1) OnFlow/OnDisposition and 2) An abstraction to push messages. I still think an abstraction for pushing unsolicited messages in addition to IMessageProcessor and IRequestProcessor fills a void in the library. 

I just wanted to let you know so that you could prioritize work.

**Comment by xinchen10** [comment]
@robreeves I added IMessageSource as an attempt to solving the second question. This code is now in the "message-source" branch and I'd like to get some feedback before getting it into master.

In summary, the listener APIs have three major groups:
1. ContainerHost: this is the host for the listeners and all other processors.
2. Message level processors: IMessageProcessor for incoming messages, IMessageSource for outgoing messages and IRequestProcessor for request/response. At this level, link management is completely hidden from the application.
3. Link processor and endpoints: Application participates in link lifetime management and is responsible for creating a LinkEndpoint. The library provides built-in TargetLinkEndpoint and SourceLinkEndpoint, which is similar to IMessageProcessor and IMessageSource respectively, but with access to link attach/detach. Application may implement its own LinkEndpoint for advanced scenarios.

Hope this will help both simple and advanced use cases.

**Comment by robreeves** [comment]
@xinchen10 I will take a look and get back to you, probably on Monday. TargetLinkEndpoint and SourceEndpoint sound very promising.

**Comment by robreeves** [comment]
I’ve taken a look at IMessageProcessor. Overall, it’s looking really nice. My main feedback is that the handling of non-accepted (i.e. rejected) messages is a bit cumbersome and results in boilerplate code. I have to derive a class from ReceiveContext to override Complete. Instead, I think it would be easier if the user could supply an optional callback to ReceiveContext. This would be similar to how SenderLink.SendAsync works with OutcomeCallback. This would remove the need to create another class just to override Complete.

Should I be able to register a MessageProcessor and MessageSource on the same address in ContainerHost? It lets me, but I cannot create both a SenderLink with the MessageProcessor address as the target and ReceiverLink with the MessageSource as the source. I get an exception at line 342 of ContainerHost, “Only sender link can be attached at address”.  I’m not sure if it is okay in the AMQP spec, but this would be nice if it was valid in the spec. For example, let’s say that there is bidirectional messaging related to configuration. It would be nice if both the source and target could share the address “configuration” instead of needing “configuration.target” and “configuration.source”. 

Next, I'll be digging into TargetLinkEndpoint and SourceLinkEndpoint.

**Comment by robreeves** [comment]
I just got done looking at TargetLinkEndpoint and SourceLinkEndpoint. To me, it’s not clear the exact problem they solve and I am afraid it may make the listener API more confusing and harder for you to support. I think they make great, complete LinkEndpoint examples, which are definitely needed. 

LinkProcessors are for advanced, application specific scenarios. I don’t think these classes have enough hooks to satisfy the needs of these application specific scenarios in their current form. For example, SourceLinkEndpoint does not have a hook into ReceiveContext.Complete. For us, we definitely want to know if a message was successfully processed by the peer. 

I see LinkProcessors being used in two scenarios.

1. The application needs hooks into link attachment for application specific attach logic (i.e. update some instrumentation, authenticate a link and reject it if it fails, attach a Closed callback).
2. Very application specific scenarios that will be tough to predicted.

We fall under the case 1. I don’t want to speculate, but I’d imagine the majority of LinkProcessor users would fall into this category. In this case we really want the simplicity of IMessageProcessor and IMessageSource, with the additional hook into a link attach. Instead of adding TargetEndpointLink and SourceEndpointLink, which are very similar to the existing classes MessageProcessor and MessageSource respectively, I think adding a method IMessageProcessor/Source.OnAttach(ListenerLink link) would be the simpler way to solve this problem. 

For case 2, I'm not sure if any base class can solve these very application specific scenarios, but TargetLinkEndpoint and SourceLinkEndpoint are great resources to get started (even more so if more hooks are added into the classes). 

Hope that helps and I didn’t overwhelm you with my long winded responses :)

**Comment by xinchen10** [comment]
@robreeves this is super valuable feedback!
1. ReceiveContext: it was intended to (a) wrap a message, (b) carry user state needed to complete the message, (c) and custom logic to complete the delivery. It sounds better to support all of them directly on the ReceiveContext class. I will try to update the code.
2. Same address for target and source: it is a bug and I will fix it. It should be allowed to have senders and receivers on the same address.
3. Target/SourceLinkEndpoint: they were introduced as wrappers of IMessageProcessor/Source per-link to simplify ILinkProcessor implementation. If the user knows how to implement IMessageProcessor/Source and they need custom logic for link attach, they can use these classes directly without implementing their own LinkEndpoint and understanding the OnFlow/OnDisposition complexity. Message level processing is still through IMessageProcessor/Source. For example, with SourceLinkEndpoint, if an outgoing delivery fails, it will be notified through the ReceiveContext callback returned by IMessageSource. I am trying to achieve a model where LinkProcessor = custom handling of link attach/detach + IMessageProcessor/Source implementation, so I'd like to avoid putting OnAttach on IMessageProcessor/Source. It seems that the current code is not there yet :-(
4. ILinkProcessor can also be used when the address is not known in advance. For example, a broker hosts many queues that can be created and deleted dynamically. In that case message processors/sources cannot be registered.

Thanks again for taking time to review the code and give feedback.

**Comment by robreeves** [comment]
@xinchen10 Glad to help! Sorry for the slow response. 

1) I agree with the change you proposed here to add them to the receiver context class.

3) I totally understand why you don't want to complicate IMessageProcessor by adding attach and close methods. I think abstracting away OnDisposition and OnFlow is a great step towards the balance of customization and simplicity you are going for in LinkProcessor. I think you are closed to achieving the balance, but just need a hook into the settled delivery state for inbound and outbound messages for the case that the application needs to guarantee a message is delivered.

**Comment by robreeves** [comment]
@xinchen10 I've been playing around with this a bit more and have some feedback. Right now the number of threads scales linearly with the number of receiver links because SourceLinkEndpoint creates a thread to send messages to each client. This is not ideal if there are many receiver link clients because it will create a lot of threads. Is there a way to have one thread to accept ReceiverContexts for many links to keep the number of threads constant?

**Comment by xinchen10** [comment]
@robreeves how do you implement IMessageSource.GetMessageAsync? Do you block the thread until a message is available? SourceLinkEndpoint creates a new task when link credits is received in flow so by default it is using the thread pool to schedule the tasks. If threads are blocked, new threads will be created. If you implement async GetMessageAsync, new threads could also be created when a burst of flows received from multiple links.

**Comment by robreeves** [comment]
Apologies for the slow response. I was on vacation :) This was my mistake. I was using BlockingCollection inside of GetMessageAsync to wait for new messages. I think this issue can be closed now. Thanks again for the hard work implementing this feature.
