### ISSUE TITLE
Determining the remote certificate associated with a connection on the listener side

### ISSUE THREAD

**Issue by robreeves** [Azure/amqpnetlite#109]
We are using the listener with SSL, external SASL, and require a client certificate. The client certificate acts a unique security token for a given client connection. Each link gets access to its own resources on the listener side and we don’t want them to be able to access other link’s resources. The resources on the listener side are durable and if a client link is recreated it needs to map to the same resource again. For example:

connection_A + senderlink.UID + target_A maps to listener resource 1.
connection_A + senderlink.UID + target_B maps to listener resource 2.
connection_B + senderlink.UID + target_A maps to listener resource 3.

The resource resolution procedure would be something like this.

1. A client connection is created. SslSettings. RemoteCertificateValidationCallback is called and the listener validates the certificate is valid.
2. ILinkProcessor.Process is called. Determine which client certificate the Amqp.Connection is associated with (AttachContext.Link.Session.Connection). 
3. Get the link target, assuming the client is a sender link.
4. Get the link UID.
5. Use the data obtained in steps 2-4 to map the link the appropriate resource on the listener.

In order to accomplish this, we need to be able to determine the client certificate that is associated with the connection. It is buried deep within the object in the SslStream, but is not publically accessible. 

Is there a way that we can determine the remote certificate associated with an Amqp.Connection object? If not, would you be open to a contribution to accomplish this? I don’t want to pollute the vision you have for this library. As always, any comments/concerns are welcome.

**Comment by xinchen10** [comment]
@robreeves I added a Principal property to the listener connection which is set when the connection is authenticated through SASL PLAIN or SASL EXTERNAL with SSL client certificate auth. You can find more details in the ContainerHostX509PrincipalTest in ContainerHostTests.cs for how to use it. Does this meet your requirements?

**Comment by robreeves** [comment]
@xinchen10 This looks like it will work perfectly. Thank you!!

**Comment by xinchen10** [comment]
@robreeves I am preparing a release.
