### ISSUE TITLE
Listen on all network interfaces when using WebSockets and ContainerHost

### ISSUE THREAD

**Issue by robreeves** [Azure/amqpnetlite#113]
When you specify localhost or the machine name and use the amqp scheme AMQP.Net Lite listens on all network interfaces (see the TcpTransportListener constructor). When you specify localhost or the machine name and use the ws scheme, it only listens on the exact hostname. 

I think the behavior between the two schemes should be consistent. In our case I’d prefer to listen on everything when I specify localhost or the machine name like it does with the amqp scheme. In other words I’d like to be able to listen on “ws://+:8080/messaging/”. I can also see the case for tightly controlling the interfaces you listen on. I could pass two Uri objects to the ContainerHost, one for localhost and one for the machine name, but that would create two HttpListeners. Is there a way to use the strong wildcard with the ws scheme and ContainerHost?

**Comment by xinchen10** [comment]
@robreeves wildcard address should work now with WebSocket transport.

**Comment by xinchen10** [comment]
fixed in 1.1.8
