### ISSUE TITLE
Upgrade from 1.1.3 to 1.1.8 Breaks Application Using SASL

### ISSUE THREAD

**Issue by SparhawkSoftware** [Azure/amqpnetlite#115]
Error: [AmqpException] 'sender-spout has been attached.'

It occurs when a create a new link after updating the token. 
Downgrade to 1.1.5 with no other code changes fixes the problem.

Code is here:

```
public async Task UpdateTokenAsync(string tokenUri, string accessToken)
{
    var expiryTime = GenericAmqpListener.GetTokenExpiryTime(accessToken);

    if (m_currentExpiryTime != DateTime.MinValue && expiryTime <= m_currentExpiryTime)
    {
        return;
    }

    m_currentExpiryTime = expiryTime;

    await GenericAmqpListener.AssociateNamespaceEntityTokenAsync(m_connection, new Uri(tokenUri), accessToken);

    if (m_link != null)
    {
        await m_link.CloseAsync();
        m_link = null;
    }

    m_link = new SenderLink(m_session, "sender-spout", m_terminusName);
    m_link.Closed = new ClosedCallback(OnLinkClosed);
}
```

**Comment by xinchen10** [comment]
This is a race condition between closing a link and recreating a new one with the same link in the same session. It should be in the older versions as well. If you run your tests multiple times you may be able to hit it. To workaround the issue now, you can either create a new session or use a different link name.
