### ISSUE TITLE
Receiver stops receiving after several hours...

### ISSUE THREAD

**Issue by maiorfi** [Azure/amqpnetlite#116]
Hi (and thanks for you amazing work).

I just developed a simple test running on a NETMF board. In such sample, I create a Receiver and a Sender used for entire lifetime of application (hopefully running...forever!).

I spawn the Sender with a custom Thread, and it looks like it is going to send forever, without any apparent issue.

On the contrary, my Receiver stopped working after several hours (i.e. it stopped receiving cloud-to-device IoT-Hub messages I periodically send through DeviceExplorer tool).

The code that activates my only Receiver instance is:

```csharp
private static void startReceiver()
        {
            var receiverAddress = "devices/" + DEVICE_NAME + "/messages/deviceBound";

            _receiver = _client.CreateReceiver(receiverAddress);

            _receiver.Start(10, (r, m) =>
            {
                r.Accept(m);

                var bodyAsString = new string(Encoding.UTF8.GetChars(m.Body as byte[]));

                Debug.Print("Message received : " + m.MessageId + ", '" + bodyAsString + "'");

                if (bodyAsString == "0")
                {
                    _led1.Write(false);
                }
                else if (bodyAsString == "1")
                {
                    _led1.Write(true);
                }
                else
                {
                    _led1.Write(true);
                    Thread.Sleep(50);
                    _led1.Write(false);
                }
            });
        }
```

Is that anything I can check in order to spot whether Receiver is actually working properly (i.e. receiving)?

Thanks!

**Comment by xinchen10** [comment]
@maiorfi I guess the connection was lost. The Client does not reconnect when this happens. You can subscribe to Client.OnError event and recreate the objects.

**Comment by maiorfi** [comment]
Ok, thanks. Referring to parameters of OnError event delegate (i.e. Client client, Link link, Symbol error), is there any suggested pattern to use in order to spot this specific situation?

**Comment by xinchen10** [comment]
@maiorfi Typically application caches the Client, and Sender/Receiver objects after they are created. In the event handler, if link is not null, the error comes from link detach and you can recreate the link object. If the Client is also closing, you will get an exception when attempting to create the link. In that case you can handle the exception and reconnect the Client. If this does not happen very often, you may also want to just close and reconnect the Client instead.
