### ISSUE TITLE
LinkEndpoint.OnFlow sometimes has a negative FlowContext.Messages value

### ISSUE THREAD

**Issue by robreeves** [Azure/amqpnetlite#119]
On the listener side my LinkListener is in the sender role pushing data to the client ReceiverLink. I use a LinkProcessor to attach the ListenerLink to a SourceEndpoint. The source sends a group of messages and waits for them to be settled. 

I’ve found that somethings the LinkEndpoint.OnFlow FlowContext.Messages value can be negative. In the example below I can reproduce this pretty consistently by sending bursts of messages that are greater than the credit given by the client. In the example the client starts with a credit of 5 and I send messages in bursts of 15. I do not ever send more messages than the given credit. I queue the messages and send them as I receive more credit.

I have not fully figured this out yet, but I suspect it is related to the fact that I do not have access to ListenerLink.credit. I have to maintain my own credit in my LinkEndpoint implementation. This means the ListenerLink.OnFlow calculation will also have a value of 0 for this.credit. 

Here is my example.

### Listener
    class Program
    {
        static void Main(string[] args)
        {
            var host = new ContainerHost(new List<string>() { "ws://localhost:8080/messaging/" });
            host.RegisterLinkProcessor(new LinkProcessor());
            host.Open();

            Console.WriteLine("running");
            Console.ReadKey();
        }
    }

    class LinkProcessor : ILinkProcessor
    {
        public void Process(AttachContext attachContext)
        {
            var endpoint = new SourceEndpoint(attachContext.Link);
            attachContext.Complete(endpoint, 0); //client sets credit for source

            //Simulate message producer
            //Sends a group of messages asynchronously and then waits for all messages to be settled
            Task.Run(() =>
            {
                //Just a repro hack
                //Delay just to give the link time to attach since this is started before the link is fully attached
                Thread.Sleep(5000);

                while (true)
                {
                    const int SendCount = 15;
                    for (int i = 0; i < SendCount; i++)
                    {
                        endpoint.SendMessage(DateTime.Now.Ticks);
                    }

                    Console.WriteLine($"Sent {SendCount} messages successfully");

                    Thread.Sleep(200);
                }
            });
        }
    }

    class SourceEndpoint : LinkEndpoint
    {
        /// <summary>
        /// Need to keep track of credit here because cannot access it in ListenerLink.
        /// Will this mess up LinkEndpoint.OnFlow calculation because this.credit is always 0?
        /// </summary>
        private int credit;

        private readonly ListenerLink link;
        private BlockingCollection<Message> waitingToSend = new BlockingCollection<Message>(new ConcurrentQueue<Message>());
        private readonly AutoResetEvent drainControl = new AutoResetEvent(false);

        //For debugging
        private int lifetimeCredit;
        private int lifetimeSentMessages;

        public SourceEndpoint(ListenerLink link)
        {
            this.link = link;

            //Start dedicated thread for sending messages when credit is available
            Task.Run(() => SendWaitingMessages());
        }

        /// <summary>
        /// The public method to send a message
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public void SendMessage(long value)
        {
            waitingToSend.Add(new Message(value));
        }

        private void SendWaitingMessages()
        {
            while (true)
            {
                //Process queued messages until there is no credit
                while (Interlocked.Decrement(ref credit) > -1)
                {
                    //debugging
                    Interlocked.Increment(ref lifetimeSentMessages);

                    //Send message
                    var msg = waitingToSend.Take();
                    link.SendMessage(msg);
                }

                //Give back decremented credit that was not used
                Interlocked.Increment(ref credit);

                //Debugging
                Console.WriteLine($"Lifetime sent: {lifetimeSentMessages}, Lifetime credit: {lifetimeCredit}");

                //Wait for more credit
                //This is signaled in the OnFlow method
                drainControl.WaitOne();
            }
        }

        public override void OnDisposition(DispositionContext dispositionContext)
        {
             dispositionContext.Complete();
        }

        public override void OnFlow(FlowContext flowContext)
        {
            //Update credit
            var updatedCredit = Interlocked.Add(ref credit, flowContext.Messages);
            Interlocked.Add(ref lifetimeCredit, flowContext.Messages);

            //If all credit was consumed signal that more credit is available
            if (updatedCredit == flowContext.Messages)
            {
                drainControl.Set();
            }

            //For debugging. Print when the flowContext is less than 0. I think this is a bug.
            Console.WriteLine($"flowContext: {flowContext.Messages}, credit: {updatedCredit}");
            if (flowContext.Messages < 0)
            {
                Console.WriteLine("++++++++++++++Negative flowContext++++++++++++++");
            }
        }
    }

### Client

    class Program
    {
        static void Main(string[] args)
        {
            var conn = new ConnectionFactory().CreateAsync(new Address("ws://localhost:8080/messaging/")).Result;
            var sess = new Session(conn);
            var receiver = new ReceiverLink(sess, "link name", "source");

            receiver.Start(5, (l, m) =>
            {
                Console.WriteLine(m.GetBody<long>());
                l.Accept(m);
            });

            Console.WriteLine("running");
            Console.ReadKey();
        }
    }

I also switched to the message-source branch (reference https://github.com/Azure/amqpnetlite/issues/103) and tried to reproduce this by implementing an IMessageSource that generates messages as quickly as possible, but the issue does not occur there. There were some significant changes around managing credit in ListenerLink when pushing messages though. For reference here is my example IMessageSource.

### IMessageSource

    class MessageSource : IMessageSource
    {
        public Task<ReceiveContext> GetMessageAsync(ListenerLink link)
        {
            return Task.Run<ReceiveContext>(() =>
            {
                //var value = WaitingToSend.Take();
                var msg = new Message(DateTime.Now.Ticks);

                return new ReceiveContext(link, msg);
            });
        }
    }

**Comment by xinchen10** [comment]
There are a couple of issues with flow control in ListenerLink for sending out messages. The message-source related changes happen to address most of them. I am bringing the message-source code into master and these issues will be fixed as a result of that.

**Comment by robreeves** [comment]
@xinchen10 It looks like you merged the message-source changes. I just tested against the master branch with the above example and still see the possibility for negative credit. My hunch is that it has something to do with managing the credit outside of ListenerLink. I manage it in SourceEndpoint.credit because the ListenerLink.Credit is internal. It looks like switching to SourceLinkEndpoint and implementing IMessageSource would be the better option since you've done a lot of the credit management for us. I still wanted to let you know the issue still exists in the example just in case it is a real issue.

Shouldn't TargetLinkEndpoint and SourceLinkEndpoint be public classes? They are in the message-source branch.

**Comment by xinchen10** [comment]
@robreeves the negative message count should be fixed now. With ILinkProcessor I expect most scenarios would just use Target/SourceLinkEndpoint, especially SouceLinkEndpoint for link credit management. I just made them public after updating the documentation.

**Comment by robreeves** [comment]
@xinchen10 The repro example is fixed. Credit does not go negative now. Thanks!
