### ISSUE TITLE
Azure ServiceBus returns "Batching brokered messages with distinct SessionId or PartitionKey is not supported for an entity with partitioning enabled" with default example

### ISSUE THREAD

**Issue by darkurse** [Azure/amqpnetlite#120]
Hi,

there is no support forum and I don't know elsewhere to post my question, so I hope you don't mind if I do so here.

In order to test the example ServiceBus.MessageSession, I have created the following topic/subscription on my **Azure account** : 
 - A Topic with partitioning enabled
 - A Subscriber "low" to this topic with both sessions and batched operations enabled
Also, I have changed the sample project to make it work with only one session group.

I can connect to the Service Bus with the credentials but the `sender.Send(message);` fails with the following thrown exception:

> Batching brokered messages with distinct SessionId or PartitionKey is not supported for an entity with partitioning enabled. Reference:[some-guid], TrackingId:2a3a44f400000123000cb8565730644a_G26_B20, SystemTracker:[my-namespace-name-on-azure]:topic:[my-topic-name-on-azure]~111, Timestamp:5/9/2016 10:19:55 AM

I do have partitioning enabled for my topic and I do need a Session Id since I need to maintain a message delivery order. However, I am using only one SessionId AND the sample code seems to be using a simple Send() .. Not a SendBatch().

If I remove the property `GroupId` it doesn't throw but I am not sure we are then using a sessionId !

I am obviously missing a key concept here, but what ? Do I need to "disable" send _batch_ ?

Regards

**Comment by xinchen10** [comment]
@darkurse this is an issue on the service side. The code should work for regular topic. For partitioned entities the group-id property does not seem to be handled correctly by the service. We will look into it. Thanks for reporting the issue.

**Comment by hcaituiro** [comment]
@darkurse you need to add 'x-opt-partition-key' in the message annotations section with the value of group-id.

**Comment by darkurse** [comment]
@hcaituiro , thank you !!
@xinchen10, out of curiosity I saw you that you were also involved in another [Microsoft.Azure.Amqp](https://github.com/Azure/azure-amqp) project on github. What's the difference between these two projects ?

**Comment by darkurse** [comment]
Using @hcaituiro trick I can send data to the session ( and I see it on my azure dashboard ) but I do not receive anything ever. `receiver.Receive(30000);` always returns null.

@xinchen10, If I can suggest a couple of things :

1. What about setting `receiver.Error` to something when you `receiver.Receive` returns null as it would be interesting to make the difference between a timeout and an error.
2. Documentation is there but empty. The descriptions on your methods/properties names are repeating what their name already tell us. You would gain explaining with the usual extra tags : 
    - **\<remarks\>** to guide us on how to use this method/property
    - \<exceptions\>
    - \<returns\> this on success or that on failure

Anyway, that's my 2 cents.

Also, Am I right assuming the amqpnetlite integration with azure service bus queue/topic is in still beta ?

Thanks for your effort and sharing your work.

**Comment by xinchen10** [comment]
@darkurse when receiver link is detached with an error, the error is set on receiver.Error. Subsequent receive calls will get AmqpException with "illegal-state" error. 

When you ran the sample, what was the value of Example.Entity? This example assumes a Queue and the value is the queue name. For topic, it is different. To send to a topic, use the topic's name as Entity value. To receive from a subscription, you have two options:
(1) Set Entity value to "[your-topic]/Subscriptions/[your-subscription]". The "name" parameter in ReceiverLink can be any value. Or,
(2) Set Entity value to "[your-topic]" and the "name" parameter of ReceiverLink to "[your-subscription]"

We will improve the documentation to have more information and the examples to work out of box.

Thank you.

**Comment by darkurse** [comment]
@xinchen10, thank you so much for your new example and the _**code works** when no session is needed_.

I had set Entity to [your-topic] but the subscription part was not set properly. I kind of tried option (2) in my multiple attempts but it didn't work for another reason I think : sessions.

I have the need to use sessions on my Topic/Subscribers because I require FIFO delivery. Same as  for Queues, I can send data with 'x-opt-partition-key' option set to my sessionId. However, I still cannot receive data from the subscriber :

Here's the code to demonstrate :
```
class TopicExample : Example
{
        readonly string entitySubscriber = "sub2";
        readonly string sessionId = "MySessionId";

        [...]
       
       async Task SendReceiveAsync(int count)
       {
            [...]

            for (int i = 0; i < count; i++)
            {
                Message message = new Message();
                message.Properties = new Properties() { 
                    GroupId = sessionId,  // Set session id
                    MessageId = "topic-test-" + i };
                message.BodySection =new AmqpValue() { Value = "message #" + i };

                // Set session id in partition key or I get error from azure
                message.MessageAnnotations = new MessageAnnotations();
                message.MessageAnnotations[new Symbol("x-opt-partition-key")] = sessionId;

                await sender.SendAsync(message);
            }

            await sender.CloseAsync();

            Trace.WriteLine(TraceLevel.Information, "Receiving messages from subscription...");

            Map filters = new Map();
            filters.Add(new Symbol("com.microsoft:session-filter"), sessionId);

            ReceiverLink receiver = new ReceiverLink(session, entitySubscriber,
                new Source() { Address = this.Entity, FilterSet = filters }, null);
            for (int i = 0; i < count; i++)
            {
                Message message = await receiver.ReceiveAsync(30000);

                if (message == null)
                {
                     // Gets always here when playing with sessionId.
                    Trace.WriteLine(TraceLevel.Information, "Nothing received...");
                    break;
                }
                else
                {
                    Trace.WriteLine(TraceLevel.Information, "Receiving message " + message.Properties.MessageId + " with body '" + message.GetBody<string>() + '"');
                }

                receiver.Accept(message);
            }

            [...]
     }
}
```

Thank you

**Comment by xinchen10** [comment]
@darkurse the code works with a partitioned topic I created in the Azure Service Bus service. You could get a null message if the receiver link fails to open. If you enable frame traces, do you see a detach frame with an error in it?

I also updated the code a bit so that the error is set on receiver link and can be retrieved when a null message is returned.

In my testing, if I terminate the process randomly, I could get the following error.
```
condition:com.microsoft:session-cannot-be-locked,description:The requested session 'a' cannot be accepted. It may be locked by another receiver.
```
This happens because even when the client is terminated, it takes a while for the service to release locked resources. For partitioned entity, it is better to set the receive timeout greater than the lock duration of the entity.

**Comment by darkurse** [comment]
@xinchen10, Thank for setting the error directly into the receiver. It makes a better flow for error check.

So the good news is it works perfectly today. The bad news is, I don't know why it failed yesterday. I haven't changed the code at all. I just pulled your latest change with `AmqpObject.Error early` update.

You are right about the `session-cannot-be-locked` error which I occasionally get by terminating the process randomly (or starting many instances of the app simultaneously). My only concern is that yesterday's error was happening consistently all the time, and now I can barely induce it in error.. I don't understand what changed to make such a difference.

As far as I am concerned we can close this issue. The code does what I expect it to do


Thanks for the tip regarding `receive timeout > lock duration` and also for your availability
