### ISSUE TITLE
Using AMQP.Net Lite with Azure IoT Hub

### ISSUE THREAD

**Issue by ppatierno** [Azure/amqpnetlite#122]
Hello,
it could be useful to add in some way the content of my following articles into AMQP .Net Lite documentation : 

https://paolopatierno.wordpress.com/2015/10/31/azure-iot-hub-commands-and-feedback-using-amqp-net-lite/

https://paolopatierno.wordpress.com/2015/10/24/connecting-to-the-azure-iot-hub-using-an-the-amqp-stack/

They show how it's possible to connect to Azure IoT Hub using the AMQP .Net Lite library.
How can I help on that if you're interested ?

Thanks,
Paolo.

**Comment by xinchen10** [comment]
@ppatierno documentation is now part of the source. You can add them as articles (see examples under the "articles" directory). The source can then be processed by DocFX to produce a static web site which can be accessed at http://azure.github.io/amqpnetlite 

If you can help author the article md files, that would be great.

**Comment by ppatierno** [comment]
Do I have to fork the project and make PR for that ?

**Comment by xinchen10** [comment]
Yes, that's right.

**Comment by ppatierno** [comment]
I have just created a pull request but it seems that CLA is required. I already signed the CLA when the project was on CodePlex. Now ?

**Comment by xinchen10** [comment]
I think our github CLA is using a different tracking system. Could you follow the link and sign it again? Thank you.

**Comment by ppatierno** [comment]
@xinchen10 sorry but I can't see any link for signing the CLA. Neither here nor on the pull request :-(

**Comment by ppatierno** [comment]
CLA just signed !

**Comment by xinchen10** [comment]
@ppatierno the articles are online now.
http://azure.github.io/amqpnetlite/articles/device_to_iothub.html
