### ISSUE TITLE
Allow deserializing object using GetBody(Type).

### ISSUE THREAD

**Issue by bulanh** [Azure/amqpnetlite#124]
When deserializing incoming messages on client side, it would be very useful to have method in `Message` class with following declaration:
```csharp
object Message.GetMessage(Type type);
```

It can be handy when you expect several kind of messages and you want to handle them as strongly typed objects.

Consider following code (only happy path shown):
```csharp
Dictionary<string, Type> typesByDescriptor;
void OnMessage(Message msg) {
    var typeString = ((DescribedValue)msg.Body).Descriptor.ToString();
    var type = typesByDescriptor[typeString];
    var data = msg.GetBody(type);
    
    if (type == typeof(FirstEvent)) {
        HandleFirstEvent(data as FirstEvent);
    } else if (type == typeof(SecondEvent)) {
        HandleSecondEvent(data as SecondEvent);
    }
}  
```

Right now you can work around this with`MethodInfo.MakeGenericMethod`, but it is hacky and would be slower than proposed method.

**Comment by xinchen10** [comment]
You can have a base class for all your event classes and annotate the base class with the known derived types with AmqpProvides attribute as follows. To decode an event object, call message.GetBody<Event>(). The library will automatically resolve to the correct type based on the descriptor in the message body. Refer to the PeerToPeer.CustomType example for more details.
```
    [AmqpContract(Name = "event-base")]
    [AmqpProvides(typeof(FirstEvent))]
    [AmqpProvides(typeof(SecondEvent))]
    public class Event
    {
    }

    [AmqpContract(Name = "first-event")]
    public class FirstEvent
    {
        // define members here
    }

    [AmqpContract(Name = "second-event")]
    public class SecondEvent
    {
        // define members here
    }

```

**Comment by xinchen10** [comment]
Not sure if I understood the issue correctly. Feel free to reopen it if this does not work for your scenario.

**Comment by bulanh** [comment]
Your solution works great for problem I had. Thank you.
