### ISSUE TITLE
Trying to Receive from Azure ServiceBus topic, throws error "The messaging entity could not be found"

### ISSUE THREAD

**Issue by rposener** [Azure/amqpnetlite#133]
This is all on 1.1.19-rc (on .net core).  I am trying to use Azure Service Bus Topic to accomplish pub/sub like behavior.  I can successfully send a topic message using the code in the demo, but I seem to be missing something on the receiver side.

Here is what I am doing, and it seems to flow straight through after the ReceiveAsync - returning a null message, and not delaying until the timeout occurs.  Perhaps I do not understand how this RecieverLink should be working?

`Session session = await GetSession();
            ReceiverLink receiver = new ReceiverLink(session, _options.ConnectionName.ToLower(), Topic);
            while (_receiving)
            {
                Message message = await receiver.ReceiveAsync();
                if (message != null && _receiving)
                {
                    Action(message.GetBody<T>());
                }
            }
            await receiver.CloseAsync();`

**Comment by xinchen10** [comment]
When creating the ReceiverLink, set `address` to `<topic-name>/Subscriptions/<subscription-name>` This is how a subscription is addressed in Service Bus. You can find more details in this example:
https://github.com/Azure/amqpnetlite/blob/master/Examples/ServiceBus/Scenarios/TopicExample.cs

**Comment by rposener** [comment]
Thanks - that got me past that.  I wonder if we can get the ReceiveAsync to take a cancellation token or something?  As I was writing tests, I keep timing out when I'm waiting for the request to complete, then because of the default timeout, it seems to wait 1,000 hours before the task would expire.

**Comment by xinchen10** [comment]
@rposener can you explain a bit more what issue you want to solve with the cancellation token? Do you want to cancel the receive call before the timeout expires? Or do you want the receive call to wait until you explicitly cancel it?

**Comment by rposener** [comment]
I want to be able to cancel the call before it times out.  In the event my app changes state/context such that the receive is no longer needed, I don't want to leave it out there.

**Comment by rposener** [comment]
Ok, I have taken a slightly different route here.  I'm using Start to begin a message pump on an Azure Service Bus Topic.  That works great, but how do I stop the message pump?  Do I SetCredit to 0 or something?  I cannot figure out how / what Setting Credits do either.  Is there any good documentation to understand this?

**Comment by xinchen10** [comment]
Calling SetCredit with 0 will stop the pump. After the call, you may get some messages that are in-transit before the broker processes the flow command.
The other option is to close the receiver link. You will need to recreate it when you need to resume message processing. This option should be considered if your application state change is not frequent and you don't want to keep the receiver around in the stop state.
This library assumes basic knowledge of AMQP 1.0 and the APIs are designed around the core concepts defined in the protocol spec. One good introduction material for AMQP 1.0 is [Clemens's Channel9 videos](https://channel9.msdn.com/Blogs/Subscribe) - watch [the flow control part](https://channel9.msdn.com/Blogs/Subscribe/The-AMQP-10-Protocol-46-Flow-Control) which convers the basics of AMQP flow control. You can find more information about AMQP 1.0 [here](https://github.com/xinchen10/awesome-amqp).

**Comment by xinchen10** [comment]
There is no plan to support cancellation token for receive calls, as cancelling a network call is tricky and could lead to unexpected results. To stop the message flow, you can either use AMQP flow control (link credit) to pause message delivery, or close the receiver link and reopen it when needed. Thanks.
