### ISSUE TITLE
False positive in LinkTests.TestMethod_LinkCreateClose

### ISSUE THREAD

**Issue by ChugR** [Azure/amqpnetlite#136]
The code as written has a race condition. Run the test to a broker on some distant, slow, remote host and the test fails occasionally. The connection.Error holds

    base = {error(condition:amqp:not-found,description:The session channel '65535' cannot be found.)}

Over the wire the client blasts the entire `open, begin, attach, detach, end, close` before the broker returns the `open`. This causes the internal not-found error that fails the test. The remote host never sends any error frames.

    ◊  ◊◊ 5.494422  Frame 904  10.18.96.1:53310  -> 10.10.62.100:5672  ->   init SASL (3): (1.0.0)
    ◊  ◊◊ 5.494499  Frame 907  10.18.96.1:53310  -> 10.10.62.100:5672  ->   method sasl.init
    ◊  ◊◊ 5.497061  Frame 910  10.18.96.1:53310 <-  10.10.62.100:5672 <-    init SASL (3): (1.0.0), method sasl.mechanisms, method sasl.outcome
    ◊  ◊◊ 5.497119  Frame 911  10.18.96.1:53310 <-  10.10.62.100:5672 <-    init AMQP (0): (1.0.0)
    ◊  ◊◊ 5.583835  Frame 922  10.18.96.1:53310  -> 10.10.62.100:5672  ->   init AMQP (0): (1.0.0)
    ◊  ◊◊ 5.583909  Frame 923  10.18.96.1:53310  -> 10.10.62.100:5672  ->   open [0]
    ◊  ◊◊ 5.583925  Frame 924  10.18.96.1:53310  -> 10.10.62.100:5672  ->   begin [0,null]
    ◊  ◊◊ 5.583952  Frame 926  10.18.96.1:53310  -> 10.10.62.100:5672  ->   attach [0,0] sender sender (source: null, target: q1)
    ◊  ◊◊ 5.584041  Frame 928  10.18.96.1:53310  -> 10.10.62.100:5672  ->   attach [0,1] receiver receiver (source: q1, target: null)
    ◊  ◊◊ 5.584070  Frame 929  10.18.96.1:53310  -> 10.10.62.100:5672  ->   detach [0,0] 
    ◊  ◊◊ 5.584082  Frame 930  10.18.96.1:53310  -> 10.10.62.100:5672  ->   detach [0,1]
    ◊  ◊◊ 5.584107  Frame 931  10.18.96.1:53310  -> 10.10.62.100:5672  ->   end [0], close [0]
    ◊  ◊◊ 5.584562  Frame 934  10.18.96.1:53310 <-  10.10.62.100:5672 <-    open [0]
    ◊  ◊◊ 5.585683  Frame 936  10.18.96.1:53310 <-  10.10.62.100:5672 <-    begin [0,65535], end [0], close [0]

**Comment by xinchen10** [comment]
@ChugR how do I read the last frame trace, specifically the fields represented by [0,65535]? Is 0 for frame.CHANNEL and 65535 for begin.remote-channel, respectively? The begin frame sent by the client has frame.CHANNEl = 0, so begin.remote-channel in the returned begin frame should be 0.  Thanks.

**Comment by ChugR** [comment]
Indeed! The peer is returning a bad channel number. Thanks for your help.

**Comment by ChugR** [comment]
[issue-136-trace.zip](https://github.com/Azure/amqpnetlite/files/316194/issue-136-trace.zip)

I forgot to answer your questions. The numbers in [square brackets] for begin are the channel and remoteChannel. I've attached the interactive web page. The frame decode legend is down at the bottom.
