### ISSUE TITLE
Future of WebSockets support on .NET Core?

### ISSUE THREAD

**Issue by robreeves** [Azure/amqpnetlite#138]
I'm assuming the reason AMQP.Net Lite does not support WebSockets on .NET Core is because .NET Core does not support the System.Net.WebSockets namespace. Is this correct? Do know if .NET Core plans to add this support?

Right now we use AMQP for some things and HTTP for other things, depending on the use case. I'm asking because we would like to use AMQP over WebSockets to consolidate our port requirements.

**Comment by xinchen10** [comment]
corefx doesn't support HTTP listener. The WebSocket client is supported now, and I will enable it for the client soon.

**Comment by robreeves** [comment]
The WebSocket client is all we need to run on .NET Core.

**Comment by xinchen10** [comment]
I have added the client WebSocket transport for .Net Core (under dotnet/Amqp.WebSockets.Client folder). I need to figure out what's the best way to package the .Net Core assemblies. If I include all DLLs in the amqpnetlite package, the netstandard1.3 target would need to depend on all corefx packages, even for people who do not use Listener or WebSockets. Or I can follow the corefx way to publish each DLL as its own package. If anyone has suggestions, please let me know. Thanks.

**Comment by xinchen10** [comment]
https://www.nuget.org/packages/AMQPNetLite.WebSockets/

This is the WebSockets client on .Net Core. To enable "ws" and "wss" schemes, create a factory as follows.
```
        ConnectionFactory connectionFactory = new ConnectionFactory(
            new TransportProvider[] { new WebSocketTransportFactory() });
```

**Comment by npnelson** [comment]
Just an FYI in case anyone struggles with this, if you are trying to connect to Azure ServiceBus with websockets, your address needs to take the format:

```var address=new Address("<your service bus namespace>",443,"<your SharedAccessKeyName>","<Your SharedAccessKey>","/$servicebus/websocket","WSS")```

**Comment by jwaltireland** [comment]
So i have created an app that uses the Azure service bus sdk using .net 461 with amqp websockets transport type.  when i upgrade the project to .net standard, and consume it in a .net core 2.1 project, i can no longer connect to azure service bus.  i get this error:

Unable to connect to the remote server 
A security error occurred

I'm on win 10, with web sockets enabled.  this works in my 461 version.  

any thoughts?
