### ISSUE TITLE
SSLSettings not being honored for WebSockets

### ISSUE THREAD

**Issue by stanasse** [Azure/amqpnetlite#140]
I have created a websocket client and server and can successfully connect and send data, however the SSL security settings are not being honored. Is there another way I should be setting SSL behavior for WebSockets or am I doing any thing incorrectly? 

For example, the RemoteCertificateValidationCallback is not being called when it is set on the SSLSettings for both the ConnectionListener and ConnectionFactory.

Also the connection is successful when the client certificate is not trusted.

An example that reproduces the issue is attached. Please let me know if any more detail is necessary. I am using Amqp.Net version 1.1.8 on Windows 10. 

I used two different self-signed certificates, one for the client and one for the server. I put the client certificate in the Personal store and the server certificate in the Personal and Trusted Root Certification Authorities store.

I used the netsh utility to add a urlacl and bind the server certificate to the port 5555, for example:

C:\WINDOWS\system32>netsh http add urlacl url = https://+:5555/ user=DOMAIN\USER listen=yes

C:\WINDOWS\system32>netsh http add sslcert ipport=0.0.0.0:5555 certhash=defbdbf76cc7f80cf4c88ae40e7d52bf4d5156b3 appid={eece89a9-9fbf-421b-a122-f1fc65c3c56d}

[Program.cs.txt](https://github.com/Azure/amqpnetlite/files/337687/Program.cs.txt)

**Comment by xinchen10** [comment]
That's the current behavior. `SslSettings` is applied to amqps transport (SSL/TSL over TCP) which is really about customizing the internal `SslStream` object. It is not used for WebSockets transport.

I think WebSocket needs its own settings since there are [options](https://msdn.microsoft.com/en-us/library/system.net.websockets.clientwebsocketoptions(v=vs.110).aspx), such as Cookies, Proxy, etc. that do not belong to `SslSettings` but are valid and important for some scenarios.

**Comment by stanasse** [comment]
Thanks for the making the client WebSocket options available in version 1.2. 

The limitation still exists on how to perform custom validation of certificates on the client and server side. Unfortunately, on the client side, it looks like the underlying Microsoft WebSocket class doesn't support custom validation of the server certificate. One option appears to be using the ServicePointManager.ServerCertificateValidationCallback, however it is not appropriate for our situation because ServicePointManager.ServerCertificateValidationCallback is a global setting. 

On the server side, one idea is that if we had access to the HttpListenerContext, for example from a callback from ConnectionListener, then we could validate the client certificate associated with the request.

I'm still in the process of investigating possible options. It appears the main issue is that when an https connection is promoted to a web socket connection, the SSL handshake using the certificates has already occurred and the underlying Microsoft WebSocket and HttpListener classes don't expose the same hooks to perform certificate validation like SSLStream.

Just curious, are there plans to expose certificate validation callbacks with secure WebSockets in amqpnet lite?

**Comment by xinchen10** [comment]
I know the limitations. I am keeping this issue open as I am also exploring options. It would be nice to make the scenario work but as you pointed out, the HTTP path does not expose all the settings like SslStream.

**Comment by xinchen10** [comment]
Some of the settings are now applied on the listener. There is on easy way to apply the settings on client unless we switch to another websocket lib. There is no plan for it at this moment.
