### ISSUE TITLE
serializable members are sometimes too strict on codec rules

### ISSUE THREAD

**Issue by mbroadst** [Azure/amqpnetlite#143]
In `amqp10` we need to heuristically determine what type of number to send across the wire since javascript doesn't provide us fine-grained detail about the Number's actual type. This makes it difficult to interop with AMQP.Net lite, since I could for instance send the value `1` which is sent across as a `uint` (`0x5201`), and the AMQP.Net lite code sample I have on the other side will throw an exception because it was expecting an `int` instead of a `uint`.

Is it possible to loosen the strict requirements here?

**Comment by xinchen10** [comment]
The library has to enforce the type system defined by the spec. If the format code (the leading byte) is not expected it has to fail the decoding. For you scenario you would need to have your own serialization logic to make it work. Here is one example you could do.
```
class Integer : IAmqpSerializable
{
    public int Value { get; private set; }

    public int EncodeSize { get { throw new NotImplementedException(); } }

    public void Encode(ByteBuffer buffer)
    {
        throw new NotImplementedException();
    }

    public void Decode(ByteBuffer buffer)
    {
        byte code = AmqpBitConverter.ReadUByte(buffer);
        if (code == 0x43)
        {
            this.Value = 0;
        }
        else if (code == 0x52 || code == 0x54)
        {
            this.Value = AmqpBitConverter.ReadByte(buffer);
        }
        else if (code == 0x70 || code == 0x71)
        {
            this.Value = AmqpBitConverter.ReadInt(buffer);
        }
        else
        {
            throw new AmqpException(ErrorCode.DecodeError, "Not expected");
        }
    }
}
```

In you class definition you can expose an `int` property backed by an `Integer` field with some necessary conversion, so the rest of your code does not have to deal with the `Integer` type. This is more code but that's required if your need to loosen the type system requirements.

**Comment by mbroadst** [comment]
@xinchen10 okay that works for me, thanks!

**Comment by ChugR** [comment]
I did some research recently on the types_in vs. types_out between .NET and AMQP. See my fork https://github.com/ChugR/amqpnetlite/blob/harvest_type_facts/Examples/type-table-gen/type-table-gen.cs
Run this program and it generates a asciidoc mapping tables. It might help you suss out other types if you need to map them following the @xinchen10  example.

**Comment by mbroadst** [comment]
@ChugR much appreciated. I think it might end up making sense to provide some sort of interop layer if you're dealing with e.g. clients from Javascript, where we only have a few primitive types and most work is done on a best-effort basis. I could imagine this might be useful for our existing amqp10 users who are working with ServiceBus/EventHub and talking to something with AMQP.Net Lite on the other side.
