### ISSUE TITLE
Support string key values in DescribedMap

### ISSUE THREAD

**Issue by bulanh** [Azure/amqpnetlite#148]
As of now AmqpNetLite requires that keys inside described map are Symbols. In first lines inside `DescribedMapType::WriteMemberValue` there is: `string key = Encoder.ReadSymbol(buffer, Encoder.ReadFormatCode(buffer));`

However, some other libraries (namely: qpid) uses pure strings (format code = 0xA1) to encode keys of the map. Maybe it is worth considering to support such maps? Going further: maybe AmqpNetLite could convert any type of key to string?

**Comment by xinchen10** [comment]
@bulanh Have you tried EncodingType.SimpleMap? It was designed to interoperate with other clients using the plain AMQP map type. The keys are strings.

It would have been ideal if EncodingType.Map also uses string keys, but that would break backward compatibility with existing clients.

**Comment by bulanh** [comment]
Yes, `EncodingType.SimpleMap` handles string keys, but it doesn't allow to use AmqpProvidesAttribute (which I need).

Can't `EncodingType.Map` handle both string and symbol keys? Something like:

```csharp
protected override int ReadMemberValue(ByteBuffer buffer, SerialiableMember serialiableMember, object container) {
    string key = ReadKey(buffer);
    // snip...
}

private static string ReadKey(ByteBuffer buffer) {
    var formatCode = Encoder.ReadFormatCode(buffer);
    string key;

    if (formatCode == FormatCode.String8Utf8 || formatCode == FormatCode.String32Utf8) {
        key = Encoder.ReadString(buffer, formatCode);
    } else {
        key = Encoder.ReadSymbol(buffer, formatCode);
    }

    return key;
}
```

**Comment by xinchen10** [comment]
Yes that could be done. It will make encoder and decoder asymmetric but I think as long as other clients can decode Symbol keys, it should be fine. Do you mind submitting a pull request for the changes?
