### ISSUE TITLE
Dispose on message

### ISSUE THREAD

**Issue by herecydev** [Azure/amqpnetlite#156]
In the message class there is a public [dispose method](https://github.com/Azure/amqpnetlite/blob/master/src/Message.cs#L252-L259). Is the creator of the message expected to call this, if so why is the class not decorated with `IDisposable` so it can correctly be used in conjunction with the `using` statement?

**Comment by xinchen10** [comment]
The major usage of this method is for using a buffer manager. Here is an article (work in progress) about it.
https://github.com/Azure/amqpnetlite/blob/working/docs/articles/buffer_management.md

I think it makes sense to make the message class `IDisposable`.
