### ISSUE TITLE
Receiver does not receive message from topic

### ISSUE THREAD

**Issue by kumarasami** [Azure/amqpnetlite#157]
I can able to send message to topic ("topicName") but i am unable to receive message from same address with same topic. Whats wrong on this? Can you help me?

// .Net framework 3.5
using Amqp;
using System;
using System.Collections.Generic;
using System.Text;

namespace Sender
{
    class Program
    {
        static void Main(string[] args)
        {
            Address address = new Address("amqp://guest:guest@aaaa:5672");
            Connection connection = new Connection(address);
            Session session = new Session(connection);

            Message message = new Message("Hello Message");
            SenderLink sender = new SenderLink(session, "name", "topic://topicName");
            sender.Send(message);
            sender.Close();

            ReceiverLink receiver = new ReceiverLink(session, "name1", "topic://topicName");
            Message message1;
            while ((message1 = receiver.Receive(1)) != null)
            {
                receiver.Accept(message1);
                Console.WriteLine(message1.Body.ToString());
            }
            
            receiver.Close();

            Console.ReadKey();

            session.Close();
            connection.Close();
        }
    }
}

**Comment by xinchen10** [comment]
Which broker are you using?

The receive timeout is 1 millisecond which is too small. Try a large timeout or simply use the default. The timeout value only affects the wait time when no messages are available. If a message is available, the call returns right away, so using a small value does not give you messages faster.

**Comment by kumarasami** [comment]
Broker: Apache ActiveMQ, Version: 5.13.0

I used Amqp.Net35.dll for sending and receiving message.

http://aaaa:8161/../topics
That web page shown that No. of consumer count as 1 when i am trying to connect the particular topic for receiving.

And also i have changed timeout to default.
while ((message1 = receiver.Receive()) != null)

Even i didn't receive any message.
Any idea?

**Comment by ChugR** [comment]
You may want to start the receiver before you send the message. When the message arrives at the broker the topic will forward the messages to all connected consumers and in this case there is none. The receiver connects to the topic after the message has come and gone.

Or run the receiver and sender as separate programs and then you can start them in any order for testing.

The usual protocol logging helps reveal clues, too. Add this to the start of main():

> Trace.TraceLevel = TraceLevel.Frame;
> Trace.TraceListener = (f, a) => System.Diagnostics.Trace.WriteLine(DateTime.Now.ToString("[hh:mm:ss.fff]") + " " + string.Format(f, a));

**Comment by kumarasami** [comment]
Thank you!
