### ISSUE TITLE
How to send Persistent message to broker

### ISSUE THREAD

**Issue by kumarasami** [Azure/amqpnetlite#158]
How to send Persistent message to broker (Apache ActiveMQ v5.13.0)?

`            Address address = new Address("amqp://guest:guest@aaaa:5672");
            Connection connection = new Connection(address);
            Session session = new Session(connection);
            
            Message message = new Message("Hello");
            
            SenderLink sender = new SenderLink(session, "name", @"topic://topicName");
            
            sender.Send(message);
            sender.Close();
`

**Comment by christian-morin** [comment]
Set the Durable property to true in the Header of the message.

`message.Header = new Header() {Durable = true};`

**Comment by kumarasami** [comment]
Thanks
