### ISSUE TITLE
Epoch error

### ISSUE THREAD

**Issue by unaizorrilla** [Azure/amqpnetlite#162]
Hi, I', trying to review of this library with Azure EventHub, and after some tests the receiver link always throw the exception:

"At least one receiver for the endpoint is created with epoch of '22', and so non-epoch receiver is not allowed. Either reconnect with a higher epoch, or make sure all epoch receivers are closed or disconnected."

Any idea?

Thanks in advance!

**Comment by xinchen10** [comment]
You probably have another application that reads from the Event Hub using EventProcessorHost. EventProcessorHost sets an epoch on the receiver to ensure only one active reader for a given consumer group and an event hub partition. You can try it with a different consumer group.

**Comment by unaizorrilla** [comment]
Umm probably is the checkpointing on eventprocessorhost... Many thanks!!

El 14 oct 2016, a las 22:54, Xin Chen <notifications@github.com<mailto:notifications@github.com>> escribi?:


You probably have another application that reads from the Event Hub using EventProcessorHost. EventProcessorHost sets an epoch on the receiver to ensure only one active reader for a given consumer group and an event hub partition. You can try it with a different consumer group.

-
