### ISSUE TITLE
using a user-provided custom transport

### ISSUE THREAD

**Issue by mbroadst** [Azure/amqpnetlite#163]
I see that there are pluggable transports, however I'm not quite sure I understand how I would be able to provide my own transport for a given Connection. Is that possible? 

There does appear to be an internal ctor that allows an `IAsyncTransport` to be passed in: https://github.com/Azure/amqpnetlite/blob/master/src/Connection.cs#L144. But otherwise, it looks like the "extensibility" is in fact just a number of hardcoded sections here: https://github.com/Azure/amqpnetlite/blob/master/src/Connection.cs#L352.

Am I reading this correctly? Maybe I'm missing something.

**Comment by xinchen10** [comment]
To use this feature, you must create the connection using [ConnectionFactory](https://github.com/Azure/amqpnetlite/blob/master/src/Net/ConnectionFactory.cs#L57). The listener side also has to support this transport type.

Please take a look at the [PeerToPeer.CustomTransport](https://github.com/Azure/amqpnetlite/blob/master/Examples/PeerToPeer/PeerToPeer.CustomTransport/Program.cs) example which shows a [named pipe](https://github.com/Azure/amqpnetlite/blob/master/test/Common/NamedPipeTransport.cs) custom transport implementation.

```
const string address = "pipe://guest:guest@localhost/custom_transport";
const string nodeName = "messages";

static void Main(string[] args)
{
    //Create host and register custom transport listener
    var uri = new Uri(address);
    var host = new ContainerHost(new List<Uri>() { uri }, null, uri.UserInfo);
    host.CustomTransports.Add("pipe", NamedPipeTransport.Listener);
    host.RegisterMessageProcessor(nodeName, new MessageProcessor());
    host.Open();
    Console.WriteLine("Listener: running");

    //Create factory with custom transport factory
    var factory = new ConnectionFactory(new TransportProvider[] { NamedPipeTransport.Factory });
    var connection = factory.CreateAsync(new Address(address)).GetAwaiter().GetResult();
    var session = new Session(connection);
    var sender = new SenderLink(session, "message-client", nodeName);
    Console.WriteLine("Client: sending a message");
    sender.Send(new Message("Hello Pipe!"));
    sender.Close();
    session.Close();
    connection.Close();
    Console.WriteLine("Client: closed");

    host.Close();
    Console.WriteLine("Listener: closed");
}
```

**Comment by mbroadst** [comment]
@xinchen10 ah, thank you. For some reason I missed the `ConnectionFactory` approach, was only creating `Connection` objects directly.

**Comment by mbroadst** [comment]
Is this supported in NET35?

**Comment by xinchen10** [comment]
It is not supported in net35. The async transport is based on Task and async/await, which is not available in net35.
