### ISSUE TITLE
Accepting expired message

### ISSUE THREAD

**Issue by herecydev** [Azure/amqpnetlite#164]
The messages have a lock annotation on them `x-opt-locked-until`. When using the receiver link's message pump, and holding on to the message past the lock time, calling accept has no effect and the message is reacquired again. See the following example:

``` c#
_receiverLink.Start(10, Handle);

private void Handle(ReceiverLink receiverLink, Message message)
        {
            try
            {
                //sleep for 80s ( > default of 60s)
                receiverLink.Accept(message);
            }
            catch
            {   //no errors ?
                receiverLink.Reject(message, new Amqp.Framing.Error());
            }
        }
```

I assume the accept will prevent further redeliveries for that message, but that message will have been redelivered when the lock expired. Is that correct?

**Comment by xinchen10** [comment]
The library currently does not handle responses for message acknowledgement calls (accept, release, reject, etc). In other words, these calls are best effort (or fire and forget). For Service Bus, the recommended approach is to call the lock renewal API to keep the message lock alive, or simply set a large lock duration on the entity if message processing takes time.
We could add support for this to the client if it is useful in general to work with popular AMQP brokers.

**Comment by Blackbaud-DanHamlin** [comment]
Does this library have a way to renew the lock?

**Comment by xinchen10** [comment]
@Blackbaud-DanHamlin The library does not have a built-in API to do this. The Service Bus AMQP extensions are request/response operations based on the [standard AMQP management mechanism](https://www.oasis-open.org/committees/document.php?document_id=54441&wg_abbrev=amqp), so it should be possible to implement it using this library. The details of the Service Bus operations can be found here: https://msdn.microsoft.com/en-us/library/mt727956.aspx

The lock token of a peek-locked message can be obtained from Message.DeliveryTag which is a byte array of the AMQP encoded Guid (uuid).
