### ISSUE TITLE
Connection is left half-dead if an exception is thrown handling AMQP frames

### ISSUE THREAD

**Issue by imiuka** [Azure/amqpnetlite#166]
Found this one while debugging #165. If an exception is thrown in one of the handlers (let's say `ReceiverLink::OnDelivery`), it will bubble up to the `Session`, then to the [`Connection::OnFrame`](https://github.com/Azure/amqpnetlite/blob/4a158b1f9bf1fef2a13431472ec699d90ca2f861/src/Connection.cs#L629).

The [`Connection::OnFrame`](https://github.com/Azure/amqpnetlite/blob/4a158b1f9bf1fef2a13431472ec699d90ca2f861/src/Connection.cs#L629) method sends a close frame (inside [`Connection::OnException`](https://github.com/Azure/amqpnetlite/blob/4a158b1f9bf1fef2a13431472ec699d90ca2f861/src/Connection.cs#L643) because `connection.state == State.Opened`), and then returns `false` to signal that the connection should no longer continue.

The [`AsyncPump`](https://github.com/Azure/amqpnetlite/blob/4a158b1f9bf1fef2a13431472ec699d90ca2f861/src/Net/AsyncPump.cs#L68) interprets the `false` return value to mean it should break out of the message pump, effectively ending further frame processing. If we have calls in-flight (for example, to `SenderLink::Send`), they will never complete and be stuck in-progress, waiting for a response. The heartbeat timer will still continue to send empty frames, though.

Eventually the server will send back a close frame, which we would normally handle and tear down all sessions and links, but because the message pump exited earlier that no longer happens. So if we encounter an unrecoverable exception, either we need to immediately tear down the whole connection and immediately transition into `State.End`, or keep the message pump alive.

**Comment by xinchen10** [comment]
Fix available in v1.2.2.
