### ISSUE TITLE
custom transport receiving issues

### ISSUE THREAD

**Issue by mbroadst** [Azure/amqpnetlite#167]
Hi,

I'm trying to write a custom transport which works over a character device (in this case a serial port exposed by qemu into windows). The basic idea here is that I need to use `CreateFile`/`ReadFile`/`WriteFile` to transfer data over a "file" provided by the driver. In order to work with the file it has to be opened in "overlapped" mode, and by nature reads and write are asynchronous. I've implemented all of this wrapped in a `Stream` subclass, for writes I just send-and-forget, whereas for reads I have an internal long running `Task` which reads from the file periodically and buffers the results to an internal circular buffer. 

For the past hour I've been scratching my head because my custom transport was throwing an `ObjectDisposedException` and I couldn't for the life of my figure out where I had screwed the code up. It finally occurred to me to check the source for this library and I found the following: https://github.com/Azure/amqpnetlite/blob/master/src/Framing/Reader.cs#L56.  What I think is happening is that AMQP.Net Lite is trying to make a read before the internal thread has picked up any response, getting a read size of 0 and throwing the `ObjectDisposedException`.  I'm not sure how to get around this problem, so any help would be welcome!

Are there any specific notes on requirements for implementing a custom transport? 

**UPDATE:** I should have mentioned this is being implemented against .NET 4.0

**Comment by xinchen10** [comment]
Read operations performed on IAsyncTransport are by [AsyncPump](https://github.com/Azure/amqpnetlite/blob/master/src/Net/AsyncPump.cs) class. If IAsyncTransport.ReceiveAsync method retuns 0 bytes, it also throws ObjectDisposedException. The expectation from TransportProvider is that, after CreateAsync is completed, the transport is ready for read and write operations. The library will only perform I/O operations after that.

Do you return 0 bytes if the circular buffer is empty? In that case if the file handle is not closed, you would need to keep the task pending until data is received.

**Comment by mbroadst** [comment]
@xinchen10 sorry this was my lack of C# knowledge at play. I was providing a `ReadAsync` on my `Stream` subclass that was never actually being called, instead it was calling some automatically provided wrapper around the synchronous `Read`!

**Comment by mbroadst** [comment]
@xinchen10 still having issues. With the following example code: 
```
var factory = new ConnectionFactory(new TransportProvider[] { MyTransport.Factory });
var connection = factory.CreateAsync(new Address(address)).GetAwaiter().GetResult();
var session = new Session(connection);
var sender = new SenderLink(session, "message-client", nodeName);
```

I can tell from the trace logs that I get through all of the SASL handshake, and the `Open` handshake is completed. At that point the `AsyncPump` is created [here](https://github.com/Azure/amqpnetlite/blob/master/src/Net/ConnectionFactory.cs#L151) and then I never actually reach the creation of the `Session` above because the `GetAwaiter().GetResult()` blocks indefinitely waiting for [4 new incoming bytes for a new frame](https://github.com/Azure/amqpnetlite/blob/master/src/Net/AsyncPump.cs#L58).

I'm using an `AutoResetEvent` to trigger incoming data from my device reader thread so I _do_ actually get further trace logs because the broker is sending heartbeats, however the Connection never properly resolves and the program is hung after open. Any hints here?

**Comment by mbroadst** [comment]
My lack of C# knowledge strikes again :) Sorry for all the noise here!

**Comment by xinchen10** [comment]
@mbroadst did you get everything working? It would be super cool to see AMQP travelling over a serial port!

**Comment by mbroadst** [comment]
@xinchen10 not quite yet, I'm still having some issues with transmission over the port itself :) I'll keep you posted!

**Comment by mbroadst** [comment]
@xinchen10 somehow the transport is emitting the following hex for the transfer frame: `000000000000000000000000003602000000005314C0110B4343A004000000004342404040404041005377A11348656C6C6F2066726F` Which looks like is padded with a whole bunch of extra leading 0's (5 bytes it seems)

**Comment by xinchen10** [comment]
In your IAsyncTransport.SendAsync implementation, for each ByteBuffer, the valid payload starts from ByteBuffer.Offset and the count is ByteBuffer.Length. By any chance you read bytes from offset 0?

**Comment by mbroadst** [comment]
@xinchen10 that was definitely it. The device is actually a character device so it doesn't support writing binary data to it, so I've just been converting everything to hex to wire it over and missed an offset there, whoops.

**Comment by mbroadst** [comment]
@xinchen10 
![Great Happiness](http://g.recordit.co/Q5EiovcRL8.gif)

Custom transport communicating over a virtio-serial port in windows on the right side. A small proxy I wrote using `amqp10` in node.js on the top left, which proxies to a local `qpidd` instance. Bottom left is a listener using `amq10` again to receive messages off the `amq.topic` exchange. Looks like the experiment worked :)

**Comment by xinchen10** [comment]
That's cool! I was planning to write an article/tutorial for the custom transport. This is definitely a useful reference.

**Comment by mbroadst** [comment]
I'm definitely willing to contribute code to that, this stuff is by no means proprietary or otherwise encumbered. Plus, I'd appreciate if someone who knows C# better than I would look it over for obvious inefficiencies 😄
