### ISSUE TITLE
Issue with version 1.2.1 while unregistering message processor.

### ISSUE THREAD

**Issue by ptrived** [Azure/amqpnetlite#169]
In the recent upgrade to version 1.2.1, it seems there is some issue while unregistering the MessageProcessor in the ContainerHost class. This issue was not seen in the version 1.1.8.
Below is a brief description about the issue and steps to reproduce the issue.

_Description_: This issue is seen when you call UnregisterMessageProcessor() from the ContainerHost. So when UnregisterMessageProcessor(), it eventually calls Dispose() method from the abstract class Collection<T>. The issue is in the Dispose method where it iterates over the keys of the collection and in the body of each iteration, link.Close() is called , which eventually calls the OnLinkClosed() from the Collection<T> class. The OnLinkClosed() method tries to remove the link from the collection which results in InvalidOperationException.

Exception Message:	 
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

_Steps to reproduce the issue_: I downloaded the amqp project and added a sample test to the ContainerHostTests test class. So to reproduce the issue, just add the below test to ContainerHostTests class and run the test.

        [TestMethod]
        public void ContainerHostMessageProcessorUnregisterTest()
        {
            string name = "ContainerHostMessageProcessorTest";
            var processor = new TestMessageProcessor();
            this.host.RegisterMessageProcessor(name, processor);

            int count = 5;
            var connection = new Connection(Address);
            var session = new Session(connection);
            var sender = new SenderLink(session, "send-link", name);

            for (int i = 0; i < count; i++)
            {
                var message = new Message("msg" + i);
                message.Properties = new Properties() { GroupId = name };
                sender.Send(message, SendTimeout);
            }

            this.host.UnregisterMessageProcessor(name);
        }

_Note : Just to give a try, I changed the Dispose method to below and then this test passed:

            void IDisposable.Dispose()
            {
                lock (this.collection)
                {
                    foreach (var link in this.collection.Keys.ToList())
                    {
                        link.Close(0, new Error()
                        {
                            Condition = ErrorCode.DetachForced,
                            Description = "Source was unregistered."
                        });
                    }

                    this.collection.Clear();
                }
            }

**Comment by xinchen10** [comment]
Fix available in v1.2.2.
