### ISSUE TITLE
amqp:internal-error trying to implement renew-lock for ServiceBus

### ISSUE THREAD

**Issue by Blackbaud-CameronBlack** [Azure/amqpnetlite#173]
Hi, I am trying to implement the renew-lock mentioned in #164 .

I am using the documentation from the page referenced on [renew-lock](https://msdn.microsoft.com/en-us/library/mt727956.aspx).

If I call the renew-lock on a partitioned topic, I get the following message:
 
**This SDK does not support operation 'com.microsoft:renew-lock' for an entity with partitioning enabled. Please use a newer version of the SDK**

If I try to renew a lock on a non-partitioned topic, I get the following:

**errorCondition: {amqp:internal-error}
statusCode: 0x000001f4
The service was unable to process the request; please retry the operation.** 

Here's some sample code to recreate.  I am hoping it is something simple, like possibly in the way that I have the BodySection implemented.  Do you have any pointers?  Or is renewing a lock on Service Bus through this library simply not possible?  If it is possible, will we be able to renew a lock on a partitioned topic as well?  Maybe via implementing x-opt-partition-key somehow?

Thanks for your time....

```
public static async Task RenewLock(string connectionString, Message message, string topic, string subscription, int lockDurationMilliseconds)
{
    var lockToken = new Guid(message.DeliveryTag).ToString();
    var entityAddress = $"{topic}/Subscriptions/{subscription}";
    var managementNodeAddress = $"{entityAddress}/$management";
    var renewLockSenderAddress = $"{subscription}-renew-lock-sender";
    var renewLockReceiverAddress = $"{subscription}-renew-lock-reply-to";

    var senderAttach = new Attach()
    {
        Source = new Source() { Address = renewLockSenderAddress },
        Target = new Target() { Address = managementNodeAddress }
    };

    var recieverAttach = new Attach()
    {
        Source = new Source() { Address = managementNodeAddress },
        Target = new Target() { Address = renewLockReceiverAddress },
    };

    var connection = await Amqp.Connection.Factory.CreateAsync(new Amqp.Address(connectionString));
    var renewLockSession = new Session(connection);
    var renewLockSenderLink = new Amqp.SenderLink(renewLockSession, "renew-lock-sender", senderAttach, null);
    var renewLockReceiverLink = new Amqp.ReceiverLink(renewLockSession, "renew-lock-receiver", recieverAttach, null);

    Console.WriteLine(message.Properties.MessageId);

    var renewLockMessage = new Message()
    {
        ApplicationProperties = new ApplicationProperties(),
        Properties = new Properties()
        {
            MessageId = message.Properties.MessageId,
            ReplyTo = renewLockReceiverAddress
        },
        BodySection = new Data() { Binary = Encoding.UTF8.GetBytes($"['map',['string', 'lock-tokens'], ['array', 'uuid', '{lockToken}']]") }
    };
    renewLockMessage.ApplicationProperties["operation"] = "com.microsoft:renew-lock";
    renewLockMessage.ApplicationProperties["com.microsoft:server-timeout"] = lockDurationMilliseconds;

    await renewLockSenderLink.SendAsync(renewLockMessage);

    var renewLockResponse = await renewLockReceiverLink.ReceiveAsync();

    await renewLockSenderLink.CloseAsync();
    await renewLockReceiverLink.CloseAsync();
    await renewLockSession.CloseAsync();
    await connection.CloseAsync();
}

```

**Comment by xinchen10** [comment]
LockToken is of type Guid, so the line to create the lockToken should be,
```
    var lockToken = new Guid(message.DeliveryTag);
```

The request body is AmqpValue containing a map. It should be created like this,
```
        BodySection = new AmqpValue() { Value = new Map() { { "lock-tokens", new Guid[] { lockToken } } } }
```

**Comment by Blackbaud-CameronBlack** [comment]
Thank you very much for the corrections, the changes work for non-partitioned topics now.  Can I get your opinion on how to do the same for partitioned ones?  Adding **x-opt-partition-key** to the **MessageAnnotations** seems to work, but I am not sure if you can just supply an arbitrary value for this?

Are there any corrections that you see that I should make to this code?

Again, thank you for your time, I really appreciate the help.

```
// Assume BrokeredMessage is a thin wrapper around Message with extra properties added
// for LockToken and LockedUntil
public async Task<HttpStatusCode> RenewLock(BrokeredMessage brokeredMessage)
{
    // Based off of https://msdn.microsoft.com/en-us/library/mt727956.aspx
    var renewLockMessage = new Message()
    {
        ApplicationProperties = new ApplicationProperties
        {
            ["operation"] = "com.microsoft:renew-lock",
            ["com.microsoft:server-timeout"] = this.serverTimeout
        },
        Properties = new Properties()
        {
            MessageId = brokeredMessage.Id,
            ReplyTo = this.renewLockReceiverAddress
        },
        MessageAnnotations = new MessageAnnotations()
        {
            [new Symbol("x-opt-partition-key")] = this.groupId  // Can this be anything?
        },
        BodySection = new AmqpValue() { Value = new Map() { { "lock-tokens", new Guid[] { brokeredMessage.LockToken } } } }
    };

    await this.renewLockSenderLink.SendAsync(renewLockMessage);

    var renewLockResponse = await this.renewLockReceiverLink.ReceiveAsync();
    if (renewLockResponse == null || renewLockResponse.Properties == null || renewLockResponse.ApplicationProperties == null)
    {
        return HttpStatusCode.BadRequest;
    }

    int statusCode = (int)renewLockResponse.ApplicationProperties["statusCode"];
    if (statusCode == (int)HttpStatusCode.OK)
    {
        var body = renewLockResponse.GetBody<Dictionary<string, DateTime[]>>();
        brokeredMessage.LockedUntil = body["expirations"][0];
    }

    return (HttpStatusCode)statusCode;
}

```

**Comment by xinchen10** [comment]
@Blackbaud-CameronBlack what error did you get for partitioned topic? Is it an exception thrown from an API call? If not, what's renewLockResponse message application properties? There should be statusCode, errorCondition and description you can check.

btw, I tried your code in the first post (with corrections) and it works on a partitioned topic.

**Comment by Blackbaud-CameronBlack** [comment]
If I comment out the **MessageAnnotations**  section above, I get this as a response:

statusCode: 501
statusDescription: "This SDK does not support operation 'com.microsoft:renew-lock' for an entity with partitioning enabled. Please use a newer version of the SDK. TrackingId:aacf75f6-ca7c-4771-a369-87e87473f4d9_G39, SystemTracker:NoSystemTracker, Timestamp:12/8/2016 7:59:55 PM"
errorCondition: {amqp:not-implemented}

**Comment by Blackbaud-CameronBlack** [comment]
I think it may have to do with leaving the links open between calls.   The original code (creating a new connection and links for each renew) does work on a partitioned topic.  The latest code (that creates the connection and links once and reuses them) works on a non-partitioned topic, but fails on a partitioned topic unless the x-opt-partition-key is supplied.

**Comment by Blackbaud-CameronBlack** [comment]
... and now it works in both scenarios (with or without x-opt-partition-key).  I could consistently recreate the issue up until about an hour ago.  Now it just started working.  Odd... thanks for the help!
