### ISSUE TITLE
 Recommended lifetimes for Connection, Session, and SendLink classes.

### ISSUE THREAD

**Issue by shaunluttin** [Azure/amqpnetlite#175]
"Send and receive methods on links are thread safe." That means we *can* use one connection/session/sender per application. What are the official recommendations, though?

* What is the recommended lifetime of a `Connection`? 
* What is the recommended lifetime of a `Session`? 
* What is the recommended lifetime of a `SenderLink`?

In the context of a web application, do you recommend transient, per request, or singleton lifetimes for each of those classes?

For instance, in the following case, we are using a transient lifetime. Would you recommend instead to use a per request or singleton lifetime? 
```
var connection = await Connection.Factory.CreateAsync(_address);
var session = new Session(connection);
var sender = new SenderLink(session, _senderName, _topicName);

var content = JsonConvert.SerializeObject(freightEstimate);
var message = new Message(content);

await sender.SendAsync(message);
```

@anthonychu @brian618

**Comment by xinchen10** [comment]
@shaunluttin It depends on your scenario and what service you are working with. If you send a message every 10 minutes, transient lifetime works. If you need to send 100 message every second to a cloud service, it does not.

Creating these object is not free. Connection has a tcp socket underneath (likely with SSL enabled). If possible, you should keep the connection open.

Session is very light weight.

Links are not super expensive to create, but the remote peer may require some operations (e.g. node lookup, authorization, resource allocating, etc.). You may see a higher latency for the very first message. If needed, you can also keep the link open.
