### ISSUE TITLE
Question: Unable to Serialize array of complex objects.

### ISSUE THREAD

**Issue by GeorgeHassan** [Azure/amqpnetlite#187]
Question,
I'm having difficulty serializing an array of complex objects.  When stepping into the AmqpSerializer I see it  is trying to find the AmqpContractAttribute for <CustomObjectType>[].  I have this attribute on the <CustomObjectType> class definition.  

I'm unaware of a way to instantiate a .net array of a specific type in a manner that allows us to place the Attribute on it.

Any help would be greatly appreciated.

**Comment by xinchen10** [comment]
This is currently not supported. Only array of primitive types are supported. As a workaround you can use List<T> where T is your custom type.

We will add support for array.
