### ISSUE TITLE
Ability to create topics/queues?

### ISSUE THREAD

**Issue by mikeinottawa** [Azure/amqpnetlite#189]
Hi there, we've used topic example but I don't see a way of dynamically creating queues or topics; it looks for a pre-defined endpoint. Is there a solution that I am missing?

**Comment by ChugR** [comment]
amqpnetlite provides the messaging framework to do the management tasks you mention. Look at https://www.oasis-open.org/committees/download.php/52425/amqp-man-v1/200-wd08.pdf for how management is done, in general, over AMQP. For managing a specific device like a broker you will also need the device's specs on what is manageable and what control is available over AMQP.

**Comment by mikeinottawa** [comment]
Thank you. I feel foolish now. 👍

**Comment by ChugR** [comment]
You're welcome. I know how you feel.

The Apache Qpid project has a management framework for the C++ broker. https://github.com/apache/qpid-cpp/tree/master/management/python This may not help you directly but it is a management-over-AMQP implementation that works for you to study.

**Comment by xinchen10** [comment]
@mikeinottawa are you using the Service Bus topic? Service Bus does not support the amqp-man protocol yet. To create a topic you would need to use the REST api or the SDK on .Net framework.
