### ISSUE TITLE
Outcome "released" when sending IoT Hub service-to-device message

### ISSUE THREAD

**Issue by georgeonofrei** [Azure/amqpnetlite#190]
Hello,

I am connecting to a device to send a command via "messages/devicebound" and I receive a lot of outcome "released". Every now and then I receive an "accepted", but 99% of the responses are "released".
Any idea what I may be doing wrong? Like not properly ending the communication or maybe this is queue specific issue and I need to set it up better?

To note: When I use DeviceExplorer (which uses the Azure.Devices package), the message is received and the device acts accordingly. It's not 100% always working, but around 95% of times the device responds as expected to my command.

Below is a trace of the communication. The code is copy-pasted from the samples and adjusted a bit.

> SEND AMQP 0 1.0.0 
> SEND (ch=0) open(container-id:99d7e3a6-294d-4cc6-aa1b-66d0d42e94b2,host-name:pilot-restore.azure-devices.net,max-frame-size:262144,channel-max:256) 
> SEND (ch=0) begin(next-outgoing-id:4294967293,incoming-window:2048,outgoing-window:2048,handle-max:4294967295) 
> SEND (ch=1) begin(next-outgoing-id:4294967293,incoming-window:2048,outgoing-window:2048,handle-max:4294967295) 
> SEND (ch=1) attach(name:cbs-sender,handle:0,role:False,source:source(),target:target(address:$cbs),initial-delivery-count:0) 
> SEND (ch=1) attach(name:cbs-reply-to,handle:1,role:True,source:source(address:$cbs),target:target()) 
> RECV AMQP 0 1 0 0 
> RECV (ch=0) open(container-id:DeviceGateway_66ee39c98fe54d8a9203112e75b002a2,host-name:10.0.4.52,max-frame-size:65536,channel-max:256,idle-time-out:240000) 
> RECV (ch=0) begin(remote-channel:0,next-outgoing-id:1,incoming-window:2048,outgoing-window:2048,handle-max:262143) 
> RECV (ch=1) begin(remote-channel:1,next-outgoing-id:1,incoming-window:2048,outgoing-window:2048,handle-max:262143) 
> RECV (ch=1) attach(name:cbs-sender,handle:0,role:True,source:source(),target:target(address:$cbs),max-message-size:1048576) 
> RECV (ch=1) flow(next-in-id:4294967293,in-window:2048,next-out-id:1,out-window:2048,handle:0,delivery-count:0,link-credit:100,available:0,echo:False) 
> SEND (ch=1) transfer(handle:0,delivery-id:0,delivery-tag:00000000,message-format:0,settled:False,batchable:True) payload 354 
> RECV (ch=1) attach(name:cbs-reply-to,handle:1,role:False,source:source(address:$cbs),target:target(),initial-delivery-count:0,max-message-size:1048576) 
> RECV (ch=1) disposition(role:True,first:0,settled:True,state:accepted()) 
> SEND (ch=1) flow(next-in-id:1,in-window:2048,next-out-id:4294967294,out-window:2047,handle:1,delivery-count:0,link-credit:200,drain:False) 
> RECV (ch=1) transfer(handle:1,delivery-id:0,delivery-tag:01000000,message-format:0,more:False,batchable:False) payload 104 
> SEND (ch=1) detach(handle:0,closed:True) 
> RECV (ch=1) detach(handle:0,closed:True) 
> SEND (ch=1) detach(handle:1,closed:True) 
> RECV (ch=1) detach(handle:1,closed:True) 
> SEND (ch=1) end() 
> RECV (ch=1) end() 
> SEND (ch=0) attach(name:sender-link,handle:0,role:False,source:source(),target:target(address:/messages/devicebound),initial-delivery-count:0) 
> RECV (ch=0) attach(name:sender-link,handle:0,role:True,source:source(),target:target(address:/messages/devicebound),max-message-size:1048576) 
> SEND (ch=0) detach(handle:0,closed:True) 
> RECV (ch=0) flow(next-in-id:4294967293,in-window:2048,next-out-id:1,out-window:2048,handle:0,delivery-count:0,link-credit:1000,available:0,echo:False) 
> RECV (ch=0) detach(handle:0,closed:True) 
> SEND (ch=1) begin(next-outgoing-id:4294967293,incoming-window:2048,outgoing-window:2048,handle-max:4294967295) 
> SEND (ch=1) attach(name:cbs-sender,handle:0,role:False,source:source(),target:target(address:$cbs),initial-delivery-count:0) 
> SEND (ch=1) attach(name:cbs-reply-to,handle:1,role:True,source:source(address:$cbs),target:target()) 
> RECV (ch=1) begin(remote-channel:1,next-outgoing-id:1,incoming-window:2048,outgoing-window:2048,handle-max:262143) 
> RECV (ch=1) attach(name:cbs-sender,handle:0,role:True,source:source(),target:target(address:$cbs),max-message-size:1048576) 
> RECV (ch=1) flow(next-in-id:4294967293,in-window:2048,next-out-id:1,out-window:2048,handle:0,delivery-count:0,link-credit:100,available:0,echo:False) 
> SEND (ch=1) transfer(handle:0,delivery-id:0,delivery-tag:00000000,message-format:0,settled:False,batchable:True) payload 372 
> RECV (ch=1) attach(name:cbs-reply-to,handle:1,role:False,source:source(address:$cbs),target:target(),initial-delivery-count:0,max-message-size:1048576) 
> RECV (ch=1) disposition(role:True,first:0,settled:True,state:accepted()) 
> SEND (ch=1) flow(next-in-id:1,in-window:2048,next-out-id:4294967294,out-window:2047,handle:1,delivery-count:0,link-credit:200,drain:False) 
> RECV (ch=1) transfer(handle:1,delivery-id:0,delivery-tag:02000000,message-format:0,more:False,batchable:False) payload 104 
> SEND (ch=1) detach(handle:0,closed:True) 
> RECV (ch=1) detach(handle:0,closed:True) 
> SEND (ch=1) detach(handle:1,closed:True) 
> RECV (ch=1) detach(handle:1,closed:True) 
> SEND (ch=1) end() 
> RECV (ch=1) end() 
> SEND (ch=0) attach(name:receive-link,handle:0,role:True,source:source(address:/messages/servicebound/feedback),target:target()) 
> SEND (ch=0) flow(next-in-id:1,in-window:2048,next-out-id:4294967293,out-window:2048,handle:0,delivery-count:0,link-credit:200,drain:False) 
> RECV (ch=0) attach(name:receive-link,handle:0,role:False,source:source(address:/messages/servicebound/feedback),target:target(),initial-delivery-count:0,max-message-size:1048576) 
> SEND (ch=0) detach(handle:0,closed:True) 
> RECV (ch=0) detach(handle:0,closed:True) 
> SEND (ch=0) close()
> SEND (ch=0) close()

Thanks a lot!
George

**Comment by xinchen10** [comment]
@georgeonofrei which sample did you use and modify? Can you post your code here (after removing the credentials)?

**Comment by georgeonofrei** [comment]
Hi,

On further ivnestigation, it seems that when I don't use the outcomecallback, the device acts as expected.

so this does not work:
`            var outcomeCallback = new OutcomeCallback((message1, outcome, state) =>
            {
                
            });
            senderLink.Send(message, outcomeCallback, null);
            senderLink.Close();
`
and this works:
`            senderLink.Send(message);
            senderLink.Close();
`

Any ideas how I can somehow get the result of the send?

Regards,
George

**Comment by xinchen10** [comment]
@georgeonofrei this is expected behavior. You can find more details here: https://github.com/Azure/amqpnetlite/blob/master/docs/articles/building_application.md#sending-messages

The behaviors of the Send method with difference parameters are different: one is blocking and the other is non-blocking. When you have a callback, the Send method returns right away and the outcome is to be delivered to your callback when it arrives. If you close the link right after the Send call, the message is still pending and it will be released. However, on the receiver side, it processes the message first and then the link close, so you still have your messages enqueued.

Probably we should update the API doc to make it more obvious to notice the behavior difference.
