### ISSUE TITLE
Dotnet web socket for azure event hubs support

### ISSUE THREAD

**Issue by nrandell** [Azure/amqpnetlite#191]
It looks like there are a couple of issues getting it working under dotnet sending to azure event hubs.

The issues I've seen are:
- The WebSocketSubProtocol needs to be "AMQPWSB10"
- The path for azure event hubs needs to be "/$servicebus/websocket"

I can probably create a pull request to fix this, but it would be good to get a pre-release package built to support dotnet core as well. Are there any active plans for this?

**Comment by xinchen10** [comment]
@nrandell are you using a local package built from master?

We have a package for dotnet on nuget: AMQPNetLite.WebSockets 1.2.0 which is working against Service Bus/Event Hubs.

"AMQPWSB10" has been replaced by "amqp" in the AMQP WebSockets binding spec. Service Bus should support the new subprotocol name very soon.

The path needs to be included in the address. The following is a test using the 1.2.0 package.

```
        static async Task TestAsync()
        {
            Address wsAddress = new Address("wss://[KeyName]:[SASKey]@foo.servicebus.windows.net/$servicebus/websocket");
            int nMsgs = 4;

            ConnectionFactory connectionFactory = new ConnectionFactory(
                new TransportProvider[] { new WebSocketTransportFactory() });
            Connection connection = await connectionFactory.CreateAsync(wsAddress);
            Session session = new Session(connection);
            SenderLink sender = new SenderLink(session, "ws-sender", "eh1");

            for (int i = 0; i < nMsgs; ++i)
            {
                Message message = new Message("hello");
                message.Properties = new Properties() { MessageId = "msg" + i };
                message.ApplicationProperties = new ApplicationProperties();
                message.ApplicationProperties["sn"] = i;
                await sender.SendAsync(message);
            }

            await connection.CloseAsync();
        }
```

**Comment by nrandell** [comment]
Thanks for the reply.

Yes, I built a local package from master - mainly because the current package has a reference to System.Collections.NonGeneric.

Is there any way to have something that allows us to override AMQPWSB10 with "amqp" until Microsoft updates events hubs?

However I also wanted to make sure that other people could find the "/$servicebus/websocket" link. I spent most of the afternoon trying to work out how to connect, as the MS documentation said they did support web sockets on event hubs, but didn't say how. (Plus the annoying fact that I couldn't add a comment to the documentation)

**Comment by xinchen10** [comment]
@nrandell for subprotocol name, I think we can introduce a new constructor for WebSocketTransportFactory that takes a user specified subprotocol name to override the default one. For path the best we can do here is to add a sample under ServiceBus category for websockets.

**Comment by xinchen10** [comment]
@nrandell I added a new constructor for web socket transport factory and a new SB sample. Please reopen the issue if you see any other issues.
