### ISSUE TITLE
Send command using shared access key instead of generating SAS token

### ISSUE THREAD

**Issue by georgeonofrei** [Azure/amqpnetlite#194]
Hello,

Is it possible to use the shared access key directly instead of generating SAS tokens?

Thanks,
George

**Comment by georgeonofrei** [comment]
Answering my own question, address object has that available:

![image](https://cloud.githubusercontent.com/assets/15815781/23313894/683d0918-fa74-11e6-808f-53447fcc5392.png)

Thanks,
George

**Comment by georgeonofrei** [comment]
The only question that remains is whether I can use the policy name and shared access key as user/password.

Thank you,
George

**Comment by xinchen10** [comment]
@georgeonofrei yes, it is supported. If you create the address from a Uri string, the policy name and key need to be URL encoded; otherwise they should be provided as is.
https://github.com/Azure/amqpnetlite/blob/master/docs/articles/building_application.md#specifying-an-address
