### ISSUE TITLE
Passing the trace message severity to the TraceListener so it can be routed to the correct logging channel

### ISSUE THREAD

**Issue by ramtinkermani** [Azure/amqpnetlite#196]
To take advantage of Tracing facility of the library, developers need to set the **TraceLevel** and register a **TraceListener** as a callback so that developer can route a trace message to the appropriate Logging/Tracing channel of their choice.
When an Amqp.WriteLine() method is called in the library, based on the **TraceLevel** set by the developer AND the **TraceLevel** of the message, the **TraceListener** will or will not be called.
**However** when the **TraceListener** is called, no information about the original message's TraceLevel is passed to it which means the listener has no idea what the **TraceLevel** of the original message was and how to internally log this Amqp trace message. Should it be logged as an Error? As an Information? Verbose?
I was wondering if it would be possible that the message's **TraceLevel** could somehow be passed to the **TraceListener**.

**Comment by xinchen10** [comment]
@ramtinkermani thanks for the suggestion. It has been just added to the TraceListener delegate.

**Comment by ramtinkermani** [comment]
Thank you! That's great.
