### ISSUE TITLE
Testability

### ISSUE THREAD

**Issue by AndreasBieber** [Azure/amqpnetlite#197]
Hi folks,

we really appreciate the lib and want to use it, but we are currently facing some hard times testing our code using your lib.
The lib provides too less interfaces. Also, constructing a new `Connection` directly establishes a socket. Therefore it is simply not mock-/testable.
As we are developing in a CI environment, we strongly need to provide unittests (not only integrationtests).

Do you think there is a chance to introduce an appropiate level of abstraction?

Thanks in advance
Andy

**Comment by typusomega** [comment]
Same here

**Comment by AndreasBieber** [comment]
Any comment on this?

**Comment by xinchen10** [comment]
@AndreasBieber can you share more details about how much abstraction is needed to enable your test cases? If an IConnectionFactory interface is available to drive creation of all mocked objects, would that be good enough? Or you need abstraction of all public APIs?

Many folks create a wrapper over the library (e.g. in #199 the author created an AmqpClient class that hides the details of this library) which can be an abstraction for mocking. Inside the wrapper you would want to test the actual library to ensure it is working.

**Comment by AndreasBieber** [comment]
Hi @xinchen10,

thanks for your answer. To be honest, i think it's necessary to have an abstraction layer of the whole public API.
For example, we have classes that are using only the Session, another class is taking care of the ReceiverLink/SenderLink.
To provide UnitTests (doing TDD) for our solution it's inevitably necessary to have an abstraction layer for at least the following classes:

  * Connection
  * ConnectionFactory
  * Session
  * SenderLink
  * ReceiverLink
  * ContainerHost (IContainer) should provide Open(), Close(), RegisterXXXProcessor/Source(), Unregister...()
  
Thanks in advance

Cheers
Andy

**Comment by AndreasBieber** [comment]
Hi @xinchen10,

any news on this?

Cheers
Andy

**Comment by xinchen10** [comment]
I am still exploring options. It introduces quite a few changes to existing APIs.

**Comment by peteraritchie** [comment]
I added a throw-away PR that shows an example of adding interface to support this concept.  From a testability standpoint, for example, this is the type of thing I would be hopping to accomplish without having to create a bunch of my own interfaces and wrappers around the amqpnetlite classes:

		[Fact]
		public void DoesReceiverReceiveFromAmqpCorrectly()
		{
			// test-specific code
			IReceiverMessage messageReceived = null;
			var waitHandle = new ManualResetEventSlim();

			// create a mock receiver link to simulate a message
			// actually coming through receiver link as soon
			// as a message is requested
			var mockReceiverLink = new Mock<IReceiverLink>();
			mockReceiverLink.Setup(mock => mock.ReceiveAsync(It.IsAny<TimeSpan>())).Returns(Task.FromResult(new Message("my body")));

			// create our home-grown event-driven class instance
			var r = new AmqpReceiver(mockReceiverLink.Object, "queueName");

			// hook up event handler
			r.MessageReceived += (sender, e) =>
			{
				messageReceived = e.Message;
				waitHandle.Set();
			};

			// start the "listener"
			r.Start("*");

			// assert our constraints
			Assert.True(waitHandle.Wait(TimeSpan.FromSeconds(5)));
			Assert.NotNull(messageReceived);
			Assert.Equal("my body", messageReceived.GetStringValue(Encoding.UTF8));
		}

**Comment by xinchen10** [comment]
Hi everyone, based on the feedback and sample PR, I pushed some code to the api-updates branch. There you will find the public interfaces (sync part in IAmqpObject.cs, async part in TaskExtensions.cs and also IConnectionFactory.cs). This should cover most of the APIs on the client side. I didn't include all public methods to minimize the changes. Please let me know if you feel any changes are needed. Thanks a lot.
