### ISSUE TITLE
error when adding package to .net core class library

### ISSUE THREAD

**Issue by neutrongenious** [Azure/amqpnetlite#198]
`Package System.Collections.NonGeneric 4.0.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package System.Collections.NonGeneric 4.0.0 supports:
  - dotnet (.NETPlatform,Version=v5.0)
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - net46 (.NETFramework,Version=v4.6)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
One or more packages are incompatible with .NETCoreApp,Version=v1.1.
Package restore failed. Rolling back package changes for 'Atea.Esb.Framework.ServiceBus.Messaging'.
Time Elapsed: 00:00:01.0843610
========== Finished ==========`

**Comment by xinchen10** [comment]
This dependency has been removed in the current master branch. We will release a new package soon but the exact time is not determined yet.

**Comment by neutrongenious** [comment]
any plans to may be do a pre-release package?

this is huge dependency on one of our micro service.

**Comment by xinchen10** [comment]
https://www.nuget.org/packages/AMQPNetLite.Core/2.0.0-pre

**Comment by pableess** [comment]
Is it possible to do a pre-release of the WebSockets package that also removes this dependency?

**Comment by xinchen10** [comment]
https://www.nuget.org/packages/AMQPNetLite.WebSockets/2.0.0-pre
