### ISSUE TITLE
How to send a message with a body that is an object of a custom type

### ISSUE THREAD

**Issue by rr118** [Azure/amqpnetlite#2]
I am having trouble figuring out how to send a message with custom types. I can see that the serializer supports custom types by using AmqpContract and AmqpMember. However I cannot figure out how to deserialize the message body back to the type instead of the described type. Is this possible? I have started an example here. 

https://github.com/rr118/amqpnetlite/tree/master/Examples/PeerToPeer/PeerToPeer.CustomType

At line 15 of MessageProcessor I do not know how to deserialize the message body back to a person type. Could you explain what I am missing please? Once I can finish this example I will submit it with a pull request.

Thanks,

Rob

**Comment by xinchen10** [comment]
Try:
```
var message = messageContext.Message;
var person = message.GetBody<Person>();
```

This allows you to send an object across network without worrying about serialization. The object is serialized as an AMQP described list and sent inside an AmqpValue message, so it is interoperable with other clients.

**Comment by rr118** [comment]
That did the trick. Thanks. I submitted a pull request for a peer to peer example with custom types. Let me know if I need to change anything.
