### ISSUE TITLE
When will the next NuGet package be released?

### ISSUE THREAD

**Issue by rr118** [Azure/amqpnetlite#20]
There have been a few important issues that have been addressed since the last NuGet package release (https://github.com/Azure/amqpnetlite/issues/10, https://github.com/Azure/amqpnetlite/issues/5,  https://github.com/Azure/amqpnetlite/issues/4 and soon possibly https://github.com/Azure/amqpnetlite/issues/9). When do you plan to release the next version? Do you have any general guidelines for changes that justify a release?

**Comment by xinchen10** [comment]
I just created a release today with fixes for all above issues except #9.
http://www.nuget.org/packages/AMQPNetLite/1.1.1

There is no fixed schedule for releases. I will create one after important issues have been fixed. If you need a fix that is important for your scenario, feel free to open an issue to request a release.

**Comment by rr118** [comment]
Awesome. Thanks!

**Comment by rr118** [comment]
Could you make a branch for version 1.1.1 so that if there is a problem with the package it is easy to troubleshoot with the matching source please?

**Comment by xinchen10** [comment]
v1.1.1 is tagged so it should be easy to get the sources either from the repo or the source attachment in the release.

Previous releases were created in codeplex. Under [DOWNLOADS](https://amqpnetlite.codeplex.com/releases) you should see all the releases. You can view the sources by following the Change Set commit id, or just download the source code from the attachment.

From now on all releases will be done on GitHub with version tags, so it should be easier to get the matching source.

**Comment by mbroadst** [comment]
@xinchen10 is there a release schedule, or list of qualifications for a NuGet release? You've fixed a number of issues required for my particular use case in the past few days, and it would be ideal to continue use NuGet for that rather than building a copy of AMQP.Net Lite locally. Perhaps a 1.1.2 release for these small issues?

**Comment by xinchen10** [comment]
@rr118 v1.1.2 released yesterday

**Comment by rr118** [comment]
@mbroadst v1.1.2 is released. I think Xin meant to tell you instead of me.
