### ISSUE TITLE
Dynamic Queue Creation on Azure Service Bus

### ISSUE THREAD

**Issue by chriswrightwk** [Azure/amqpnetlite#200]
As I understand it, it's possible to create queues on the fly when using the Service Bus client. Is it possible to do the same using the amqpnetlite client? I'd like to avoid having to set the queues up in advance.

**Comment by xinchen10** [comment]
The SB client creates queues using the REST api. This library only supports AMQP. At this point ASB does not support management operations over AMQP. The REST protocol for creating a queue is straightforward. You could do it with a simple HTTP PUT.

**Comment by chriswrightwk** [comment]
Thanks for the suggestion - I'll give it a try.
