### ISSUE TITLE
ActiveMQ vs AMQP .NET Lite versions

### ISSUE THREAD

**Issue by benboo** [Azure/amqpnetlite#201]
This is also up [on Stackoverflow as a question here](http://stackoverflow.com/q/43038083/2875848).

ActiveMQ, as per line 151 in AmqpWireFormat, refuses connections with a AMQP protocol version other than 1.0.0.

AMQP .NET Lite, as per line 411 in Connection, sends 0.1.0.0. At the same time it claims to do Full control of AMQP 1.0 protocol behavior.

Obviously ActiveMQ refuses connections from AMQP .NET Lite with "Connection attempt from non AMQP v1.0 client. AMQP,0,1,0,0".

Where to, from here?

**Comment by DrEsteban** [comment]
I am also blocked here.

**Comment by xinchen10** [comment]
The header format is "AMQP [protocol id] 1 0 0". Protocol Id of 0 means AMQP. By default ActiveMQ requires authentication (through SASL). You can either include the user name and password in the address string, or set it on ConnectionFactory.SASL settings. Once that is set, there will be "AMQP 3 1 0 0" header to start SASL negotiation followed by "AMQP 0 1 0 0" header for AMQP connection negotiation. I have posted a code snippet on stackoverflow. It is also recommended to use ConnectionFactory.CreateAsync method to avoid blocking I/O.

**Comment by DrEsteban** [comment]
Thanks!  Setting username and password resolved this for me.

However, I still find it strange that AMQP.NET Lite doesn't throw any exceptions when ActiveMQ refused the connection.  So I still think there's a bug here.

**Comment by xinchen10** [comment]
@DrEsteban If I do not specify user login, I am getting an exception.
```
try
{
    string queueName = "q1";
    Connection connection = new Connection(new Address("amqp://localhost:5672"));
    Session session = new Session(connection);
    SenderLink sender = new SenderLink(session, "sender", queueName);
    Message message = new Message("Hello World");
    sender.Send(message);
    connection.Close();
}
catch (Exception e)
{
    Console.WriteLine(e.ToString());
}
```

```
System.Net.Sockets.SocketException (0x80004005): An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at Amqp.TcpTransport.TcpSocket.Amqp.ITransport.Send(ByteBuffer buffer) 
   at Amqp.TcpTransport.Amqp.ITransport.Send(ByteBuffer buffer)
   at Amqp.Connection.Writer.Amqp.ITransport.Send(ByteBuffer buffer) 
   at Amqp.Connection.SendCommand(UInt16 channel, DescribedList command) 
   at Amqp.Session..ctor(Connection connection, Begin begin, OnBegin onBegin) 
   at Amqp.Session..ctor(Connection connection) 
   at ConsoleApplication1.Program.Main(String[] args) 
```

**Comment by DrEsteban** [comment]
@xinchen10 Sorry I should have clarified.  I suppose I would expect the exception to be thrown when the connection was _created_, rather than on send.

**Comment by xinchen10** [comment]
@DrEsteban this is the chosen behavior for implementing the AMQP object state machine. State change is non-blocking. Since errors can happen at any time so application should expect exceptions from any API calls.

**Comment by DrEsteban** [comment]
@xinchen10 Understood! Thx.
