### ISSUE TITLE
Sending a message to deadletter queue on azure

### ISSUE THREAD

**Issue by oscarwest** [Azure/amqpnetlite#204]
Hello,

How would we go about sending a message that i'm processing to the deadletter queue?

Regards, Oscar

**Comment by xinchen10** [comment]
@oscarwest are you using the Azure Service Bus queue? Is your question about moving a message that you receive but cannot process to the deadletter queue?

**Comment by oscarwest** [comment]
@xinchen10 We are using Azure Service Bus Topics. Yes we would like to recieve a message, inspect it and possibly send it to the deadletter queue. 
AMQPNetLite: 1.2.1

Also, what is the difference between the following methods? The documentation is slightly ambiguous.

ReceiverLink.Accept(message);
ReceiverLink.Reject(message);
ReceiverLink.Release(message);

**Comment by xinchen10** [comment]
These methods map directly to the states of a messages defined by the protocol spec (section 3.4).
http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-complete-v1.0-os.pdf

The actual broker behavior is implementation specific and cannot be covered in the library documentation.

For Azure Service Bus, the rejected outcome is used to deadletter a message, so you can call the Reject method to move the message into the deadletter queue.
