### ISSUE TITLE
Waht is wrong with IAmqpSerializable

### ISSUE THREAD

**Issue by breitmark** [Azure/amqpnetlite#216]
I have a class ContextWallet, but Encode and Decode are never called:

`namespace abc
{
    [AmqpContract(Name = "xyz", Encoding = EncodingType.List)]
    public class ContextWallet : IAmqpSerializable
    {
        public ContextBase Context { get; set; }

        #region IAmqpSerializable
        public int EncodeSize
        {
            get
            {
                ByteBuffer buf = new ByteBuffer(0, true);
                Encode(buf);
                return buf.Length;
            }
        }

        public void Encode(ByteBuffer buffer)
        {
            if (Context == null)
            {
                Amqp.Types.Encoder.WriteSymbol(buffer, new Amqp.Types.Symbol("null"), true);
            }
            else
            {
                Context.Encode(buffer);
            }
        }

        public void Decode(ByteBuffer buffer)
        {
            Context = ContextBase.DecodeContext(buffer);
        }

       ... more methods
}`

and in the ContextBase class:

        private string _ContextType = null;
        private ContextBase _Parent = null;

        public string ContextType
        {
            get
            {
                if (string.IsNullOrEmpty(_ContextType))
                {
                    return this.GetType().FullName;
                }
                return _ContextType;
            }
            set
            {
                _ContextType = value;
            }
        }

        public void Encode(Amqp.ByteBuffer buffer)
        {
            Amqp.Types.Encoder.WriteSymbol(buffer, new Symbol(ContextType), true);

            Map map = new Map();
            FillPropMap(map);
            Amqp.Types.Encoder.WriteMap(buffer, map, true);
            if (Parent == null)
            {
                Amqp.Types.Encoder.WriteSymbol(buffer, new Symbol("null"), true);
            }
            else
            {
                Parent.Encode(buffer);
            }
        }

        public virtual void FillPropMap(Amqp.Types.Map map)
        {
            Type t = this.GetType();
            foreach (var p in t.GetProperties())
            {
                switch (p.Name)
                {
                    case "ContextType":
                    case "Parent":
                        // Ignore special properties
                        break;
                    default:
                        map.Add(p.Name, p.GetValue(this));
                        break;
                }
            }
        }

        public void Decode(Amqp.ByteBuffer buffer)
        {
            try
            {
                byte formatCode = Amqp.AmqpBitConverter.ReadUByte(buffer);
                if ((formatCode == FormatCode.Map8) || (formatCode == FormatCode.Map32))
                {
                    Amqp.Types.Map map = Amqp.Types.Encoder.ReadMap(buffer, formatCode);
                    InsertPropMap(map);
                }
                Parent = DecodeContext(buffer);
            }
            catch (Exception e)
            {
                Log.Error(e, "Decoding context data failed");
            }
        }

        public virtual void InsertPropMap(Amqp.Types.Map map)
        {
            Type t = this.GetType();
            foreach (var key in map.Keys)
            {
                var p = t.GetProperty(key.ToString());
                if (p != null)
                {
                    p.SetValue(this, map[key]);
                }
            }
        }

        public static ContextBase DecodeContext(Amqp.ByteBuffer buffer)
        {
            ContextBase ret = null;
            try
            {
                byte formatCode = Amqp.AmqpBitConverter.ReadUByte(buffer);
                if ((formatCode == FormatCode.Symbol8) || (formatCode == FormatCode.Symbol32))
                {
                    Symbol sym = Amqp.Types.Encoder.ReadSymbol(buffer, formatCode);
                    if (sym != "null")
                    {
                        ret = ContextManager.Instance.Create(sym);
                        if (ret != null)
                        {
                            ret.Decode(buffer);
                        }
                    }
                }
            }
            catch (Exception e)
            {
                Log.Error(e, "Decoding context symbol failed");
            }
            return ret;
        }

Can you please give me a hint!

**Comment by xinchen10** [comment]
Try removing AmqpContractAttribute from the ContextWallet class. The serializer resolves a type in the following order: AmqpContract -> Amqp Primitives -> IAmqpSerializable -> Enum -> Collections.

Since you have the AmqpContract attribute defined but no AmqpMember members, the object is written as an empty described list.

**Comment by xinchen10** [comment]
@breitmark it seems that you are trying to serialize an object of type ContextBase without explicit Contract/Member decorations. This is possible with other serializers (e.g. DataContract, Json, etc) but not supported right now by the AMQP serializer. We could enable it by using the class full name as the descriptor and adding all public properties/fields to a list/map. It will give better performance than your approach as the type will be compiled once instead of being reflected for every object instance. Do you think it will be useful?

**Comment by nextra-Team** [comment]
[Solved] Thank you! Your first comment helped a lot. Could you make that behaviour more visible in the documentation, please

**Comment by breitmark** [comment]
[Solved] Thank you! Your first comment helped a lot. Could you make that behaviour more visible in the documentation, please
