### ISSUE TITLE
Question: Is there a way to set the timeout for a SenderLink.SendAsync call in AMQPNetLite 1.2.3?

### ISSUE THREAD

**Issue by zmhh** [Azure/amqpnetlite#221]
I can see this is easy to do in the Master branch, and am wondering if there is a way to do so with the currently released version, 1.2.3?

**Comment by xinchen10** [comment]
It turns out that the timeout parameter is ignored in the SendAsync API in the master branch. That means only the synchronous Send method supports timeout. We will implement it for SendAsync. Thank you.
