### ISSUE TITLE
When connecting to WebSphere MQ 9 using amqp seeing exception

### ISSUE THREAD

**Issue by ompraash** [Azure/amqpnetlite#226]
![image](https://user-images.githubusercontent.com/28113831/31030165-f8acfabc-a519-11e7-9880-8c37678dc1ea.png)

> AMQXR0032E: ClientIdentifier '62acbe20-bf5b-4dd8-bbb6-1597302dfb02' has not specified an address to obtain the destination name.

Based on the documentation provided [here](https://github.com/Azure/amqpnetlite/blob/4be1050929b2efdbcd74a7650186c9983c7f34ea/docs/articles/hello_amqp.md), while trying the example for sender.exe an exception is thrown.

Error is generated @ `sender.Send(message);`

Another question is, based on `SenderLink sender = new SenderLink(session, "sender-link", "q1");`  "q1" is queue name or any random topic.

**Comment by xinchen10** [comment]
Can you enable tracing and share the output? The instructions can be found here.
https://github.com/Azure/amqpnetlite/blob/master/docs/articles/tracing.md

Remove credentials from the sasl-init log before posting it here.

**Comment by xinchen10** [comment]
Please reopen the issue when you have the traces available for investigation. Thanks.

**Comment by per-clausen-maersk** [comment]
The exception is thrown if `message.Properties.To` is null, must be set to e.g. `string.Empty`. 

Disposition from broker:
`disposition(role:True,first:0,last:0,settled:True,state:rejected(error:error(condition:amqp:not-found,description:AMQXR0032E: ClientIdentifier 'AMQP.Test.Sender.2' has not specified an address to obtain the destination name.)),batchable:False)`
