### ISSUE TITLE
Auto discovery of SessionId/Groups

### ISSUE THREAD

**Issue by jfloodnet** [Azure/amqpnetlite#227]
Is there a way to manage this in a similar manner to Sessions in Azure Service Bus?

E.g. this sample https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.ServiceBus.Messaging/Sessions

...shows how to manage all sessions, without having to know the Id's up front.

**Comment by xinchen10** [comment]
@jfloodnet if you are asking something similar to the session pump in SB sdk, then the answer is no. This library provides a way to lock a session using the AMQP primitives, i.e. attaching a receiver link with a session-filter in the source object. When a null value of session id is specified, the SB service returns one available session and you can receive messages in it with the receiver link in the usual way. You can either read the group-id property of a received message to determine the obtained session-id, or a OnAttached callback to extract the session-id from the returned attach.source.filters. More details can be found in this example code: https://github.com/Azure/amqpnetlite/blob/master/Examples/ServiceBus/Scenarios/MessageSessionExample.cs
