### ISSUE TITLE
Ability to get ReceiverLink Address from instance

### ISSUE THREAD

**Issue by mechanic22** [Azure/amqpnetlite#229]
I was trying to find out if there was a way to get the Address back out when I get an instance of a ReceiverLink.

IE

var receiver = new ReceiverLink(session, "my Name", "queue://my-queue");

how can I get "queue://my-queue" back out of the receiver object? Is that even possible?

**Comment by xinchen10** [comment]
That's not possible. It is not saved after link attach is initiated. There are a couple of workarounds application can do. From the library perspective, we could add an attribute bag on the AmqpObject class where application can attach app specific state to the object for later retrieval.

**Comment by mechanic22** [comment]
Ok, no big deal I will work around it in the application
