### ISSUE TITLE
Multithreaded environment

### ISSUE THREAD

**Issue by mechanic22** [Azure/amqpnetlite#230]
I am trying to utilize the AMQPNetLite library for a webapi instance and wondering if i am doing something wrong.

What I am trying to do is create a single connection to my broker and a single session. (Which are static in my request class). The request class uses queues to mimic a request response request to a microservice

Here is my current code:

    public async Task<Amqp.Message> RequestAsync(string queue, string subject, object body, TimeSpan? requestTimeout = null, TimeSpan? responseTimeout = null, uint? requestTtl = null)
    {
            var correlationId = Guid.NewGuid().ToString("N");
            var request = new Amqp.Message(body)
            {
                Header = new Amqp.Framing.Header() { Ttl = requestTtl ?? 10000 }, // Time to live: 10 seconds
                Properties = new Amqp.Framing.Properties() { ReplyTo = _clientId, CorrelationId = correlationId }
            };

            if (!string.IsNullOrEmpty(subject))
                request.Properties.Subject = subject;

            var eventWaitHandle = new ManualResetEvent(false);
            Amqp.Message response = null;
            Amqp.MessageCallback onMessage = (Amqp.IReceiverLink r, Amqp.Message msg) =>
            {
                if (msg.Properties.CorrelationId.Equals(correlationId))
                {
                    response = msg;
                    r.Accept(msg);
                    eventWaitHandle.Set();
                }
            };

            var receiver = new Amqp.ReceiverLink(_session, _clientId + ".receiver." + correlationId, _clientId);
            receiver.Start(300, onMessage);           

            sw = System.Diagnostics.Stopwatch.StartNew();
            var sender = new Amqp.SenderLink(_session, _clientId + ".sender." + correlationId, queue);

            await sender.SendAsync(request, requestTimeout ?? OneMinute);

            bool success = eventWaitHandle.WaitOne(responseTimeout ?? OneMinute);

            var closeTasks = new[] { receiver.CloseAsync(), sender.CloseAsync() };

            if (success)
                return response;
            else
                throw new TimeoutException();
    }

The problem I am having is if I await the SendAsync I dont get a response but if I change the line
    `await sender.SendAsync(request, requestTimeout ?? OneMinute);`
to 
   `var task = sender.SendAsync(request, requestTimeout ?? OneMinute);`

I get a response. 

So I have a couple questions:

- I tried to make a single ReceiverLink that everything replied to but noticed this would only process one response at a time, is there a way to make it process many messages in parrellel?
- I tried to make a SenderLink cache but noticed if I had to send two different messages in two different Tasks at the same time, it seemed like something would deadlock because the application would just hang. Should I be created a new connection/session/links? per thread? If that is the case, I feel like i would run into some performance issues.

Just curious what your thoughts are on the matter. Thanks

**Comment by mechanic22** [comment]
Also from a previous request I opened, you stated the onMessage callback was occuring on the I/O thread causing a sort of deadlock, which is the issue I think I am getting again. Also with that being said, does that mean only one message can be processed at a time?

**Comment by mechanic22** [comment]
So all in all my question is, can i use the same session across multiple threads to spawn and create multiple links to send and receive at the same time

**Comment by xinchen10** [comment]
@mechanic22 looks like you have figured out the issue. Just want to provide some information on async usage of the send/receive APIs. Since you are creating a pair of links for every request, I think it is safe to assume that there is only one response message over the receiver link. With that assumption, the code can be written as follows.
```
        public async Task<Message> RequestAsync(string queue, string subject, object body, TimeSpan? requestTimeout = null, TimeSpan? responseTimeout = null, uint? requestTtl = null)
        {
            var correlationId = Guid.NewGuid().ToString("N");
            var request = new Message(body)
            {
                Header = new Header() { Ttl = requestTtl ?? 10000 }, // Time to live: 10 seconds
                Properties = new Properties() { ReplyTo = _clientId, CorrelationId = correlationId }
            };

            if (!string.IsNullOrEmpty(subject))
                request.Properties.Subject = subject;

            TimeSpan timeout = requestTimeout ?? OneMinute;
            var sender = new SenderLink(_session, _clientId + ".sender." + correlationId, queue);
            var receiver = new ReceiverLink(_session, _clientId + ".receiver." + correlationId, _clientId);
            await sender.SendAsync(request, timeout);
            Message response = await receiver.ReceiveAsync(timeout);
            if (response != null)
            {
                receiver.Accept(response);
            }
            await sender.CloseAsync();
            await receiver.CloseAsync();

            if (response == null)
            {
                throw new TimeoutException("Response not received within time");
            }

            return response;
        }
```

This should be fine when the requests are infrequent. Otherwise, you may want to keep the pair of links.

**Comment by mechanic22** [comment]
Re-opening because I have a quick question hopefully.

In multiple threads should i reuse the connection object? 
If so should I be reusing my session object across multiple threads?

I only ask because I am trying to send multiple messages at the same time and it appears they are blocking each other.

I am currently reusing the connection and session objects across threads and creating new SenderLinks off the session. Just curious what you recommend. Thanks

**Comment by xinchen10** [comment]
Session does not really matter unless you need session level flow control and transaction management. Connection is bound to physical tcp connection so having all links in the same connection means that all traffic is going through the same tcp connection. To maintain frame order, the transport implementation does sequential writes to tcp socket so I/O may become a bottleneck if you have high throughput scenarios, especially when the network latency is high. There might also some lock contention if you have links in one connection running in multi-threads. Without knowing the details of the application specifics, it is hard to say which one is better. If you have only a few links it might be better to just use one connection for each. If you have to control the number of connections you would need to use a connection pool or partition the links.
