### ISSUE TITLE
SendAsync() timeout  but message still successfully sent

### ISSUE THREAD

**Issue by kdparkinson** [Azure/amqpnetlite#231]
ASP.net core 2 app sending messages to an Apache QPID message broker. Broker receives messages as expected when the body is small but if the body is to large the code times out at `await sender.SendAsync(message)`. I have attached traces for a successful message of small size and a larger 
one that times out.
[SuccessfulAMQPTrace28923CharString.txt](https://github.com/Azure/amqpnetlite/files/1422757/SuccessfulAMQPTrace28923CharString.txt)
[ErrorAMQPTrace57846CharString.txt](https://github.com/Azure/amqpnetlite/files/1422758/ErrorAMQPTrace57846CharString.txt)
It appears that the trace for the successful one is small enough to be sent in one transfer and the larger message has two. Any help would be much appreciated!

**Comment by xinchen10** [comment]
Looks like the broker cannot handle a continuous transfer without delivery-id/delivery-tag/message-format. Those are mandatory for the first transfer and may be omitted for the continuous transfers. As a workaround you can check if the broker supports a config for max-frame-size and set it large enough so messages are not fragmented.

**Comment by danlangford** [comment]
@xinchen10 Thanks for your input. I happen to be the engineer that manages the broker @kdparkinson is trying to send larger messages to.  Unfortunately I think the message size is undetermined enough that for us to move forward we would need to set it pretty large. Well that may work in the short term we don’t know at what point the setting may be insufficient.

 It sounds like you were saying the broker is requiring something that the specification says is optional. Is that correct? What do you think is the best way forward for a solution for us? Should we be working with the QPID project team to determine if there is a fix they could be providing ? Or do you think having this client send that information, maybe making it configurable, may be an appropriate option?

**Comment by xinchen10** [comment]
@danlangford I guess there might be a way to config the max-frame-size on broker but I don't know what it is. The frames traces in the ErrorTrace.txt look valid as far as the protocol is concerned. I suspect it is something in the broker that could not handle the last transfer frame. The best solution is to work with the QPID team to confirm if this is indeed an issue in the broker and, if yes, get it fixed. Meanwhile I can provide you a private package that sends these fields but I don't want to include it in the released package and make it configurable.

**Comment by xinchen10** [comment]
Please reopen the issue if you need anything from us.
