### ISSUE TITLE
I am getting 9 extra zeroes bytes when the source of a java application

### ISSUE THREAD

**Issue by zD1z** [Azure/amqpnetlite#233]
I developed a dot net application to consume MQ red hat messages, however all messages arriving from the Java application I am getting 9 extra zeroes bytes. Has anyone gone through and found a solution?

**Comment by xinchen10** [comment]
Do you have more details on which library was used to send the message, how the message was constructed (properties, body, etc)? Where are those extra bytes? Is it in the message body? Which API did you call to get the body? Do you have sample code for the receiver? Can you capture the raw bytes of a received message?
