### ISSUE TITLE
SASL EXTERNAL not working with Apache Qpid C++ broker

### ISSUE THREAD

**Issue by scholzj** [Azure/amqpnetlite#24]
The SASL EXTERNAL mechanism is currently not working against the Apache Qpid broker. The client sends the sasl-init without the initial response. That triggers the Qpid C++ broker to send sasl-challenge, to which the client never responds.

This can be fixed in two ways:
a) send the sasl-init with (empty) initial response (not sure what impact will this have e.g. on Azure Service Bus)
b) respond to sasl-challenge with sasl-response containing empty response

**Comment by xinchen10** [comment]
fixed in v1.1.2
