### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by zmhh** [Azure/amqpnetlite#241]
Hey @xinchen10,

The TCP Keep-Alive and AMQP Idle-Timeouts which were recently added to the library are big items for us, having experienced connectivity issues using previous versions of the library in less than ideal network conditions.  

Could we get a new release so we can get these improvements via NuGet? Any thoughts on a timeline?

Thanks!

**Comment by xinchen10** [comment]
@zmhh I uploaded 2.1.1 to NuGet but didn't make it listed in search results. You should be able to install it through package manager console. It would be great if you can try it out. I will make it listed once everything is working as expected. Thanks.

**Comment by zmhh** [comment]
Checking it out!

**Comment by zmhh** [comment]
Hey @xinchen10, all is looking good to me.  I've grabbed 2.1.1 from NuGet and done some basic testing, including the timeouts, and have not seen any issues.
