### ISSUE TITLE
Flow frame dropped by session after outgoing window closed blocks links from resuming message sending.

### ISSUE THREAD

**Issue by cjwmorgan-sol-sys** [Azure/amqpnetlite#242]
While testing my client against a broker which optimizes dispositions and flows in batches for batchable transfer frames, I found the most (all except one) flows were not being processed by the links. My Message broker sends a disposition (for multiple deliveries) immediately followed by flows for each link to update the link state with a small outgoing frame window for the session, for a group of transfers. Under certain conditions the most links in the session do not get their credit values recalculated to send their deliveries to the session.  This effectively locks the links credits at zero making the affected links unable to pass deliveries to the session to be processed when the next flow is processed. 

Here is the cause for the flow to be dropped by the session. First when the flows are sent for a group of transfers all of the fields used to calculate the session outgoing window on the client are identical. Second, when the session processes the first flow the outgoing window is set to some value greater then 0 the session writes out its pending outgoing deliveries decreasing or closing the outgoing window. When the window is closed the flow is dropped and not passed to the corresponding link to update the link state.

Here is the cause for the link never resuming to pass deliveries to the session. If the pending outgoing deliveries on a session are all from one link and the number of pending deliveries is enough to close (or mostly close) the session outgoing window. All the subsequent flows for the batch do not change the session's outgoing window and if the session's window is closed the link credits (link state) are not updated for the other links. 

In the code for the session `OnFlow` method (about line 527 in `Session.cs`) there is a check on the session outgoingWindow to return passing the flow onto the link if the window is zero. I find this odd as it would drop the link state update. I tried remove this check so the links always receive the flow to update there state and the problem went away. This check was committed in the initial commit to Session.cs and I don't really know the purpose for this check. Should the link state update be dropped if the session outgoing window is zero?

I can raise a pull request if the check should be removed.

I have a unit test for my project that recreate issue, see https://github.com/cjwmorgan-sol-sys/nms-amqp/blob/master/src/test/csharp/Test/TestCase/ConsumerTest.cs method `TestMultipleConsumerMessageListenerReceive`. Unfortunate the message broker I found issue on is not public yet. So, here are some details around what happens when the is run against the message broker. The test tries to send 400000 messages in a round robin on 4 different sender links (IMessageProducer are pretty much SenderLinks) where the broker sets the sessions outgoing window to no greater than 247. The link credits are also set to 247 initially and will exceed this value in a flow from the broker. Eventually only messages from one sender link end up getting sent to the broker and the rest are in the outgoing list of the other sender links.

**Comment by xinchen10** [comment]
@cjwmorgan-sol-sys you are right. The check for session window size should be removed.

**Comment by cjwmorgan-sol-sys** [comment]
@xinchen10 I'll make a pull request then.

**Comment by cjwmorgan-sol-sys** [comment]
@xinchen10 Nevermind I looked more closely at your commit. Thank you. Closing.
