### ISSUE TITLE
Properties of inherited classes are missing on receiver side

### ISSUE THREAD

**Issue by BenjaminAbt** [Azure/amqpnetlite#244]
**Scenario:**
We have a common base project for message contents, for example:

```cs
    public abstract class BaseQueueElement
    {
        [AmqpMember]
        public string Name {get;set;}
    }
```

Now for the implementation projects we use something like:

```cs
    [AmqpContract(Name = "PositionQueueElement", Encoding = EncodingType.SimpleMap)]
    public sealed class PositionQueueElement : BaseQueueElement
    {
        [AmqpMember]
        public int X { get; set; }

        [AmqpMember]
        public int Y { get; set; }

        [AmqpMember]
        public int Z { get; set; }
    }
```

Because we're using .NET Core we have to use the AmqpValue where TElement is `PositionQueueElement`
```cs
           AmqpValue<TElement> ser = new AmqpValue<TElement>(element);

            Message message = new Message { BodySection = ser };
            await _senderLink.SendAsync(message);
```
In the debugger we can see the serialization of `AmqpValue` and `Message` works fine.
![image](https://user-images.githubusercontent.com/6189336/33987103-fb5ad054-e0bf-11e7-9c3e-a1a21df659e8.png)

On the receiver side the Name property is missing.

![image](https://user-images.githubusercontent.com/6189336/33987144-1fea6c22-e0c0-11e7-8dca-abf6f8da65dd.png)
(the different values of X/Y/Z are just because I've debugged different messages).

Is this a serialization issue? Or by design?

**Comment by xinchen10** [comment]
This is not expected. I will look into it.

**Comment by BenjaminAbt** [comment]
ping me if you need more information or assistance.

**Comment by xinchen10** [comment]
@BenjaminAbt I just noticed that there is no AmqpContract attribute on the base class. Can you add it and try again? Without that the AmqpMember properties in base class are not included during serialization.

**Comment by BenjaminAbt** [comment]
You were right....
```cs
    [AmqpContract()]
    public abstract class BaseQueueElement
    {
        [AmqpMember]
        public string Name {get;set;}
    }
``` 
works like a charm!

Thought only on specific impl classes we need the contract attribute.
Also the `EncodingType` must be the same.

It is still confusing to me I can see the affected property as part of the sender raw message but not on the receiver raw message.

Thank you for your hint and help!

**Comment by BenjaminAbt** [comment]
@xinchen10 is there any possibility to use POCO classes without those attributes?
