### ISSUE TITLE
.Net Core 2.0 - TransactionScope Support?

### ISSUE THREAD

**Issue by toddbaert** [Azure/amqpnetlite#246]
Now that .NET Core 2.0 has been released (which features TransactionScope support), can we anticipate support for this capability on a future release for this platform?

Thanks!

**Comment by toddbaert** [comment]
@xinchen10 
I was considering a creating a PR for this, but wanted your input. Would this involve more than including the classes is the Amqp.Transactions namespace in the .Net Core build and updating the compiler directives around transaction-related to code to include Core?  From that point on, would only .Net Core 2.0 be supported in future releases of the Core distribution?

**Comment by xinchen10** [comment]
@toddbaert I'd like to support core 1.0 if possible. For 2.0, you are right that it may be just updating the compiler directives to include the txn code. Ideally we want one assembly that works on both 1.0 and 2.0, but if we cannot conditionally handle txn in code we may have to create separate assemblies for them.
