### ISSUE TITLE
Are there issues with the nuspec?

### ISSUE THREAD

**Issue by pshrosbree** [Azure/amqpnetlite#247]
When using Paket () as the NuGet client I get this:

```
Could not detect any platforms from '.netmicroframework0.0' in 'C:\src\paket-test\analytics-eventhubreader\packages\AMQPNetLite\AMQPNetLite.nuspec', please tell the package authors
Could not detect any platforms from 'netmf42' in 'C:\src\paket-test\analytics-eventhubreader\packages\AMQPNetLite\lib\netmf42\be\Amqp.NetMF.pdbx', please tell the package authors
Could not detect any platforms from 'netmf43' in 'C:\src\paket-test\analytics-eventhubreader\packages\AMQPNetLite\lib\netmf43\be\Amqp.NetMF.pdbx', please tell the package authors
Could not detect any platforms from 'netmf44' in 'C:\src\paket-test\analytics-eventhubreader\packages\AMQPNetLite\lib\netmf44\be\Amqp.NetMF.pdbx', please tell the package authors
```

Looking at the .NET [target frameworks](https://docs.microsoft.com/en-us/dotnet/standard/frameworks) I see that this complaint is justified, in that none of `.netmicroframework0.0`, `netmf42`, `netmf43` or `netmf44` are listed. In fact, a Web search AMQPNetLite is the prmeier source of these target frameworks.

Is this an error in the nuspec?

I am using AMQPNetLite 2.1.1.

**Comment by xinchen10** [comment]
It installs fine with the NuGet client.

According to this page,
https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks

The framework names under lib can be
```
lib\{framework name}[{version}]
```
{version} is optional and I guess the client may need to use the target framework version from the project in case of no exact match but I am not sure.

**Comment by pshrosbree** [comment]
It installs fine with paket as well, it is just that the framework names are not valid framework names.

Regards,
Peter Shrosbree
________________________________

**Comment by xinchen10** [comment]
According to this page https://fsprojects.github.io/Paket/dependencies-file.html netmf is not in the supported list by Paket.
