### ISSUE TITLE
Talking with TestAmqpBroker from Microsoft's Azure AMPQ

### ISSUE THREAD

**Issue by MatthewDavidCampbell** [Azure/amqpnetlite#249]
Using 2.1.1 of AMQPNetLite on Net Core 2.1.4 Windows....

Not well versed the AMQP protocol but thought I could run the TestAmqpBroker locally:

     .\TestAmqpBroker.exe amqp://127.0.0.1:5672 /trace:frame /queues:q1

And connect up using Microsoft's Azure AMPQ (version 2.3.1.) as follows:

     var transportSettings = new TcpTransportSettings() {
       Host = "127.0.0.1",
       Port = 5672
     };

     var settings = new Microsoft.Azure.Amqp.AmqpSettings();

     AmqpTransportProvider amqpProvider = new AmqpTransportProvider();
     amqpProvider.Versions.Add(new AmqpVersion(new Version(1, 0, 0, 0)));
     settings.TransportProviders.Add(amqpProvider);

     AmqpTransportInitiator initiator = new AmqpTransportInitiator(settings, transportSettings);
      TransportBase transport = await Task.Factory.FromAsync(
                (c, s) => initiator.BeginConnect(AmqpConstants.DefaultTimeout, c, s),
                (r) => initiator.EndConnect(r),
                null)
                .ConfigureAwait(false);

     AmqpConnectionSettings connectionSettings = new AmqpConnectionSettings()
     {
        ContainerId = Guid.NewGuid().ToString(),
        MaxFrameSize = 65536,
        HostName = "127.0.0.1"
     };

     AmqpConnection connection = new AmqpConnection(
       transport, 
       ProtocolHeader.Amqp100, 
       false, 
       settings, 
       connectionSettings
     );
     await connection.OpenAsync(AmqpConstants.DefaultTimeout).ConfigureAwait(false);

Fails on handling the max frame size from the test broker which is set to 65536 but the `AsyncIO` receives 1095586128.  Not sure where 1095586128 comes from. 

Seems like the test broker is sending data back to the AMPQ connection was isn't getting parsed right.  Wondering if bridging the test broker and Microsoft's framework is even viable?  Wondering if anybody else has tried?

**Comment by xinchen10** [comment]
Please check the answer here:
https://github.com/Azure/azure-amqp/issues/93
