### ISSUE TITLE
Race condition in AmqpObject.AddClosedCallback() causes the Close Callback not to be invoked

### ISSUE THREAD

**Issue by ramtinkermani** [Azure/amqpnetlite#258]
Following up on the resolution for issue #224, we started using the **AmqpObject's** **AddClosedCallback**() to add the closed callbacks after the object is created to make sure the closedCallback is called even if it's added after the object is closed. But we observed that we still miss the close event occasionally and the CloseCallback is not called. After investigating this I found out that in **AddClosedCallback** when we enter the lock, if the value of the **closedCalled field** is false (Object is not closed yet) we proceed to add the callback to the **Closed** event and we return (and not invoking the callback since we assume it will be called later). However, it is possible that right after we enter the **if** block (**if (!this.closedCalled)**) the object is closed and we will miss the callback event. I think this is where the problem is:

Even though a lock in **AmqpObject.CloseInternal()** protects **closedCalled field**, **Session.Abort()**, **Link.Abort()**, etc. can still set the property **CloseCalled** to true which in turn sets the **closedCalled field** to true and there are no locks preventing this from happening. I'm not sure but probably adding a lock in the setter of the **ClosedCalled property** to protect **closedCalled field** might help with the issue. 
This is my hypothesis and I'd appreciate it if you let me know if this is a problem or not and if you could add a fix for it.
Thanks a lot!

**Comment by xinchen10** [comment]
@ramtinkermani You analysis about the race condition is correct. The bug is that we should have checked closedNotified flag (not the closedCalled flag).

**Comment by ramtinkermani** [comment]
Ok, great! Thanks for the prompt response and the quick fix!
