### ISSUE TITLE
AMQP char type not supported

### ISSUE THREAD

**Issue by kpvdr** [Azure/amqpnetlite#259]
When encoding the AMQP char type, the message
```
System.ApplicationException: Sender can not encode base type: char
```
is raised.

**Comment by kpvdr** [comment]
This is an observation made while running the AMQP Types Test from [Qpid Interop Test](https://github.com/apache/qpid-interop-test) (`qpid_interop_test.amqp_types_test`) against an [ActiveMQ](https://github.com/apache/activemq) broker, which can handle AMQP char types. The AMQP Types Test includes AMQP.NetLite shims.

**Comment by xinchen10** [comment]
It is supported by the library. The tests need to be updated to include 'char' type.

**Comment by xinchen10** [comment]
https://issues.apache.org/jira/browse/QPIDIT-118
