### ISSUE TITLE
Avoid Transaction overhead in SenderLink.Send

### ISSUE THREAD

**Issue by szehetner** [Azure/amqpnetlite#266]
I need to send messages without waiting for an acknowledge, for this I'm using this SenderLink.Send overload:
https://github.com/Azure/amqpnetlite/blob/5fa4f9dcf682985dfa77654a0c2bd911dcb1400c/src/SenderLink.cs#L138

Profiling shows that the call to ResourceManager.GetTransactionalStateAsync takes about 17% of the send time, due to the async statemachine overhead and the call to Transaction.Current. I'm not using Transactions, so I would like to avoid this. Calling 
https://github.com/Azure/amqpnetlite/blob/5fa4f9dcf682985dfa77654a0c2bd911dcb1400c/src/SenderLink.cs#L147
directly with null as DeliveryState would solve this problem, but the method is internal. Could this be made public? Or maybe another public Send overload created? Or a way to say "do not use transactions" globally?

**Comment by xinchen10** [comment]
@szehetner we can make the method public. Just need to make it clear in the api doc that it is not transaction aware.
