### ISSUE TITLE
client cannot handle MessageId from uLong

### ISSUE THREAD

**Issue by kornys** [Azure/amqpnetlite#278]
https://github.com/Azure/amqpnetlite/blob/eddf2d3c512933fee83eef99b11284fcb356ea19/src/Framing/Properties.cs#L46

When message from another client is sent and messageId is set on ulong, amqp.net receiver raise exception
```
at Amqp.Framing.Properties.get_MessageId() in C:\Users\mqt\repo\amqpnetlite.rel\src\Framing\Properties.cs:line 46
Unable to cast object of type 'System.UInt64' to type 'System.String'.
```

**Comment by xinchen10** [comment]
For types other than string, use the Properties.Get/SetMessageId method to get or set the message ID value. This is mentioned in the xml doc of the Properties.MessageId property but it may not be easy to find.
```
        /// <remarks>
        /// The default message identifier type assumed by the library is string.
        /// If the application needs to process other types (ulong, uuid, or binary),
        /// it must use the Get/SetMessageId methods.
        /// </remarks>
```

**Comment by kornys** [comment]
@xinchen10 thanks!
