### ISSUE TITLE
Sustained async performance with task-per-message model

### ISSUE THREAD

**Issue by ChugR** [Azure/amqpnetlite#279]
In my github clone of this library please see [Async examples](https://github.com/ChugR/amqpnetlite/tree/async-drain-spout/Examples/Async).  The two projects are set up to run under dotnet. The Async.Drain example is best set up with performance stats to show the issue but both Drain and Spout suffer the same way.

Drain presupposes some broker with millions of messages on it. 
* Some number of instances of the Drain class are created. Each Drain.Run is started as a Task.
* Main then does a WaitAll for the Drains to finish.
* Within Drain.Run some number of workers are created and put into a free queue.
* A receiver is opened and receive callbacks put delivered messages into a message queue.
* Drain Run loops waiting for there to be at least one message and one free worker. Then the message is
removed from the message queue and associated with the worker, and the worker's Run function is started as a task.
* As worker tasks complete they pass the message back to the Drain class where the message is disposed and the worker is placed back into the free queue.
* When enough messages are processed or the wall clock timer expires all the workers are allowed to finish and each Drain then exits.

This seems like a straightforward way to use async TAP. However, when I run this code the messages processed per second rate dwindles. It starts out processing maybe 20+K/sec; after it minute it is down to 2K/sec; after 30 minutes it is down to 200/sec.

Before you get too alarmed I don't think this is an AMQP.Net Lite problem. I added a CLI switch --auto-receive that cuts the Lite library out of the picture. It does not set up a Connection, Session, or ReceiverLink although it does still create and dispose of Message objects. With this switch the performance numbers are virtually identical to running with Lite and a fast, local server. And the behavior is the same using dotnet on Linux Fedora 27 and on Windows Server 2012 R2.

I am wondering then what is a good way to structure a dotnet async program so that each message can be handed off to a worker and the whole process does not grind to a halt? I've tried starting thisDrain.Run() with TaskCreationOptions.LongRunning but that makes no measurable difference.

Thanks for any advice.
-Chuck

### Example Run

> dotnet run -- --address orders --broker amqp://127.0.0.1:5672 --count 1000000 --instances 2 
>    --test-duration 60  --credit-initial 100 --task-pool-size 50 
>    --task-delay-min-ms 0 --task-delay-max-ms 0 --stats-interval 2
>
> [07:25:41.948505] INFO Instance:0 msgsDone=38001;  time(S): 1.873, msg/S: 20,288.84
> [07:25:41.948555] INFO Instance:1 msgsDone=37954;  time(S): 1.873, msg/S: 20,263.75
> [07:25:43.947349] INFO Instance:0 msgsDone=21437;  time(S): 1.999, msg/S: 10,723.86
> [07:25:43.947378] INFO Instance:1 msgsDone=22631;  time(S): 1.999, msg/S: 11,321.16
> [07:25:45.947552] INFO Instance:0 msgsDone=16606;  time(S): 2.000, msg/S: 8,303.00
> [07:25:45.947589] INFO Instance:1 msgsDone=16628;  time(S): 2.000, msg/S: 8,314.00
> [07:25:47.947689] INFO Instance:0 msgsDone=12871;  time(S): 2.000, msg/S: 6,435.50
> [07:25:47.947730] INFO Instance:1 msgsDone=12818;  time(S): 2.001, msg/S: 6,405.80
> [07:25:49.947819] INFO Instance:0 msgsDone=10918;  time(S): 2.001, msg/S: 5,456.27
> [07:25:49.947860] INFO Instance:1 msgsDone=11191;  time(S): 2.000, msg/S: 5,595.50
> [07:25:51.947968] INFO Instance:0 msgsDone=9291;  time(S): 2.000, msg/S: 4,645.50
> [07:25:51.948006] INFO Instance:1 msgsDone=10115;  time(S): 2.000, msg/S: 5,057.50
> [07:25:53.947176] INFO Instance:0 msgsDone=8107;  time(S): 1.999, msg/S: 4,055.53
> [07:25:53.947219] INFO Instance:1 msgsDone=8694;  time(S): 1.999, msg/S: 4,349.17
> [07:25:55.947374] INFO Instance:0 msgsDone=7073;  time(S): 2.000, msg/S: 3,536.50
> [07:25:55.947426] INFO Instance:1 msgsDone=7461;  time(S): 2.000, msg/S: 3,730.50
> [07:25:57.947603] INFO Instance:0 msgsDone=5548;  time(S): 2.000, msg/S: 2,774.00
> [07:25:57.947653] INFO Instance:1 msgsDone=5755;  time(S): 2.000, msg/S: 2,877.50
> [07:25:59.947776] INFO Instance:0 msgsDone=4806;  time(S): 2.001, msg/S: 2,401.80
> [07:25:59.947818] INFO Instance:1 msgsDone=4715;  time(S): 2.001, msg/S: 2,356.32
> [07:26:01.947080] INFO Instance:0 msgsDone=4617;  time(S): 1.999, msg/S: 2,309.65
> [07:26:01.947137] INFO Instance:1 msgsDone=4578;  time(S): 1.999, msg/S: 2,290.15
> [07:26:03.947296] INFO Instance:0 msgsDone=4463;  time(S): 2.000, msg/S: 2,231.50
> [07:26:03.947340] INFO Instance:1 msgsDone=4293;  time(S): 2.000, msg/S: 2,146.50
> [07:26:05.947554] INFO Instance:0 msgsDone=4219;  time(S): 2.000, msg/S: 2,109.50
> [07:26:05.947621] INFO Instance:1 msgsDone=4123;  time(S): 2.000, msg/S: 2,061.50
> [07:26:07.947729] INFO Instance:0 msgsDone=3913;  time(S): 2.001, msg/S: 1,955.52
> [07:26:07.947771] INFO Instance:1 msgsDone=3872;  time(S): 2.001, msg/S: 1,935.03
> [07:26:09.948037] INFO Instance:0 msgsDone=3722;  time(S): 2.000, msg/S: 1,861.00
> [07:26:09.948094] INFO Instance:1 msgsDone=3778;  time(S): 2.000, msg/S: 1,889.00
> [07:26:11.947266] INFO Instance:0 msgsDone=3562;  time(S): 1.999, msg/S: 1,781.89
> [07:26:11.947319] INFO Instance:1 msgsDone=3633;  time(S): 1.999, msg/S: 1,817.41
> [07:26:13.947525] INFO Instance:0 msgsDone=3416;  time(S): 2.000, msg/S: 1,708.00
> [07:26:13.947577] INFO Instance:1 msgsDone=3436;  time(S): 2.000, msg/S: 1,718.00
> [07:26:15.947753] INFO Instance:0 msgsDone=3321;  time(S): 2.001, msg/S: 1,659.67
> [07:26:15.947829] INFO Instance:1 msgsDone=3395;  time(S): 2.001, msg/S: 1,696.65
> [07:26:17.948004] INFO Instance:0 msgsDone=3187;  time(S): 2.000, msg/S: 1,593.50
> [07:26:17.948074] INFO Instance:1 msgsDone=3286;  time(S): 2.000, msg/S: 1,643.00
> [07:26:19.947385] INFO Instance:0 msgsDone=3136;  time(S): 1.999, msg/S: 1,568.78
> [07:26:19.947441] INFO Instance:1 msgsDone=3142;  time(S): 1.999, msg/S: 1,571.79
> [07:26:21.947650] INFO Instance:0 msgsDone=2617;  time(S): 2.000, msg/S: 1,308.50
> [07:26:21.947703] INFO Instance:1 msgsDone=2928;  time(S): 2.001, msg/S: 1,463.27
> [07:26:23.947874] INFO Instance:0 msgsDone=2556;  time(S): 2.001, msg/S: 1,277.36
> [07:26:23.947928] INFO Instance:1 msgsDone=2798;  time(S): 2.000, msg/S: 1,399.00
> [07:26:25.948096] INFO Instance:0 msgsDone=2838;  time(S): 2.000, msg/S: 1,419.00
> [07:26:25.948160] INFO Instance:1 msgsDone=2858;  time(S): 2.000, msg/S: 1,429.00
> [07:26:27.947344] INFO Instance:0 msgsDone=2846;  time(S): 1.999, msg/S: 1,423.71
> [07:26:27.947397] INFO Instance:1 msgsDone=2865;  time(S): 1.999, msg/S: 1,433.22
> [07:26:29.947623] INFO Instance:0 msgsDone=2762;  time(S): 2.000, msg/S: 1,381.00
> [07:26:29.947692] INFO Instance:1 msgsDone=2829;  time(S): 2.001, msg/S: 1,413.79
> [07:26:31.947841] INFO Instance:0 msgsDone=2709;  time(S): 2.001, msg/S: 1,353.82
> [07:26:31.947884] INFO Instance:1 msgsDone=2741;  time(S): 2.000, msg/S: 1,370.50
> [07:26:33.948023] INFO Instance:0 msgsDone=2361;  time(S): 2.000, msg/S: 1,180.50
> [07:26:33.948074] INFO Instance:1 msgsDone=2437;  time(S): 2.000, msg/S: 1,218.50
> [07:26:35.947188] INFO Instance:0 msgsDone=2589;  time(S): 1.999, msg/S: 1,295.15
> [07:26:35.947241] INFO Instance:1 msgsDone=2625;  time(S): 1.999, msg/S: 1,313.16
> [07:26:37.947447] INFO Instance:0 msgsDone=2537;  time(S): 2.000, msg/S: 1,268.50
> [07:26:37.947500] INFO Instance:1 msgsDone=2553;  time(S): 2.000, msg/S: 1,276.50

**Comment by billpoole-mi** [comment]
We're creating a task for each received message and we're not seeing any performance degradation over time. We're using a SemaphoreSlim to throttle the number of tasks that can be created in parallel. Not sure if that could help?

**Comment by ChugR** [comment]
Thanks for the check. A goal is to keep up 2000 or 3000 messages per second indefinitely. In the first two seconds this example consumes 80,000 messages so that's great. The problem is keeping it up past the million message mark.

The solution uses a limited number of message worker objects instead of SemaphoreSlim. The workers are allocated once and kept for the duration of the test. Messages that arrive before there is a worker/task to consume them are just queued.

**Comment by billpoole-mi** [comment]
I assume where you say "As worker tasks complete they pass the message back to the Drain class where the message is disposed and the task is placed back into the free queue", it should be the worker is placed back into the free queue (not the task)?

Perhaps there is some memory fragmentation happening and the slowdown is the GC? Are you using buffer pooling for the received messages?

**Comment by billpoole-mi** [comment]
Just checking whether or not this is still an issue. I created a test (below), which I ran for 10 minutes with no noticeable slowdown. If you're still having the issue, maybe see if you get the problem with the test below?

``` csharp
static async Task TestSustainedThroughput(int meanMessageSize)
{
	// Generate 1000 random messages to be sent over and over
	var rng = new Random();
	var randomMessages = new List<Message>();
	for (var i = 0; i < 1000; i++)
	{
		var bytes = new byte[rng.Next(meanMessageSize)];
		rng.NextBytes(bytes);
		randomMessages.Add(new Message
		{
			Header = new Amqp.Framing.Header { Durable = true },
			BodySection = new Amqp.Framing.Data()
			{
				Buffer = new ByteBuffer(bytes, 0, bytes.Length, bytes.Length)
			}
		});
	}

	var isComplete = false;
	var connectionFactory = new ConnectionFactory
	{
		BufferManager = new BufferManager(64, 128 * 1024, 100 * 1024 * 1024)
	};

	var connection = await connectionFactory.CreateAsync(
		new Address("amqp://artemis:simetraehcapa@localhost"))
		.ConfigureAwait(false);
	var session = new Session(connection);
	var receiverLinks = new List<ReceiverLink>();
	Console.CancelKeyPress += (sender, e) =>
	{
		e.Cancel = true;
		Task.Run(CancelTest);
	};

	var sentMessageCount = 0;
	var receivedMessageCount = 0;
	var bytesReceived = 0L;

	async Task ReceiveMessages(string queueName)
	{
		var receiveThrottler = new SemaphoreSlim(50, 50);
		var receiverLink = new ReceiverLink(session, $"receiver-link-{queueName}", queueName);
		receiverLinks.Add(receiverLink);
		receiverLink.SetCredit(credit: 1000, autoRestore: true);
		var receiveTaskList = new ConcurrentDictionary<Task, bool>();
		while (!isComplete)
		{
			//Console.WriteLine("Waiting to receive");
			var message = await receiverLink.ReceiveAsync().ConfigureAwait(false);
			//Console.WriteLine("Received message");
			if (message != null)
			{
				using (message)
				{
					await receiveThrottler.WaitAsync().ConfigureAwait(false);
					receiveTaskList.TryAdd(Task.Run(async () =>
					{
						try
						{
							if (isComplete)
							{
								return;
							}

							receiverLink.Accept(message);
							Interlocked.Increment(ref receivedMessageCount);
							Interlocked.Add(ref bytesReceived, message.GetBody<ByteBuffer>().Length);
						}
						catch (Exception ex)
						{
							Console.WriteLine(ex);
							await CancelTest().ConfigureAwait(false);
						}
						finally
						{
							receiveThrottler.Release();
						}
					}).ContinueWith(task => receiveTaskList.TryRemove(task, out _)), false);
				}
			}
		}

		await Task.WhenAll(receiveTaskList.Keys).ConfigureAwait(false);
	}

	async Task SendMessages(string queueName)
	{
		var sendThrottler = new SemaphoreSlim(25, 25);
		var senderLink = new SenderLink(session, $"sender-link-{queueName}", queueName);
		var sendTaskList = new ConcurrentDictionary<Task, bool>();
		while (!isComplete)
		{
			await sendThrottler.WaitAsync().ConfigureAwait(false);
			sendTaskList.TryAdd(Task.Run(async () =>
			{
				try
				{
					await senderLink.SendAsync(randomMessages[sentMessageCount % randomMessages.Count])
						.ConfigureAwait(false);
					Interlocked.Increment(ref sentMessageCount);
				}
				catch (Exception ex)
				{
					Console.WriteLine(ex);
					await CancelTest().ConfigureAwait(false);
				}
				finally
				{
					sendThrottler.Release();
				}
			}).ContinueWith(task => sendTaskList.TryRemove(task, out _)), false);
		}

		await Task.WhenAll(sendTaskList.Keys).ConfigureAwait(false);
		await senderLink.CloseAsync().ConfigureAwait(false);
	}

	async Task MonitorPerformance()
	{
		var i = 0;
		var lastBytesReceived = 0L;
		var lastReceivedMessageCount = 0;
		while (!isComplete)
		{
			var temp1 = bytesReceived;
			var bytesPerSecond = temp1 - lastBytesReceived;
			lastBytesReceived = temp1;
			var temp2 = receivedMessageCount;
			var messagesPerSecond = temp2 - lastReceivedMessageCount;
			lastReceivedMessageCount = temp2;
			Console.WriteLine($"{++i}: {bytesPerSecond/1024f/1024:f2} MBytes/s and {messagesPerSecond} messages/s");
			await Task.Delay(TimeSpan.FromSeconds(1)).ConfigureAwait(false);
		}
	}

	async Task CancelTest()
	{
		Console.WriteLine("Cancelling test...");
		isComplete = true;
		await Task.WhenAll(receiverLinks.Select(receiverLink => receiverLink.CloseAsync()))
			.ConfigureAwait(false);
	}

	await Task.WhenAll(
		ReceiveMessages("q1"),
		ReceiveMessages("q2"), 
		SendMessages("q1"),
		SendMessages("q2"),
		Task.Delay(TimeSpan.FromSeconds(1))
			.ContinueWith(task => Task.Run(() => MonitorPerformance())))
		.ConfigureAwait(false);

	await session.CloseAsync().ConfigureAwait(false);
	await connection.CloseAsync().ConfigureAwait(false);
}
```

**Comment by xinchen10** [comment]
Close old issues.
