### ISSUE TITLE
Receiving messages from IBM MQ

### ISSUE THREAD

**Issue by Scythril** [Azure/amqpnetlite#284]
Hi,

I'm attempting to use this library following the documentation found here as well as the examples listed in https://developer.ibm.com/messaging/2017/11/13/mq-light-messaging-microsoft-net-part-1/

This is my first foray into using IBM MQ, having used RabbitMQ (although with AMQP 0.9) quite a bit in the past.

So far, I can connect, and I can send messages no problem. When setting up a consumer, though, it seems to be hit or miss. What I've noticed is that the RECV comes through, but when it attempts to send back the accepted message, I get `error(condition:amqp:connection:forced,description:Cannot access a disposed object.
Object name: 'TcpTransport'.)`

I have very basic settings currently, username/password, using AMQP (not S at the moment), address is using an MQ share, TTL policy, setting a custom container id, and the following Source on the ReceiverLink:
```
            var source = new Source
            {
                Address = "share:share1:topic1",
                ExpiryPolicy = new Symbol("link-detach"),
                Timeout = MessageTtl,
                Durable = 0,
                Dynamic = false
            };
```

Connection code:
```
            var factory = new ConnectionFactory();
            factory.AMQP.ContainerId = ContainerId;
            var connectionTask = factory.CreateAsync(new Address(ServerConnectionString));
            Task.WaitAll(connectionTask);
            Connection = connectionTask.Result;
            Connection.Closed += ConnectionClosed;
            Session = new Session(Connection);
            Session.Closed += SessionClosed;
```

And receiver code:
```
                receiver.Start(PrefetchValue, (link, message) =>
                {
                    Console.WriteLine("Received AMQP message.");
                    Console.WriteLine(message.Body.ToString());
                    link.Accept(message);
                });
```

One thing I've noticed is that if I send a bunch of messages before subscribing the receiver, it will print all/most of those messages, but when I send a message while it's sitting idle, I get the connection-forced error.

Another note is that I can connect to this broker using the Node.js mqlight library, and have NO problems receiving any number of messages I've thrown at it. I've compared the frame traces between this library and that one as well, and other than a few minor differences in int values, they're pretty much the same.

Most of my Googling has pointed to problems with SSL, but I'm not using SSL, and I'm able to do the initial connection just fine.

Does anyone have any pointers on what could be going on here?

**Comment by xinchen10** [comment]
@Scythril can you post the complete receiver code? What else do you have after receiver.Start(...)? The start method is non-blocking. If you close any of the receiver/session/connection objects, the accept call will fail.

**Comment by xinchen10** [comment]
I don't have MQ to test against. I tried MQ Light. Sender is working but receiver could not get any messages back. Same thing happens even with their node.js example. Do you still have the frame traces from your node.js testing? Can you share it?

**Comment by xinchen10** [comment]
I got the following code working against MQ Light. Tried it several times and it worked just fine (this is on Windows 10 with regular .Net framework).
```
        public async Task BasicSendReceiveAsync()
        {
            int nMsgs = 10000;

            ConnectionFactory factory = new ConnectionFactory();
            factory.AMQP.ContainerId = "localhost";
            factory.SASL.Profile = SaslProfile.Anonymous;
            Connection connection = await factory.CreateAsync(new Address("amqp://localhost:5672"));
            var t1 = Task.Run(async () =>
            {
                await Task.Delay(5000);
                Session session = new Session(connection);
                SenderLink sender = new SenderLink(session, "public_1234", "public");
                for (int i = 0; i < nMsgs; ++i)
                {
                    Message message = new Message("hello");
                    message.Properties = new Properties() { MessageId = "msg" + i };
                    message.Properties.To = "public";
                    await sender.SendAsync(message);
                    await Task.Delay(20);
                }
            });

            var t2 = Task.Run(async () =>
            {
                Session session = new Session(connection);
                ReceiverLink receiver = new ReceiverLink(session, "share:share1:public", "share:share1:public");
                for (int i = 0; i < nMsgs;)
                {
                    Message message = await receiver.ReceiveAsync();
                    if (message != null)
                    {
                        Trace.WriteLine(TraceLevel.Information, "receive: {0}:{1}", message.Properties.MessageId, message.Body);
                        receiver.Accept(message);
                        i++;
                    }
                }
            });

            await Task.WhenAll(t1, t2);

            await connection.CloseAsync();
        }
```

**Comment by Scythril** [comment]
Hi @xinchen10 ,

This works for me as well. My problem arises when a new sender or receiver connects, it seems to very often (but not 100%) disconnect other connections, but not with the mqlight library.

I don't see any of this on RabbitMQ with the AMQP 1.0 plugin, so I'm thinking it's either something specific to IBM MQ's implementation of the protocol, or some setting on our server. I'll dig into this further on that side.

Thanks for looking into it! I really like how simple and straight-forward this library is.

**Comment by Scythril** [comment]
I've found the IBM MQ AMQP logs on the server, and I'm seeing this:

> 7/19/18 14:20:51.396  AMQXR0021W: Client 'public_1234' at network address 'xx.xx.xx.xxx' disconnected abnormally 
with exception 'AMQCO1007E: Connection 'xx.xx.xx.xxx' for client 'public_1234' did not send or receive data for '0' milliseconds and has been closed. '.

This led to me looking into the idle-timeout parameter, but when I set that and force a timeout by waiting longer, I get a different message, and the connection shuts down gracefully, so even though the error message seems to imply an idle timeout (though I'm not sure how you can disconnect after 0 milliseconds...), that doesn't seem to be the same issue.

At this point I'm at a loss as to what else could be causing this, but I'm working around it by setting handlers on the session and connection close events, and re-establishing the link to those new connections when catching the AmqpException. I believe this is something we'd have to implement anyway since the connection could be lost for any number of reasons. These frequent disconnects aren't ideal, but at least we can deal with them now.

Thanks again for the help!
