### ISSUE TITLE
ReceiverLink to receive messages concurrently via callback

### ISSUE THREAD

**Issue by dbeavon** [Azure/amqpnetlite#285]
I'm a bit new to the AMQP protocol.  I spent some time investigating the ReceiverLink's callback feature and I just wanted to verify my findings.  The Start() method allows you to specify a callback delegate but there is no simple way to get it to run the callback in parallel (from multiple threads at the same time).  

Even after creating multiple ReceiverLinks I wasn't able to get messages to be received in parallel.  It appears that the Pump() used to to call my delegate is all the way down in the Connection class so I would have to create multiple connections before my delegate would be executed concurrently.

The reason I ask is because the work that needs to be done for each message is a very long-running operation (1 second).  I was hoping that there would be some built-in way to perform the work concurrently by receiving multiple messages at once, and then accept each of them after the pending operation is completed.  I need to be processing at least 10 messages per second.

I suppose I will have to write my own code to receive messages in parallel.  I think this will mean creating  a TPL Task and awaiting ReceiveAsync() instead of supplying a callback on ReceiverLink.Start().  Please let me know if I'm on the right track.  If so I'll start looking at examples of ReceiverLink that use ReceiveAsync instead of specifying my callback on the Start() method.

**Comment by xinchen10** [comment]
Your callback can be async. Just make sure all exceptions are handled so it won't crash the process. If you start the link with 20 credit, there will be up to 20 worker tasks executing in parallel.
```
            receiver.Start(20, async (link, message) =>
            {
                Exception result = null;
                try
                {
                    await ProcessMessageAsync(message);
                }
                catch (Exception e)
                {
                    result = e;
                }

                try
                {
                    if (result == null)
                    {
                        link.Accept(message);
                    }
                    else
                    {
                        link.Reject(message);
                    }
                }
                catch { }
            });
```

**Comment by xinchen10** [comment]
The sample code was just to show the idea of starting a task from the callback and do not blocking on it. You can change it to follow the "best practices" of using task.
```
        receiver.Start(20, (link, msg) =>
        {
            // fire and forget
            var t = ProcessMessageAsync(link, msg);
        });

        async Task ProcessMessageAsync(IReceiverLink receiver, Message message)
        {
            await Task.Delay(1000);
            try
            {
                receiver.Accept(message);
            }
            catch (Exception exception)
            {
                // exception handling
                // receiver closed. reconnect if necessary.
            }
        }
```

The Accept/Reject methods are thread safe. Link endpoint state is protected with a lock when it is updated as a result of these calls.

**Comment by dbeavon** [comment]
Looks good.  Thanks again for your time.  I love this async stuff.  In a windows service I don't think there will be any synchronization context (by default) so I am on the hunt for something (eg from nuget) that will act as a message-pump for any future "awaits" where I'll need synchronization. 

I suspect at some point it might be a problem that all these async tasks never synchronize with each other.  In the very least they could synchronize after the long-running operation has been performed, but before the final Accept(message).
