### ISSUE TITLE
Using AMQPNetLite to subscribe to queues within ASP.Net application

### ISSUE THREAD

**Issue by koosala** [Azure/amqpnetlite#289]
This is more a question than an issue.

Our application is structured as a collection of IIS hosted Web API sites. The request comes in from the client application and it is routed between the Web API sites as synchronous REST calls. For e.g. a create order request is received by Ordering Web API, which creates an order and then calls Billing Web API via REST to create an invoice and Inventory Web API to reserve inventory. 

A more resilient design is for Ordering Web API to "publish" the order created event using Amqpnetlite to a Red Hat AMQ message broker (they recommend AMQPNetLite for .Net clients), have the Billing and Inventory web APIs subscribe to this event by using receiverlink to listen for events. 

My question is related to having WebAPI consumers connect to the AMQ broker to listen for messages using the AMQP protocol, which I understand establishes a TCP connection. This seems to work ok and we will need to define the application recycle, idle timeouts to work for us.  The benefit of doing this in Web API is we don't need a web and a windows service instance of each component e.g. billing. 

That said, I don't think threadpool plays into the background processing with AMQPNetLite. So, is having AMQP listeners this way in an ASP.Net application a workable design?

**Comment by xinchen10** [comment]
As long as the listener is running it should be able to pick up a message from the queue when it arrives. The question is how you keep the listener running. Maybe you keep it running all the time or activate the ASP.Net application when a message is available. I don't know the details though.
