### ISSUE TITLE
Synchronous sender link Close after async SendAsync causes thread deadlock

### ISSUE THREAD

**Issue by billpoole-mi** [Azure/amqpnetlite#290]
Invoking SenderLink.Close after SenderLink.SendAsync causes a thread deadlock, resulting in the Close method throwing a TimeoutException after 60s. For example:

```
var connectionFactory = new ConnectionFactory();
var connection = await connectionFactory.CreateAsync(new Address("amqp://guest:guest@localhost")).ConfigureAwait(false);
var session = new Session(connection);
var senderLink = new SenderLink(session, "sender-link", "q1");

await senderLink.SendAsync(new Message("Test message")).ConfigureAwait(false);
senderLink.Close(); // This line deadlocks
```

However, if senderLink.Send is used (instead of SendAsync) prior to senderLink.Close or senderLink.CloseAsync is used (instead of Close) after senderLink.SendAsync, then no deadlock occurs.

Likewise, if the task returned from SenderLink.CloseAsync() is awaited using the Task.Wait() method, the same deadlock occurs:

```
await senderLink.SendAsync(new Message("Test message")).ConfigureAwait(false);
senderLink.CloseAsync().Wait(); // This line deadlocks
```

This problem is seen in v2.1.3.

**Comment by xinchen10** [comment]
This is expected behavior when mixing sync and async API calls.
#237 Mix of Async and Sync methods may result in deadlocks
[building application - threading](https://github.com/Azure/amqpnetlite/blob/master/docs/articles/building_application.md#threading)

**Comment by billpoole-mi** [comment]
Thanks. I'd thought I'd read that somewhere before, but couldn't remember where. So, given that's the case, what is the appropriate way to invoke async API calls from within non-async methods, where we have no async alternatives to those async methods?

For example, how do we close Amqp.Net Lite objects (AmqpObjects) within the Dispose method of IDisposable?

Also, Amqp.Net Lite only provides a synchronous Closed event. Perhaps Amqp.Net Lite should provide an AsyncClosed alternative, and corresponding AddAsyncClosedCallback method?

The reality that we have to deal with as developers is that we're not always in control of whether the method in which we need to invoke the Amqp.Net Lite API is async or not.

Any guidance/recommendations as to how to invoke the Amqp.Net Lite API in these circumstances would be very much appreciated.
