### ISSUE TITLE
Amqp.Net from nuget AMQPNetLite.Core cannot be loaded properly in application targeted to .net461

### ISSUE THREAD

**Issue by slanto** [Azure/amqpnetlite#291]
AMQPNetLite.Core is compatible with netstandard 1.3, so it should be used in application for net461 as well as for core 2.0 successfully. 
In one of our project, where the nuget package is used, we encountered a 
problem with loading Amqp.net assembly in .net461 application

This problem concerns azure functions with running version: 1.0.11913.0 described in the ticket https://github.com/Azure/Azure-Functions/issues/904

In a nutshell, our custom library (netstandard.2.0) references to nuget AMQPNetLite.Core 2.1.3, is used in azure function running on .net461. 
It turnes out that Amqp.net dll cannot be found and loaded properly even if suitable dll is present in bin folder on azure. 

Could you please verify this case and confirm that AMQPNetLite.Core 2.1.3 is compatible with .net461 and should be loaded properly? 
Do you have any idea how to fix this problem?

**Comment by xinchen10** [comment]
Same issue as #292
