### ISSUE TITLE
Failed to verify assembly -- Strong name validation failed.

### ISSUE THREAD

**Issue by slanto** [Azure/amqpnetlite#292]
Hello,
When I try to manually verify Amqp.Net.dll, I get an error:
```
C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools>sn -v "C:\Users\user\azure-functions-amqp-problem\FunctionApp1\bin\Debug\net461\bin\Amqp.Net.dll"

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Failed to verify assembly -- Strong name validation failed.
```

It seems like Amqp.Net.dll has a potential problem with assembly identity. Probably because of this there is an issue in loading assembly in azure function. For more details please refer to https://github.com/Azure/Azure-Functions/issues/904

Can you please double check it to verify the issue?

**Comment by marcin-chwedczuk-meow** [comment]
It was not specified in original issue but problem occurs for e.g. AMQPNetLite.Core nuget package 2.1.3 on .NET Core 2.0 runtime.
