### ISSUE TITLE
Retrieving header and properties from IBM MQ message 

### ISSUE THREAD

**Issue by cobyros** [Azure/amqpnetlite#296]
Hi,
Our legacy component publishes messages to IBM MQ (using offical IBM MQ client) with 5 additional custom properties in header.
My .net core application (using amqpnetlite) is listening via receiver link to IBM MQ topic,
On callback it gets messages body properly, but couldn't resolve the additional header properties.
How can i overcome it?
10x

**Comment by ChugR** [comment]
AMQP Header does not support custom properties. Maybe application properties is what you mean.

I can create a message with a header property and varying application properties:

    public async static Task MessageSender(SenderLink sender, Message msg)
    {
        msg.Header = new Amqp.Framing.Header();
        msg.Header.Durable = true;
        msg.ApplicationProperties = new Amqp.Framing.ApplicationProperties();
        msg.ApplicationProperties["this"] = "that";
        msg.ApplicationProperties["timebell"] = 5;
        await sender.SendAsync(msg);
    }

Then when the messages is received the properties are accessed through:

    if (message.Header != null)                
        Console.WriteLine("header:{0}", message.Header.ToString());
    if (message.ApplicationProperties != null) 
        Console.WriteLine("applicationProperties:{0}", message.ApplicationProperties.Map.ToString());

When the code runs the console prints:

    header:header(durable:True)
    applicationProperties:[this:that,timebell:5]

**Comment by cobyros** [comment]
Thanks for your response.
Can you describe how should I populate application properties when message writer is using IBM MQ client library?

**Comment by ChugR** [comment]
Sorry, don't have a clue about that library. I'd start looking in an IBM MQ client library API reference.
