### ISSUE TITLE
More SASL mechanisms

### ISSUE THREAD

**Issue by orthoxerox** [Azure/amqpnetlite#299]
Right now the library supports only PLAIN authentication. I've added CRAM-MD5 in [my fork](https://github.com/Azure/amqpnetlite/compare/master...orthoxerox:master), but it feels wrong specifying the mechanism explicitly. If I provide some credentials, the library should automatically pick one of the server-accepted mechanisms compatible with the credentials given.

I would write a PR for that, but this requires decoupling SASL negotiation from the underlying mechanisms. I am not willing to rearrange the internal logic unless I get a blessing from the core maintainers.

**Comment by xinchen10** [comment]
We can achieve the same by making mechanism matching extensible in SaslProfile.cs.
```
protected virtual bool Match(Symbol mechanism)
{
    return mechanism.Equal(this.Mechanism);
}

internal bool OnFrame(...)
{
    foreach (var m in mechanisms.SaslServerMechanisms)
    {
        if (this.Match(m))
        {
            matched = m;
            break;
        }
    }
}
```
Now you can implement a profile for either PLAIN or CRAM-MD5 using the same credential.

**Comment by orthoxerox** [comment]
@xinchen10 Except various SASL responses I need to return from the overridden methods aren't public, so I cannot implement an external profile at all.

**Comment by xinchen10** [comment]
Which methods do you need access to? For SASL negotiation the profile implementation is responsible for challenge/response handling while the library takes care of I/O and framing.

**Comment by xinchen10** [comment]
You are right. They need to be public.
