### ISSUE TITLE
Best practices for creating "heavy" and singleton objects

### ISSUE THREAD

**Issue by ricardozanini** [Azure/amqpnetlite#302]
Hi!
Is there any documentation about how to reuse "heavy" objects, like [Connection](http://azure.github.io/amqpnetlite/api/Amqp.Connection.html)?

For example, one could add a cache of connections and/or sessions to keep sending messages in a short time frame. This would be very useful in use cases with a lot of producers. In Java, we have [PooledJMS](https://github.com/messaginghub/pooled-jms) that could be used with [Qpid-jms (AMQP)](https://qpid.apache.org/components/jms/index.html) library to pool producers and reusing them during the message sending/receiving lifecycle.

If there isn't a feature request for this, I'd like to hear from you how I can handle use cases like this. Is there any best practices? I came from Java, so I may missing something.

Thanks!

**Comment by xinchen10** [comment]
When you have many messages to send or receive, it is recommended to reuse the sender/receiver link object. As for caching there are different options. You could simply keep the link object as a member of your producer or consumer class, or create a pool of them by destination. I am not sure how much you will get from the pooling approach unless the app is network bound (you need more connections). A single link/connection should give you reasonable throughput when you do asynchronous/parallel send operations.

**Comment by ricardozanini** [comment]
Thanks for the insight @xinchen10! I'll run some tests in my local lab.
