### ISSUE TITLE
Session deadlocks while opening a link while another link on the same session is closing

### ISSUE THREAD

**Issue by billpoole-mi** [Azure/amqpnetlite#303]
The Session object deadlocks while opening a link on that session while another link on that session is in the process of closing.  The code to reproduce the problem is below.

	static async Task TestParallelOpenCloseLink()
	{
		var connectionFactory = new ConnectionFactory();
		var connection = await connectionFactory.CreateAsync(
			new Address("amqp://artemis:simetraehcapa@localhost"))
			.ConfigureAwait(false);
		var session = new Session(connection);

		async Task RunLoop(int senderNo)
		{
			for (var j = 0; j < 100; j++)
			{
				Console.WriteLine($"Opening link {senderNo}.{j}.");
				var senderLink = new SenderLink(session, $"link{senderNo % 2}", 
					$"q{senderNo % 2}");
				await senderLink.CloseAsync().ConfigureAwait(false);
				Console.WriteLine($"Link {senderNo}.{j} closed.");
			}
		}

		var tasks = new List<Task>
		{
			RunLoop(1),
			RunLoop(2)
		};

		await Task.WhenAll(tasks).ConfigureAwait(false);
		await session.CloseAsync().ConfigureAwait(false);
		await connection.CloseAsync().ConfigureAwait(false);
	}

**Comment by xinchen10** [comment]
Which broker did you use and what platform for the client? I was not able to reproduce the issue with my local broker. I added a unit test (ConcurrentLinkCreateClose in TaskTests.cs) and could run it many times without failure.

**Comment by billpoole-mi** [comment]
I'm running Apache Artemis v2.6.2 and a .NET Core 2.1 client using the 2.1.400 SDK on Windows 10. The deadlock occurs every time when I run the code I posted above in this environment.

**Comment by billpoole-mi** [comment]
Did you test it on v2.1.3 or the master? I've only tested the above code on v2.1.3. Is it possible that the issue has already been resolved on the master?

**Comment by billpoole-mi** [comment]
I just ran the code I posted on the master and the issue remains.

**Comment by xinchen10** [comment]
I ran the exact same code as a netcoreapp2.1 app on v2.1.3 against a local ActiveMQ 5.15.0 broker on Windows 10. No deadlock.

Is it possible for you to capture a process dump when it happens?

**Comment by billpoole-mi** [comment]
I tried right-clicking the process in Task Manager and selecting "Create dump file" but the menu option is disabled. The menu option is enabled for some applications and not for others and I can't figure out why. Any idea what I'm doing wrong?

**Comment by billpoole-mi** [comment]
Maybe in your setup you're not getting enough parallel open/close sender link operations? Maybe try the below instead. It runs 64 parallel loops opening/closing links to two queues "q1" and "q2".

```csharp
static async Task TestParallelOpenCloseLink()
{
	var connectionFactory = new ConnectionFactory();
	var connection = await connectionFactory.CreateAsync(
		new Address("amqp://artemis:simetraehcapa@localhost"))
		.ConfigureAwait(false);
	var session = new Session(connection);

	async Task RunLoop(int loopNumber)
	{
		for (var j = 0; j < 1000; j++)
		{
			var queueNumber = loopNumber % 2 + 1;
			var queueName = $"q{queueNumber}";
			var linkName = $"link-{loopNumber}";
			SenderLink senderLink;
			using (var cts = new CancellationTokenSource(TimeSpan.FromSeconds(2)))
			{
				cts.Token.Register(() => Console.WriteLine(
					$"Timed out on opening link {linkName} to queue {queueName}"));
				senderLink = new SenderLink(session, linkName, queueName);
			}

			using (var cts = new CancellationTokenSource(TimeSpan.FromSeconds(2)))
			{
				cts.Token.Register(() => Console.WriteLine(
					$"Timed out on closing link {linkName} to queue {queueName}"));
				await senderLink.CloseAsync().ConfigureAwait(false);
			}
		}
	}

	Console.WriteLine("Starting test.");
	var tasks = new List<Task>();
	for (var i = 0; i < 64; i++)
	{
		tasks.Add(RunLoop(i));
	}
			
	await Task.WhenAll(tasks).ConfigureAwait(false);
	Console.WriteLine("Completed successfully with no deadlock.");

	await session.CloseAsync().ConfigureAwait(false);
	await connection.CloseAsync().ConfigureAwait(false);
}
```

**Comment by billpoole-mi** [comment]
You can download the dump file from here - https://drive.google.com/file/d/15S5GAL9UBx_aU3NUWipQJaExiZfiYDPv/view?usp=sharing.

**Comment by xinchen10** [comment]
@billpoole-mi There is no deadlock in the dump. The close task is not completing. The task should time out after 60 seconds. Do you see TimeoutException from the CloseAsync call eventually? It could happen if the broker does not respond to the link close call appropriately.
