### ISSUE TITLE
Session (2nd) constructor does not use all of the Begin properties.

### ISSUE THREAD

**Issue by spankr** [Azure/amqpnetlite#305]
I'm looking at the [Session constructor](https://github.com/Azure/amqpnetlite/blob/782373decd9472514863823a84619e937fca4bc8/src/Session.cs#L83) on line 77-94 and I notice that the ```incomingWindow``` and ```outgoingWindow``` member variables don't look right.

```
            this.incomingWindow = defaultWindowSize;
            this.outgoingWindow = begin.IncomingWindow;
``` 

I looked at how the [Default()](https://github.com/Azure/amqpnetlite/blob/782373decd9472514863823a84619e937fca4bc8/src/Session.cs#L449) inner method works and it returns

```
            return new Begin()
            {
                IncomingWindow = defaultWindowSize,
                OutgoingWindow = defaultWindowSize,
                HandleMax = (uint)(connection.MaxLinksPerSession - 1),
                NextOutgoingId = uint.MaxValue - 2u
            };
```

This doesn't break "default" behavior because everything is ```defaultWindowSize```, which is a constant. Should this be changed to use the matching **Begin** properties?

e.g.

```
            this.incomingWindow = begin.IncomingWindow;
            this.outgoingWindow = begin.OutgoingWindow;
```

**Comment by xinchen10** [comment]
@spankr yes you are right. We should initialize the window sizes from the begin parameter.
