### ISSUE TITLE
Use Amqp.Listener.ContainerHost.RegisterMessageProcessor without specifying address

### ISSUE THREAD

**Issue by rkubis** [Azure/amqpnetlite#307]
It is not possible to register _RegisterMessageProcessor_ on _Amqp.Listener.ContainerHost_ without specifying address to listen on.

But all [Qpid Proton](https://qpid.apache.org/proton/index.html) clients are able to listen without specifying address, they are receiving all messages on **host:port** only.

It should be nice to have _RegisterMessageProcessor(IMessageProcessor)_ method.

**Comment by xinchen10** [comment]
Which one is better, having a new register method without address parameter or keeping the existing API but doing regex matching on the address?

**Comment by rkubis** [comment]
It could accept `null` (or another empty value) as address parameter to keep existing API, _RegisterMessageProcessor(null, IMessageProcessor)_.

**Comment by jdanekrh** [comment]
I don't like magic value of `null` much. Regex has the advantage that using that, one may implement the wildcards feature that brokers have, e.g. https://activemq.apache.org/artemis/docs/latest/wildcard-syntax.html and https://qpid.apache.org/releases/qpid-java-6.0.8/jms-client-0-8/book/JMS-Client-0-8-Binding-URL.html#JMS-Client-0-8-Binding-URL-Topics-Wildcards

@ChugR wdyt?

**Comment by xinchen10** [comment]
The following code (untested) can achieve the same goal before we have support for the new API.
```
static class ContainerHostExtensions
{
    static AnyLinkProcessor any;

    public static void RegisterMessageProcessor(this ContainerHost host, IMessageProcessor processor)
    {
        if (any != null)
        {
            throw new InvalidOperationException("Processor already registered");
        };

        any = new AnyLinkProcessor(processor);
        host.RegisterLinkProcessor(any);
    }

    public static void UnregisterMessageProcessor(this ContainerHost host, IMessageProcessor processor)
    {
        if (any == null || processor != any.processor)
        {
            throw new InvalidOperationException("Processor not registered or different from the registered instance");
        }

        host.UnregisterLinkProcessor(any);
        any = null;
    }

    class AnyLinkProcessor : ILinkProcessor
    {
        internal readonly IMessageProcessor processor;

        public AnyLinkProcessor(IMessageProcessor processor)
        {
            this.processor = processor;
        }

        public void Process(AttachContext attachContext)
        {
            if (attachContext.Attach.Role)
            {
                attachContext.Complete(new Error("amqp:not-allowed"));
            }
            else
            {
                attachContext.Complete(new PublishLinkEndpoint(this.processor), 300);
            }
        }
    }

    class PublishLinkEndpoint : LinkEndpoint
    {
        readonly IMessageProcessor processor;

        public PublishLinkEndpoint(IMessageProcessor processor)
        {
            this.processor = processor;
        }

        public override void OnMessage(MessageContext messageContext)
        {
            // Process can be called concurrently from multiple connections
            this.processor.Process(messageContext);
        }

        public override void OnFlow(FlowContext flowContext)
        {
        }

        public override void OnDisposition(DispositionContext dispositionContext)
        {
            dispositionContext.Complete();
        }
    }
}
```

**Comment by Havret** [comment]
@xinchen10 Actually it doesn't work as address check is done before `linkProcessor` lookup. 

https://github.com/Azure/amqpnetlite/blob/a16ee2ded504ef70185c83cf4914a9f82bf71da8/src/Listener/ContainerHost.cs#L395-L399

**Comment by Havret** [comment]
@xinchen10 Can we do anything about it?

**Comment by xinchen10** [comment]
It is a little late but better than never. I added a  AddressResolver to ContainerHost which can be used to implement this scenario plus many more. Basically the application now has the chance to first take a look at the incoming attach requests and decide which address (i.e. processor) should be used. The processor can be pre-registered or even registered on the fly. Null address is now rejected after invoking the link processor.
