### ISSUE TITLE
ReceiverLink's onMessage callback can receive the same message multiple times

### ISSUE THREAD

**Issue by spankr** [Azure/amqpnetlite#308]
I'm currently trying to bulletproof our amqp logic against network issues. To do that, I have a pair of simple netcore console apps...['hello world' simple](https://github.com/Azure/amqpnetlite/blob/master/dotnet/HelloAmqp/Program.cs).

I am running these console apps in a Windows VM and they connect to a ActiveMQ docker container on a separate Linux box (about 5 feet away).

My testing has been 
1. Start the 2x console apps (via Visual Studio in debug mode). 
1. Send one message to verify publish and subscribe both work. 
1. Disable the network adapter on my VM (to simulate a disconnected ethernet cord).
1. Count to 8 Mississippi. :)
1. Reconnect the network adapter on my VM.
1. Send 2-4 messages from my publisher.

I notice my subscriber processing some of the messages, then the disconnect callbacks fire, which triggers the connection to recover and then finally it starts processing messages again. Except that it does not pick up where it left off but instead appears to re-process old messages.

![screen shot](https://user-images.githubusercontent.com/1530609/45503937-08eecd00-b74e-11e8-9ab3-161fbfa04643.png)

At the bottom of the screenshot, it can be seen what I'm doing for the OnMessage processing.

**Consumer Code Snippet** (for the curious)

```c#
var source = new Source() { Capabilities = new[] { new Symbol("queue") }, Address = queueName };
var receiverLinked = new ManualResetEvent(false);

var dfltBegin = new Begin()
{
    IncomingWindow = 2048,
    OutgoingWindow = 2048,
    HandleMax = (uint)(_factory.AMQP.MaxLinksPerSession - 1),
    NextOutgoingId = uint.MaxValue - 2u
};

do
{
    try
    {
        receiverLinked.Reset();
        _connection = await _factory.CreateAsync(address, null, (con, open) =>
        {
            // on opened
            _session = new Session((Connection)con, dfltBegin, (sess, begin) =>
            {
                // on begin
                _receiver = new ReceiverLink((Session)sess, "receiver-link", source, (link, attach) =>
                {
                    Source s = (Source)attach.Source;
                    Console.WriteLine($"Created subscription for address: {s?.Address}");
                    ((ReceiverLink)link).Start(5, OnMessage);
                    receiverLinked.Set();
                });
            });
        }).ConfigureAwait(false);
        success = receiverLinked.WaitOne(WAIT_TIME);

        if (!success)
        {
            Console.WriteLine("OpenConsumer timeout. Cleanup and try again.");
            Cleanup();
        }
    }
    catch (Exception e)
    {
        Console.WriteLine($"OpenConsumer Exception: {e.Message}. Cleanup and try again");
        Cleanup();
        Thread.Sleep(RETRY_DELAY); // wait x seconds for netork issues to clear up
    }
} while (!success);

_connection.AddClosedCallback(async (sender, error) =>
{
    Console.WriteLine("Connection closed detected");
    if (!_shuttingDown)
    {
        Console.WriteLine("Attempting to reconnect");
        Cleanup();

        Thread.Sleep(RETRY_DELAY); // wait x seconds for network issues to clear up
        await OpenConsumer(connectionUrl, queueName).ConfigureAwait(false);
    }
});
_receiver.AddClosedCallback((_, __) => Console.WriteLine("Receiver fired closed callback"));
_session.AddClosedCallback((_, __) => Console.WriteLine("Session fired closed callback"));
```

I've been able to get this to happen with simpler (not using the connection and session callbacks) logic.

I can't see what I'm doing wrong so I'm posting this as an issue in the case that this is a bug. 

Its not critical to my current work because our issue is *not* getting messages after reconnect. We can put info in our messages to filter out duplicates.

**Comment by xinchen10** [comment]
ReceiverLink.Accept(Message) does not make a network call to make sure the broker has deleted the message. It simply triggers a disposition command to be sent to the broker. Writing this command to network is asynchronous. It is possible that these disposition commands did not make their way to the broker if the connection is lost. A new receiver link will pick up the messages again as they are still available on the broker.
