### ISSUE TITLE
Getting intermittent "Object reference not set to an instance of an object" AmqpException.

### ISSUE THREAD

**Issue by billpoole-mi** [Azure/amqpnetlite#314]
I'm getting an intermittent AmqpException being thrown, where the exception message is "Object reference not set to an instance of an object" thrown from SenderLink.Async(Message, TimeSpan). I haven't been able to figure out the source of the exception because the exception and line number reported don't align with the current version of the source code - possibly because it's compiled for Release rather than Debug?

The only exception info that I have is below.

Amqp.AmqpException: Object reference not set to an instance of an object.
   at Amqp.SenderLink.SendAsync(Message message, TimeSpan timeout) in C:\Users\mqt\repo\amqpnetlite.rel\src\Net\TaskExtensions.cs:line 218

The exception tends to be thrown after 10 minutes or so of sending under load. I'm using the latest version (v2.1.4) of AMQPNetLite.Core and AMQPNetLite.Serialization.

**Comment by billpoole-mi** [comment]
Okay, I've done a bunch more analysis to find where the exception is occurring. The exception being thrown in the SenderLink.Async(Message, TimeSpan) method is actually at line 211 in TaskExtensions.cs:
``` csharp
await new SendTask(this, message, txnState, timeout).Task.ConfigureAwait(false);
```
However, the _originating_ exception is actually being thrown in ReceiverLink.cs at line 540:
```csharp
this.timer.Dispose();
```
From there it's bubbling up to the Connection object. The stack trace I get is:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Amqp.ReceiverLink.AsyncWaiter.Signal(Message message) in C:\...\src\ReceiverLink.cs:line 540
   at Amqp.ReceiverLink.OnTransfer(Delivery delivery, Transfer transfer, ByteBuffer buffer) in C:\...\src\ReceiverLink.cs:line 279
   at Amqp.Session.OnTransfer(Transfer transfer, ByteBuffer buffer) in C:\...\src\Session.cs:line 575
   at Amqp.Session.OnCommand(DescribedList command, ByteBuffer buffer) in C:\...\src\Session.cs:line 342
   at Amqp.Connection.OnSessionCommand(UInt16 remoteChannel, DescribedList command, ByteBuffer buffer) in C:\...\src\Connection.cs:line 537
   at Amqp.Connection.OnFrame(ByteBuffer buffer) in C:\...\src\Connection.cs:line 632
```
From there, it seems to make its way to be an Outcome of a SendTask, passed as the outcome parameter of the OnOutcome callback method in the SendTask class in TaskExtensions.cs at line 289. The OnOutcome method then finds that the descriptor code of the outcome is Rejected.Code and then invokes:
```csharp
thisPtr.TrySetException(new AmqpException(((Rejected)outcome).Error));
```
Line 211 in TaskExtensions.cs then throws this exception, and this also explains why there is no stack trace in the exception beyond the SendAsync method call on line 211 of TaskExtensions.cs.

So it seems that the timer field in the ReceiverLink class isn't guaranteed to be non-null when Signal(Message) is invoked.

**Comment by xinchen10** [comment]
Thanks for finding the bug. You are right. A message could arrive before the timer is initialized in the waiter.

**Comment by billpoole-mi** [comment]
Is it possible to get a new release containing this fix?

**Comment by xinchen10** [comment]
Release 2.1.5.

**Comment by billpoole-mi** [comment]
Thank you!
