### ISSUE TITLE
ReceiverLink flow control issue

### ISSUE THREAD

**Issue by billpoole-mi** [Azure/amqpnetlite#315]
Applications can manage link credits manually by invoking the ReceiverLink.SetCredit method with autoRestore = false, which allows an application to manage link credits itself, passing the credit to the SetCredit method when credit is to be restored. However, the flow frames sent by the receiver to the sender to restore link credit also contains a "delivery count" sequence number, which is the basis upon which the link credit given in the frame is interpreted by the sender, in accordance with the following formula.

link-credit(snd) := delivery-count(rcv) + link-credit(rcv) - delivery-count(snd)

The Amqp.Net Lite library allows the link credit to be managed by the application level by passing the credit to the SetCredit method with autoRestore=false, but does not allow the application to specify the delivery count.

The delivery count and link credit both need to be managed atomically (within the same lock statements) for flow control to work. However, at present the delivery count is managed by the Amqp.Net Lite library and incremented before the application is informed that a message has been received. 

Therefore, the delivery-count sent by the ReceiverLink class in the SetCredit method is "ahead" of the credit managed by the application. This then leads to the "delivery limit" (computed by adding the link-credit to the delivery-count) possibly being incorrect when the Amqp.Net Lite library constructs and sends flow frames to the sender.

This then leads to the number of received messages held by the Amqp.Net Lite library waiting for the application-level to process them growing without bound when the rate that messages are processed is less than the rate at which the messages are delivered.

I can think of the following ways to address this:
- Add a new SetCredit method overload to ReceiverLink and IReceiverLink that accepts a delivery count sequence number, allowing the application-level to manage the delivery count _and_ credit. This would require the SequenceNumber struct to be made public and the InitialDeliveryCount received on link-attach to be exposed to the application. If this option is chosen, it might also be a good idea to mark the current SetCredit method as obsolete, as I expect that it isn't possible to use the SetCredit method to manually manage link credit in its current form without experiencing the issue described.
- Add a new IncrementDeliveryCount method to ReceiverLink and IReceiverLink that increments the delivery count. Applications can invoke this method inside an appropriate lock after being informed by the Amqp.Net Lite library that a message has been received.

In both of the above options, the ReceiverLink class would only increment the delivery count itself in the ReceiverLink.OnDelivery method if autoRestore = true.

**Comment by xinchen10** [comment]
Delivery count should be managed by the receiver link internally because that must be the count of all received deliveries. The problem with manual credit management is that the code should not take the user's parameter and assign it to this.credit directly. It should be computed based on the input and the current internal state of link flow control. The current assumption is that user issues a certain credit, receives and processes all messages, and then call SetCredit again. It is mainly for batched processing case. As ChugR mentioned in another post this could be better implemented with the drain flag.

**Comment by billpoole-mi** [comment]
I think there could be value in allowing an application to completely override the flow control logic in the ReceiverLink class. If the solution I proposed in issue #329 is accepted, then we won't need to implement custom flow control logic to meet our current requirements. But, who knows what strange requirements might come up in the future.

One possible solution would be to provide a SetCredit method overload that accepts an IFlowControlStrategy parameter, where IFlowControlStrategy is defined as:

```csharp
public interface IFlowControlStrategy
{
	/// <summary>
	/// Invoked when the total credit of the receiver link changes.
	/// </summary>
	void OnTotalCreditChanged();

	/// <summary>
	/// Invoked when a message is received.
	/// </summary>
	void OnMessageReceived();

	/// <summary>
	/// Invoked when a message is acknowledged.
	/// </summary>
	/// <param name="setCredit">Sets the remaining link credit to the given value.</param>
	void OnMessageAcknowledged(Action<int> setCredit);
}
```

This would allow the custom flow control logic to execute inside the appropriate lock (this.ThisLock) because the ReceiverLink class would invoke the OnMessageReceived and OnMessageAcknowledged methods inside that lock.

The existing (default) flow control logic could then be separated into a (nested in the ReceiverLink class) DefaultFlowControlStrategy class.

Note: I think that the enhancement proposed in #329 is worthwhile, even if it becomes possible to implement custom flow control logic with a solution to this issue.

**Comment by billpoole-mi** [comment]
I noticed that a recent commit has changed the behavior/semantics of the ReceiverLink.SetCredit method where autoRestore = false to:
- start a drain cycle; and
- ignore subsequent invocations of SetCredit until the drain cycle is complete.

Is this not a breaking change for applications currently using the SetCredit method with autoRestore = false to manually/directly control link credit? For example, invoking SetCredit with autoRestore = false before the drain cycle is complete will no longer send another Flow frame.

Existing applications may be manually calculating their own "restored" credit and invoking SetCredit with autoRestore = false when the restored credit reaches a threshold.

Note: Even though there is an argument to be made that applications shouldn't be doing this (for the reasons described in this issue), existing applications may be doing this because they need direct control over link credit. That is, users may be experiencing this issue but have not noticed (perhaps due to not running under enough load or for long enough time), or have noticed but have no choice but to wear it because their application requires direct control over link credit.

If invoking the SetCredit method with autoRestore = false now starts a drain cycle and subsequent invocations of the SetCredit method are effectively ignored until the drain cycle completes, many existing applications using SetCredit with autoRestore = false in the way I describe above could stop working properly. Receiver links could in some cases become starved because the application expected a SetCredit invocation to send a Flow frame and it did not because a drain cycle was still in progress.

Is there still a desire to support this use case? If so, perhaps a SetCredit overload accepting an IFlowControlStrategy or something similar like I proposed in my previous comment is needed? Developers of existing applications using SetCredit with autoRestore = false to manually restore credit as I described above could migrate their applications to use this new overload. 

This can be justified from the standpoint that they would need to do this anyway to prevent the symptoms described originally in this issue.

If this use was wasn't ever intentionally supported or there is no longer a desire to support it, then I think this has to be made clear in the documentation.

**Comment by xinchen10** [comment]
Manual credit management works reliably only if application receives all available messages allowed by credit before calling SetCredit again, which is effectively the drain mode. The difference is whether credit is reset if insufficient messages are available. Before this change application could still get messages when more are available but now they don't. That could be considered a breaking change to such applications.

I think the link flow control should be managed by the library with some simple inputs defined by the application. For majority of the cases we only need credit, restore threshold and drain flag. Requirement for a custom strategy should be rare. Even if it is needed, it is not trivial to get everything right.

I prefer a single API like SetCredit where user sets up the arguments and everything should just work. We already handle credit and restore threshold. We may need a different overload for the drain flag if this breaking change is not acceptable.

**Comment by billpoole-mi** [comment]
Why could manual credit management not be achieved with a SetCredit overload accepting an IFlowControlStrategy like I proposed? 

My theory is that the internal auto-restore logic as currently implemented in the ReceiverLink class could be refactored out into a DefaultFlowControlStrategy nested class implementing the IFlowControlStrategy interface. If that is possible, then doesn’t that prove manual (app-defined) flow control is possible using the same mechanism?

**Comment by xinchen10** [comment]
It can be achieved with your proposal. I just feel it is over engineered. Link flow control is well defined in the spec and technically there is no custom link flow control. If someone would want to implement the flow control it most likely duplicates the code in the library. Also to fully implement it we would need to expose more (e.g. flow command processing) in the interface. The term "credit" is probably a source of confusion in this discussion. On the API layer credit is not the link credit in the implementation. It is meant to be the total of messages the application wants to prefetch. Underneath the library should calculate the read credit based on a number of flow control states which I always believe the application should not bother with.

**Comment by billpoole-mi** [comment]
Okay fair enough. I defer to your judgement. We don’t need this control now that the auto-restore level is controllable. I just figured it might be better to have the control and not need it than need it and not have it.

Also, I’m okay with the breaking change if you are. I suggest the specifics of the new semantics be documented along with a statement that direct manual (application-level) control over receiver link credit is no longer supported.
