### ISSUE TITLE
ReceiverLink flow control issue

### ISSUE THREAD

**Issue by billpoole-mi** [Azure/amqpnetlite#316]
I re-posted this issue because after posting it the first time, I couldn't find the issue and assumed it was lost. But, after posting it this second time I still couldn't find the issue, so I'm not sure what's going on. Apologies if the issue has now been posted twice. If so, please feel free to close/delete either one of them.

The ReceiverLink class allows an application to manage link credit manually by invoking the SetCredit method with autoRestore = false, however the delivery count sequence number is still managed by the Amqp.Net Lite library, which can lead to the "delivery limit" (computed by adding the link-credit to the delivery-count) increasing without bound over time when the rate of processing messages is less than the rate at which messages are delivered. 

The delivery count is automatically incremented by the Amqp.Net Lite library when a message is received, and that delivery count is sent by the Amqp.Net Lite library in the flow frame with the credit passed to the SetCredit method. The credit received by the sender in the flow frame from the receiver is interpreted in the context of the delivery count received in that flow frame.

The delivery count is incremented by the Amqp.Net Lite library in the OnDelivery method before the received message is given to the application, which means that the delivery count is "ahead" of the credit determined by the application and given to the Amqp.Net Lite library in the SetCredit method.

The delivery count and credit need to both be mutated atomically for flow control to work properly, which is not possible while the Aqmp.Net library mutates the delivery count and the application mutates the link credit. 

Each time the application invokes the SetCredit method with autoRestore = false, the delivery count is higher than it should when the ReceiverLink.OnDelivery method has been invoked (increasing the delivery count), but the application hasn't yet updated the link credit in response to the received message.

I can think of two ways to address this:
1. Add a new SetCredit method overload to IReceiverLink and ReceiverLink that accepts an additional deliveryCount (SequenceNumber) parameter, allowing the application to increment the delivery count itself in the same lock where the link credit is modified. This would require the SequenceNumber struct to be made public and the InitialDeliveryCount received on link-attach to be made available to the application to initialize its delivery count. If this option is selected, then it might be a good idea to mark the current SetCredit method obsolete because I don't expect in its current form it can be used to manually manage link credit without experiencing the issue described.
2. Add an IncrementDeliveryCount method to IReceiverLink and ReceiverLink that increments the delivery count. This would be invoked by the application in the same lock where the link credit is modified.

Both of the above options would require the delivery count to only be incremented by the Amqp.Net Lite library in the OnDelivery method if autoRestore = true.

**Comment by xinchen10** [comment]
Dup of #315
