### ISSUE TITLE
Creating a RabbitMQ compatible listener

### ISSUE THREAD

**Issue by perl80903** [Azure/amqpnetlite#323]
I have a need to create a mock RabbitMQ back-end so that we can do some performance testing on our RabbitMQ enabled logic without access to an actual RabbitMQ instance.

To that end, I thought I could use this library, but I am hitting a roadblock because the RabbitMQ client side requests a protocol version of 0.9.0.1 whereas this library appears to be hard-coded as version 3.1.0.0, so while our RabbitMQ client API can hit my AMQP.Net Lite-based listener prototype, they can't negotiate a connection.

Any suggestions?
(Apologies if I'm doing something really stupid here - I am just getting my feet wet with this)

**Comment by xinchen10** [comment]
RabbitMQ client speaks 0.9 which is not compatible with the standard amqp 1.0 protocol. So this library is not something that can help you.
