### ISSUE TITLE
Feature request: custom auto-renew level for receiver links

### ISSUE THREAD

**Issue by billpoole-mi** [Azure/amqpnetlite#329]
The ReceiverLink class currently always evaluates the auto-renew logic in the ReceiverLink.DisposeMessage method when this.restored >= this.totalCredit / 2. However, this assumes that this.totalCredit /2 messages can always be processed (acknowledged) before needing to restore some credit.

Our problem arises because we're correlating messages into correlation sets, and we can only accept the messages in a given set when all messages in the set have been received and successfully processed. 
Therefore, we can receive a lot of messages that cannot be "completed" until at least one other message is received.

Consequently, we increase the total link credit on a receiver link when we have to - i.e. where we have exhausted the total link credit with pending messages awaiting other messages.

We therefore can end up with a very high total link credit with a low remaining credit (and a high number of pending messages waiting for other messages to arrive). We then find that we can receive messages exhausting the low remaining credit (so this.credit = 0), but still have more than this.totalCredit / 2 "pending" messages that are awaiting the arrival of other messages. 

Those messages won't then ever complete because they're waiting for other messages, but the remaining credit (this.credit) is zero - so no further messages can ever arrive. However, there are many "restored" credits (i.e. this.restored is quite large, but still less than this.totalCredit / 2. So, we need a way to trigger restoring credits, even though this.restored < this.totalCredit / 2.

A solution to this problem would be to allow the application to specify the auto-renew level in the ReceiverLink.SetCredit method. That is, it would be great if the following SetCredit overload was provided:

```csharp
public void SetCredit(int credit, int autoRestoreLevel)
```

Using this overload would of course mean auto-restore is enabled, meaning the autoRestore boolean parameter isn't required.

This can be pretty easily achieved by adding an autoRestoreLevel class member and setting it in the SetCredit method. Then in the DisposeMessage method, this.restored is compared to this.autoRestoreLevel, rather than this.totalCredit / 2.

The existing SetCredit method can then be made private and have its signature changed to:

```csharp
private void SetCredit(int credit, bool autoRestore, int autoRestoreLevel)
```

Then the following two SetCredit overloads can be defined that then invoke the above private method:

```csharp
public void SetCredit(int credit, bool autoRestore = true)
{
	if (credit < 0)
	{
		throw new ArgumentOutOfRangeException(nameof(credit));
	}

	SetCredit(credit, autoRestore, autoRestore ? credit / 2 : 0);
}

public void SetCredit(int credit, int autoRestoreLevel)
{
	if (credit < 0)
	{
		throw new ArgumentOutOfRangeException(nameof(credit));
	}

	if (autoRestoreLevel < 0 || autoRestoreLevel > this.credit)
	{
		throw new ArgumentOutOfRangeException(nameof(autoRestoreLevel));
	}

	SetCredit(credit, true, autoRestoreLevel);
}
```

This added flexibility would solve our problem, whilst maintaining full backwards compatibility with existing Amqp.Net Lite applications.

Note that due to issue #315 still being unresolved, I'm unable to implement custom flow control logic to meet our requirements. If the above proposed feature is not accepted, then it is very important for us that issue #315 be addressed ASAP. I would be happy to propose a solution for this if requested.

Thanks!!

**Comment by xinchen10** [comment]
I think the issue is that the current implementation does not honor user's credit in all conditions. For example, in your case, if you start with 100 credit, receive 100, and complete 30, and expect to receive another 30, but it does not happen. It is a bug. If we fix this bug, will it satisfy your requirement?

**Comment by ChugR** [comment]
Having a client change the total credits while messages are in flight is always going to be problematic.

* Raising the credit limit is usually not a problem
* Lowering the credit limit can easily be a problem

The AMQP 1.0 mechanism for avoiding credit mismatches at each end of a link is the Flow 'drain' flag. Drain works by a receiver sending a Flow with the drain indication True. The sender then sends all available messages to use up the credit from the Flow. If insufficient messages are available then the sender sends the messages followed by a Flow with a delivery-count that consumes all the credit and a credit value of zero. Now the sender and receiver on the link agree on the credit (zero) and there are no messages in flight. The receiver can issue a new Flow with a new total credit limit safely.

The following illustration shows Flow 'drain' working with qpid-dispatch router in drain self test. 
* A client (peer_2) creates a receiver [0,0] and a sender [0,1]. 
* Peer_2 issues one credit to the receiver link and receives 10 credits on the sender link. 
* The sender sends 10 messages
* For 3 messages the receiver receives one message and issues another credit of one.
* On receiving transfer_3 the receiver issues a credit of 20 with the drain flag set
* The sender sends the remaining 6 messages (transfer IDs 4..9)
* The sender then executes the drain by sending a Flow with the TransferId=24 and credit=0

> QDR [B0_2] <- [] peer_2 attach [0,0] receiver link_1 (source: "org.apache.dev", target: none, class: client)
> QDR [B0_2] <- [] peer_2 attach [0,1] sender link_1 (source: none, target: "org.apache.dev", class: client)
> QDR [B0_2] <- [] peer_2 flow [0,0] (0,1)
> QDR [B0_2] -> [] peer_2 attach [0,0] sender link_1 (source: "org.apache.dev", target: none, class: client)
> QDR [B0_2] -> [] peer_2 attach [0,1] receiver link_1 (source: none, target: "org.apache.dev", class: client)
> QDR [B0_2] -> [] peer_2 flow [0,1] (0,10)
> QDR [B0_2] <- [] peer_2 transfer [0,1] (0) settled transfer_0 - 43 bytes transfer presettled
> QDR [B0_2] <- [] peer_2 transfer [0,1] (1) settled transfer_1 - 43 bytes transfer presettled
> QDR [B0_2] <- [] peer_2 transfer [0,1] (2) settled transfer_2 - 43 bytes transfer presettled
> QDR [B0_2] <- [] peer_2 transfer [0,1] (3) settled transfer_3 - 43 bytes transfer presettled
> QDR [B0_2] <- [] peer_2 transfer [0,1] (4) settled transfer_4 - 43 bytes transfer presettled
> QDR [B0_2] <- [] peer_2 transfer [0,1] (5) settled transfer_5 - 43 bytes transfer presettled
> QDR [B0_2] <- [] peer_2 transfer [0,1] (6) settled transfer_6 - 43 bytes transfer presettled
> QDR [B0_2] <- [] peer_2 transfer [0,1] (7) settled transfer_7 - 43 bytes transfer presettled
> QDR [B0_2] <- [] peer_2 transfer [0,1] (8) settled transfer_8 - 43 bytes transfer presettled
> QDR [B0_2] <- [] peer_2 transfer [0,1] (9) settled transfer_9 - 43 bytes no more credit transfer presettled
> QDR [B0_2] -> [] peer_2 flow [0,1] (10,5) credit restored
> QDR [B0_2] -> [] peer_2 transfer [0,0] (0) settled transfer_0 - 43 bytes transfer presettled
> QDR [B0_2] -> [] peer_2 flow [0,1] (10,9)
> QDR [B0_2] -> [] peer_2 flow [0,1] (10,10)
> QDR [B0_2] <- [] peer_2 flow [0,0] (1,1)
> QDR [B0_2] -> [] peer_2 transfer [0,0] (1) settled transfer_1 - 43 bytes no more credit transfer presettled
> QDR [B0_2] <- [] peer_2 flow [0,0] (2,1) credit restored
> QDR [B0_2] -> [] peer_2 transfer [0,0] (2) settled transfer_2 - 43 bytes no more credit transfer presettled
> QDR [B0_2] <- [] peer_2 flow [0,0] (3,1) credit restored
> QDR [B0_2] -> [] peer_2 transfer [0,0] (3) settled transfer_3 - 43 bytes no more credit transfer presettled
> QDR [B0_2] <- [] peer_2 flow [0,0] (4,20) drain credit restored
> QDR [B0_2] -> [] peer_2 transfer [0,0] (4) settled transfer_4 - 43 bytes transfer presettled
> QDR [B0_2] -> [] peer_2 transfer [0,0] (5) settled transfer_5 - 43 bytes transfer presettled
> QDR [B0_2] -> [] peer_2 transfer [0,0] (6) settled transfer_6 - 43 bytes transfer presettled
> QDR [B0_2] -> [] peer_2 transfer [0,0] (7) settled transfer_7 - 43 bytes transfer presettled
> QDR [B0_2] -> [] peer_2 transfer [0,0] (8) settled transfer_8 - 43 bytes transfer presettled
> QDR [B0_2] -> [] peer_2 transfer [0,0] (9) settled transfer_9 - 43 bytes transfer presettled
> QDR [B0_2] -> [] peer_2 flow [0,0] (24,0) drain


If AmqpNetLite could execute a drain cycle for its clients or a client executed a drain cycle then the client could reliably send a flow with a new credit total. There are no messages in flight to mess up the 'remaining' calculations.

**Comment by xinchen10** [comment]
Drain is a nice feature. This library tries to allow a client to manage flow control without knowing every details in amqp link flow. So the receiver link has only the SetCredit API that tries to handle common cases. From a user's perspective, draining is no different than stopping the link with 0 credit while still accepting incoming messages. One thought about the SetCredit API was to use drain when credit is 0 (the library would send a flow with remaining credit and a true drain flag). It hasn't been implemented yet.
However, the issue in @billpoole-mi's case is about batching restored credits (to send less flow frames) while the credit is increased.

**Comment by billpoole-mi** [comment]
I think the essence of the problem is that the Amqp.Net Lite library doesn't know (and shouldn't know) how many of the "pending" messages it knows about are awaiting other messages to arrive, meaning that they are effectively suspended (on ice as such), reducing the effective/working size of the flow control window.

I think that it is a completely reasonable default position for the library to take to trigger auto-restore when this.restored reaches this.totalCredit / 2, because it is assuming that none of its "pending" messages are suspended as such. i.e. it expects (quite reasonably) that all of the "pending" messages will complete eventually, not requiring any further messages to be received to do so.

However, the number of "pending" messages that are suspended (awaiting the arrival of other messages) must be subtracted from the size of the flow control window when considering the appropriate trigger (i.e. the number of "restored" messages) for auto-restore.

That is, an application may need a flow control window of 500 credits. So, if there are 200 "suspended" messages, then application should increase the total credit to 700, but auto-restore should still be triggered after this.restored reaches 250 (500 / 2). No matter how many suspended messages there are at any given time (and therefore no matter the size of this.totalCredit), the true size of the flow control window is 500, and therefore the auto-restore trigger should always be 250.

Since there is no way for the Amqp.Net Lite library to know the number of suspended messages, it can't determine the real size of the flow control window, and therefore can't determine the appropriate threshold for auto-restore. So, I think providing a SetCredit method overload that allows the application to override the default auto-restore level is a suitable way to meet the requirement.

**Comment by billpoole-mi** [comment]
@ChugR, we're not actually experiencing a problem from reducing the total credit. This scenario actually arises after only increasing the total credit, but then having a lot of messages waiting for other messages to arrive. This then means that auto-restore is not triggered, even though this.restored is quite high (but still less than this.totalCredit / 2).

I have implemented my proposed solution and it does work, including through the process of reducing the credit limit as the number of messages awaiting other messages is reduced.

**Comment by xinchen10** [comment]
@billpoole-mi the library actually knows the pending (or suspended) messages. They are returned by receive call but not accepted/rejected yet. Given a credit, the library needs to give that many messages, if available, to the application, even when more than half of received messages are suspended. This is something I am going to fix.

**Comment by billpoole-mi** [comment]
Although all suspended messages are pending, not all pending messages are suspended. A suspended message is a pending message awaiting the arrival of another message. That is, a suspended message can never finish being processed until one or more other messages have arrived. A pending message that is not suspended will complete without any other messages being received, given time to do so. A suspended message becomes un-suspended when the last of the other messages it needs to finish being processed arrives.

Therefore, while a ReceiverLink knows the number of pending messages, it doesn't know the number of suspended messages.

Consider a ReceiverLink where totalCredit = 1,000, remaining credit = 100, pending = 600 and restored = 300. When the next message arrives, should the ReceiverLink auto-restore or not? The current logic doesn't auto-restore because restored (300) < totalCredit / 2 (500).

I would say that if more than 400 of the 600 pending messages are suspended, then the ReceiverLink should auto-restore because the appropriate auto-restore threshold is (1,000 - 400) / 2 = 300. If fewer than 400 of the 600 pending messages are suspended, then the ReceiverLink should _not_ auto-restore.

Thus without knowing the number of pending messages that are suspended, the library cannot determine whether the auto-restore.

Note that it is important that we don't use the fact that the remaining credit is small and pending is high as a trigger for auto-restore because when a receiver is processing messages slower than the sender can send them, the remaining credit is consistently small and pending consistently high. If that were to trigger auto-restore, then there would be too many Flow frames being sent.

If there are pending messages that will complete if given some time to do so (i.e. they are not suspended), it's better to wait for more pending messages to complete before sending a Flow frame.

So, although this issue could be solved by changing the auto-restore trigger condition from restored >= totalCredit / 2 to something like restored >= credit or restored >= (totalCredit - pending) / 2, this would have the unwanted side effect of sending a flood of Flow frames when the receiver is processing messages slower than the sender can provide them.

One option would be to provide a mechanism for the application to tell the library when messages are suspended and un-suspended so it can keep a count of suspended messages and factor that into its flow control logic.

However, I think it's better to leave the concept of suspended messages at the application level and let the application specify the auto-restore threshold itself (when invoking the SetCredit method), using the number of suspended messages as an input to that calculation.

I'm happy to submit a pull request for this if requested.

**Comment by xinchen10** [comment]
I misunderstood the term "suspended". It might be very specific to your application. In most cases application starts processing a message right after it receives it from the link and they won't have issues with the current credit restore logic.

It is nice that the application could set the restore threshold but that won't handle all cases. For example, application sets credit to 100 and threshold to 10, and then hold on to 99 messages and just accept one. The next receive call won't get message either. Application could adjust the threshold based on the "suspended" messages but I believe the credit batching logic should not be a concern to the application. All it should do is setting a credit which is the max number of messages it can process.

For this corner case we should trigger a flow when restoring credit under this condition:
(this.credit == 0 && this.receivedMessages.Count == 0)

Yes, it could potentially send one flow for every message but that only happens when the application holds on to all messages. As soon as it starts accepting/rejecting messages it will get out of this situation right away. For the common usage pattern it will never be hit.

We should need to trigger a flow in SetCredit when restored is non-zero even if credit does not change, or it is reduced but the diff is less than restored.

**Comment by billpoole-mi** [comment]
In the scenario you gave (where the application sets credit to 100 and threshold to 10, and then holds onto 99 messages and just accepts one), the next receive call _may_ eventually get a message, depending on what it means for the application to "hold onto" the 99 messages.

If "holds onto" means that none of the 99 messages can be processed until other messages arrive, then you are correct and the next receive call will not ever get a message. However, if 9 or more of the 99 pending messages can/will be processed without requiring other messages to be received, then once they have been processed (i.e. this.restored reaches 10), the credit will be auto-restored and then more messages received.

The _only_ scenario where the receiver link can be starved under the current flow control logic is where enough of the pending messages cannot be processed until other messages have been received (and therefore will _never_ complete). In _all_ other circumstances, the pending messages in hand will naturally eventually complete, increasing this.restored until this.restored = this.totalCredit / 2 (at which point credit is auto-restored).

If the SetCredit method sends a Flow frame when current credit stays the same or is decreased (but only when this.restored > 0) as you suggest, then it allows an application to use the SetCredit method to effectively "flush" the restored credit (or the part of thereof that can be flushed based on the new credit limit).

However, this is still making credit batching logic a concern of the application.  That is, presumably an application would seek to invoke SetCredit with the same total credit only when it is actually seeking to manually restore credit because it has determined that:
- it has run out of credit;
- restored > 0 (meaning there is credit available to "flush"); and
- no further messages can be completed without receiving other messages.

Perhaps there is value in adding a SetCredit overload that accepts a flushCredit parameter, which determines whether the maximum amount of restored credit that _can_ be "flushed" to the peer _is_ flushed?

```csharp
public void SetCredit(int credit, bool flushCredit, bool autoRestore = true)
```

A separate SetCredit overload would be needed (rather than adding an optional flushCredit parameter (with a default value) to the existing SetCredit method), because many applications would want the credit to be flushed _only_ if credit is increasing (i.e. the current behavior). That is, we wouldn't want the application to have to check whether the credit is increasing and set flushCredit to 'true' if it is and 'false' if it isn't to get the current behavior.

Although, this method signature is not ideal because the flushCredit parameter doesn't make sense if autoRestore is false because a Flow frame is _always_ sent if autoRestore is false. Therefore, we would have to throw an exception if this overload is invoked with flushCredit = false and autoRestore = false. 

I'm also not sure whether sending a Flow frame when disposing a message and this.credit == 0 && this.receivedMessages.Count == 0 is the right thing to do. This assumes that the remaining pending messages are waiting for other messages to arrive (i.e. they will never complete processing - i.e. they are 'suspended').

I think that in the the vast majority of circumstances, the pending messages are not 'suspended' and _will_ eventually complete (without requiring receipt of other messages), which makes _not_ sending a Flow frame when this.credit == 0 && this.receivedMessages.Count == 0 the right thing to do. i.e. the right thing to do is wait for more of the pending messages to complete processing.

I got the impression from your response that you're happy with the idea of allowing the application to specify the auto-restore threshold. So, I've created a pull request for this on that assumption, which adds the following SetCredit overload:

```csharp
public void SetCredit(int credit, int autoRestoreThreshold)
```

**Comment by billpoole-mi** [comment]
I've run a few tests using the updated ReceiverLink flow control logic and am finding that the link is quite often sending a flood of Flow frames due to the following predicate triggering auto-restore (from line 484 of ReceiverLink.cs):

```csharp
this.credit == 0 && this.receivedMessages.First == null
```

A snippet of the output showing one such flood is below.

12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=1. Sent Flow frame with credit=1 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=4. Sent Flow frame with credit=4 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=3. Sent Flow frame with credit=3 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=3. Sent Flow frame with credit=3 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=5. Sent Flow frame with credit=5 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=4. Sent Flow frame with credit=4 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=4. Sent Flow frame with credit=4 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=2. Sent Flow frame with credit=2 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=4. Sent Flow frame with credit=4 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=3. Sent Flow frame with credit=3 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=4. Sent Flow frame with credit=4 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=4. Sent Flow frame with credit=4 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=2. Sent Flow frame with credit=2 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=5. Sent Flow frame with credit=5 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=4. Sent Flow frame with credit=4 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=4. Sent Flow frame with credit=4 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=4. Sent Flow frame with credit=4 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=3. Sent Flow frame with credit=3 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=4. Sent Flow frame with credit=4 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=2. Sent Flow frame with credit=2 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=3. Sent Flow frame with credit=3 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=4. Sent Flow frame with credit=4 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=4. Sent Flow frame with credit=4 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=3. Sent Flow frame with credit=3 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=1. Sent Flow frame with credit=1 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=6. Sent Flow frame with credit=6 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=3. Sent Flow frame with credit=3 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=5. Sent Flow frame with credit=5 to peer.
12/02/2019 4:03:04 PM: Auto-restored credit. Restored count=5. Sent Flow frame with credit=5 to peer.

I think the predicate above should be removed from the auto-restore condition. I can't think of a situation where it is needed.

**Comment by xinchen10** [comment]
This is needed to handle a corner case. App starts with 10 credit, receives 10, accept 1, and then calls receive to get another message. Without this the last receive will always return null. If the app processes and accepts messages in the order they are received, this condition will never be hit.
Your pattern is very unique that the current flow control is not sufficient to handle it. I will make some changes that hopefully will satisfy the simple use case and at the same time gives more control to application if needed.

**Comment by billpoole-mi** [comment]
I think it is sufficient for the library to assume all pending messages will be processed/accepted, given enough time. The only time this is not so is where the app is correlating messages, so some messages won’t ever be accepted until other messages are received.

In this corner case, I think it is sufficient for the app to inform the library it needs more credit to cover these messages waiting for other messages. That’s what we are doing and it is working very nicely.

The only issue we have now is that when credit is low, the library sends floods of Flow frames.

As far as I can tell, if that condition is removed from the auto-restore trigger and if we assume apps correlating messages will increase credit when needed, then all cases are met.

**Comment by xinchen10** [comment]
I added a CreditMode option so that app can control whether and when credits should be restored. I still feel like in the special case calling SetCredit is just a workaround and it requires app to keep track of the issued credit and "suspended" messages. With this option if an app relies on the library's buffer queue for incoming messages, it should use RestoreOnAcknowledge. If an app has its own message queue and processes messages in batches or based on some correlation, it should use RestoreOnReceive.

**Comment by billpoole-mi** [comment]
RestoreOnReceive isn't going to work for our requirements. We don't want to auto-restore on receive. We want to auto-restore when our application decides it needs to, which is in one of the following two scenarios:
- The received message has been processed/acknowledged (i.e. all processing pertaining to the message is complete)
- The received message has been correlated and is awaiting the arrival of one or more other messages. When all the required messages arrive for a correlation, all the messages that were waiting are "un-restored", for lack of a better way of describing it.

What actually happens is the application "borrows" one credit when any message is correlated and is then waiting for another message to arrive. When the borrowed balance reaches a threshold, we call SetCredit and boost the amount of credit. When a correlation set completes, a credit is "repaid" for each message in the set. Once sufficient credit has been repaid, the total credit is reduced by calling SetCredit again.

We need to decide whether this logic is app-level logic or not. If this logic is going to be implemented in the AmqpNetLite library, then we'd need to add the concept of message correlation into the AmqpNetLite library and then have AmqpNetLite implement the above logic. 

Personally, I think it's an app-level concept and left out of AmqpNetLite.

The issue is that the application knows something that AmqpNetLite doesn't. That is, it knows how many of the "pending" messages that are "suspended" (awaiting other messages). AmqpNetLite doesn't know this.

Adding a credit mode doesn't tell the library that information. The only way to get the library to deal with it all so the app never has to call SetCredit again (after the first time) would be to add something like a Suspend(Message) method and Unsuspend(Message) method, which would increase and decrease the "suspended" count respectively.

**Comment by xinchen10** [comment]
This is really the Manual mode. We should fix that mode so it works for your scenario. Auto-mode should just work after SetCredit is called once in all cases. I think if we also track flow control states in manual mode but only send flow when SetCredit is called, it should work.

**Comment by billpoole-mi** [comment]
By the way, I think the CreditMode.RestoreOnReceive option would be really dangerous because the receiver would have to process messages at the same or faster rate than the sender is sending them. Otherwise it would get overloaded. The internal AmqpNetLite message queue would grow unbounded until the system ran out of memory.

I described a solution for allowing the app to do flow control manually in issue #315, but you weren't in favor of it.

Do you have a really strong objection to keeping the solution as is, but just removing the part of the auto-restore trigger condition below?

```csharp
this.credit == 0 && this.receivedMessages.First == null
```

If this condition were to be removed from the auto-restore trigger, then I think we'd have a solution that meets everyone's requirements. If people are not doing correlation, then they can call SetCredit once when creating the receiver link. If they *are* doing correlation, then they can implement the flow control logic I described above, calling the SetCredit as described above.

**Comment by xinchen10** [comment]
It is dangerous if the app's queue is unbounded or the app doesn't know when to stop calling receive. This is why it is not the default. I thought it would work for your scenario because i don't see a big difference between getting messages from the local buffer and from the remote by increasing credit. If I cannot find a better solution, I will revert it to the previous behavior and remove the latest auto-restore trigger. I have tried :-)

**Comment by billpoole-mi** [comment]
I very much appreciate your efforts in working through this. Just to confirm, are you suggesting reverting the code back to where it was just prior to the CreditMode option (4 hours ago) and removing the this.credit == 0 && this.receivedMessages.First == null part of the auto-restore trigger? If so, then that would be awesome and very much appreciated!

**Comment by billpoole-mi** [comment]
Sorry, accidentally closed the issue. :-)

**Comment by jjpepper** [comment]
It sounds here like all of @billpoole-mi 's requirements are met by removing:

```csharp
this.credit == 0 && this.receivedMessages.First == null
```

To me, it seems pretty clear that @billpoole-mi's requirements are not specific to his application.  This concept of "suspended" vs pending, where suspended means that it *cannot be accepted* until more messages are received is a general requirement for any use of AmqpNetLite that is doing message correlation.  The use of correlation implies that there are some messages that aren't going away.  So any argument that it's not worth doing this because it's catering too closely to one particular user seems incorrect.

Since AmqpNetLite does not know about this concept of _suspended_ messages, it must assume the most likely case for a message is that it will be consumed.  Users of AmqpNetLite that understand the concept of _suspended_ messages themselves can (*and must*) increase link credit themselves via `SetCredit`, and this is done much more eagerly so that auto-restoring credit is not necessary.

Users of AmqpNetLite that don't do message correlation and are unaware of any concept of _suspended_ messages will *always* consume the messages eventually (even if no other message is received from the peer), and therefore don't need to auto restore.

Do you agree with this assessment @xinchen10?

I believe this is what @billpoole-mi is saying here:

> I'm also not sure whether sending a Flow frame when disposing a message and this.credit == 0 && this.receivedMessages.Count == 0 is the right thing to do. This assumes that the remaining pending messages are waiting for other messages to arrive (i.e. they will never complete processing - i.e. they are 'suspended').

> I think that in the the vast majority of circumstances, the pending messages are not 'suspended' and _will_ eventually complete (without requiring receipt of other messages), which makes _not_ sending a Flow frame when this.credit == 0 && this.receivedMessages.Count == 0 the right thing to do. i.e. the right thing to do is wait for more of the pending messages to complete processing.

Have I correctly paraphrased what you are arguing @billpoole-mi?

**Comment by billpoole-mi** [comment]
Yes indeed, thanks @jjpepper!

**Comment by jjpepper** [comment]
@xinchen10 just checking what your intention is with this one?
