### ISSUE TITLE
The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101

### ISSUE THREAD

**Issue by iamkarlson** [Azure/amqpnetlite#333]
Hi guys, 
Could you help me to understand what is the actual issue here? I'm just got this after some refactorings. I've tried a bit to investigate underlying problem but cannot say for sure what is leading to that. This issue is 100% false in description because I've tried 2 different connection strings to different services buses. I've also tested with another tool and it's working fine. 

```
error(condition:amqp:internal-error,description:The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101)
```

Here's a screenshot of the sender link state after SendAsync call:

![image](https://user-images.githubusercontent.com/4534374/51837794-d90f2300-2304-11e9-94de-a45a0717ae4b.png)

It looks like that the link tried to send the message but something went wrong.

**Comment by xinchen10** [comment]
The link is still attached. The error is likely for the message transfer. Did it come back in a disposition frame?

**Comment by iamkarlson** [comment]
I've accidentally discovered that TTL was set to 0. I believe that is the
reason. How do you think is difficult to add TTL check in the library?

**Comment by xinchen10** [comment]
If the spec defines a range of a property value, the library should validate it; otherwise it should transmit the value as is so that the receiver can interpret and handle it. In this case if the SB service does not allow 0 for ttl, it needs to reject the message with clear error message. I will forward the issue to the SB team.

**Comment by iamkarlson** [comment]
Thanks
