### ISSUE TITLE
Possible ConnectionFactory interface issue

### ISSUE THREAD

**Issue by billpoole-mi** [Azure/amqpnetlite#334]
We have a situation where we need to open new AMQP connections on demand to various remote peers using various SASL mechanisms (anonymous, plain and external/TLS). We use the ConnectionFactory.CreateAsync method to create the connections.

However, the choice of anonymous, plain or external/TLS is specified through the ConnectionFactory.SASL.Profile and ConnectionFactory.SSL properties. The problem is that to meet our requirements, we would need to change these properties while the connection factory may be in the progress of creating connections.

It strikes me that it should be possible to use a single connection factory to create connections in parallel to different hosts, where different hosts use different SASL mechanisms. This would be possible if a ConnectionFactory.CreateAsync method overload were provided with a SaslProfile parameter.

We also should consider whether it should also be possible to specify SslSettings for each new connection in the CreateAsync method.

**Comment by xinchen10** [comment]
Factory is just a helper for opening connections. You can create factories on demand based on your setup. You could have a helper method like this.
```
static Task<Connection> OpenConnectionAsync(Address address, TcpSettings tcp, SslSettings ssl, SaslSettings sasl, ...)
{
    var factory = new ConnectionFactory();
    // configure the factory based on parameters
    return factory.CreateAsync(address);
}
```

**Comment by billpoole-mi** [comment]
Good point. It didn't occur to me to create single-use factories. Thanks!
