### ISSUE TITLE
About Microsoft Azure AMQP for .Net

### ISSUE THREAD

**Issue by 4wakened5leeper** [Azure/amqpnetlite#337]
Hi, I just came across [this library](https://github.com/Azure/azure-amqp) and I was wondering what was the difference between this lib and AMQP Net Lite ?
@xinchen10 I found many similarities in the code, so as you seems to be the main contributor to this two libs, could you tell us more about the purpose of each of these libraries?

**Comment by StanislavPrusac** [comment]
Explanation ( xinchen10 ):
Azure.Amqp is the main stack that our clients (SB, EH, Relay) are built upon and will be supported for the main stream dotnet platforms. When dotnet platforms evolve, support for early versions may be dropped (e.g. net45).amqpnetlite is designed to run on most dotnet frameworks with even old versions. It is not officially supported.We have plans to update them and provide guidelines for selecting the right library.

[https://github.com/Azure/azure-service-bus-dotnet/issues/42](https://github.com/Azure/azure-service-bus-dotnet/issues/42)

**Comment by hacst** [comment]
Does Microsoft consider azure-amqp as something external developers can use or should we stick to amqpnetlite if we want something that is targeted more towards that? Being the basis for the official clients sounds great but from the outside azure-amqp has less activity, documentation and examples which makes me weary.

**Comment by jwillmer** [comment]
Any reason why this is closed without any comment? @xinchen10
