### ISSUE TITLE
Unlocking message after receiver is closed/connection

### ISSUE THREAD

**Issue by mh05** [Azure/amqpnetlite#340]
I have case with the underlying problems 

1. I need to lock message on one receiver-link
2. After the receiver-link is closed all message should be unlocked
3. Have an amount of locked message (I my case 100)
4. Receiverlink should constantly pull for message (by async)

Situation:

A Senderlink sends a message into Azure Service Bus.
The receiver link gets this message from Azure Service Bus and need process this message.
Processing of message can take a long time. During this period the message should be lock on Azure Service Bus (or only be communicate to this receiver link). The message should be release on behave of this receiverLink or unlocked when the receiverlink is killed (crashed, threading)

At this point. I’m closing the connection, receiverlink and session but a messages are still locked. Is there an way to solve this?

**Comment by xinchen10** [comment]
Technically if the receiver link is attached with `source.durable = false; source.default-outcome = released;`, the broker should release all locked messages when the link is closed. But I am not sure if Azure Service Bus does it today.
