### ISSUE TITLE
RabbitMQ and VirtualHost

### ISSUE THREAD

**Issue by mrdance** [Azure/amqpnetlite#341]
It seems like whatever set for VirtualHost is not sent and used. Use wireshark to check this. Any ideas?

**Comment by xinchen10** [comment]
By VirtualHost do you mean the open.hostname field? If you can capture the frame logs please post it here (removing your credentials in SASL frames if any). The instruction can be found here.
https://github.com/Azure/amqpnetlite/blob/master/docs/articles/tracing.md

**Comment by Gsantomaggio** [comment]
for future readers:
```csharp
 var open = new Open
                {
                    HostName = "vhost:my_vhost", // <--- to set the vhost in rabbitmq
                    Properties = new Fields()
                    {
                        [new Symbol("connection_name")] = "my_connection_name"
                    }
                };
```
