### ISSUE TITLE
Release() increments delivery count with Azure Service Bus

### ISSUE THREAD

**Issue by michaelburch** [Azure/amqpnetlite#342]
Calling Release(message) results in the DeliveryCount property being incremented. Expected behavior is that the DeliveryCount is unchanged

Link is created as follows:

` 
connection = await factory.CreateAsync(_settings.Address);

            session = new Session(connection);

            attach = new Attach

            {

                SndSettleMode = SenderSettleMode.Unsettled,

                RcvSettleMode = ReceiverSettleMode.Second,

                Source = new Source() { Address = $"{_settings.Topic}{_settings.EntityPath}", DefaultOutcome = new Released() },

                Target = new Target()

            };

            link = new ReceiverLink(session, Guid.NewGuid().ToString(), attach, null);
            link.SetCredit(prefetchCount, true);

`

**Comment by xinchen10** [comment]
Release should not increment delivery count. I think the release outcome is likely not processed by the service? Do you end the program right after calling release?

**Comment by michaelburch** [comment]
no, in fact the receiver stays running much like the LongHaulTest

**Comment by xinchen10** [comment]
The library just sends a released outcome when you call Release method. I will pass the question to the Service Bus team.

**Comment by yvgopal** [comment]
Service Bus processes Release outcome and it doesn't increment delivery count on Release. Could you check if something else is causing the delivery count to be incremented? like message lock is already lost before you sent the Released outcome.
