### ISSUE TITLE
Receive messages already in queue .Net Core IBM MQ while service is down

### ISSUE THREAD

**Issue by rgaffo** [Azure/amqpnetlite#343]
Hi,

I tried to recover messages that already in queue while service is down, but doesn't work.

The service just receive messages after is connected and subscribe in the topic.

There are no errors, any one have idea what am I doing wrong?

The code that I use is:

```
static void Main(string[] args)
{
var strAddress = $"{scheme}://{user}:{password}@{host}:{port}";
var address = new Address(strAddress);

var openFrame = new Open();
openFrame.ContainerId = "IntegradorAPI";

var connection = new Connection(address, null, openFrame, null);
var session = new Session(connection);

var receiver = new ReceiverLink(session, queueManagerName, queueName);
receiver.Start(int.MaxValue, AMQP_Receiver);
}

public static void AMQP_Receiver(IReceiverLink receiver, Message message)
{
receiver.Accept(message);
}
```

**Comment by xinchen10** [comment]
@rgaffo is this all the code in your program? `ReceiverLink.Start()` method is not blocking. It returns after it sets the link credit and registers the message callback, so your application will exit before messages arrive. If your application is running but you still do not get messages, try to get frame level traces by following this doc https://github.com/Azure/amqpnetlite/blob/master/docs/articles/tracing.md.

**Comment by rgaffo** [comment]
@xinchen10 thanks for you reply! After `ReceiverLink.Start()` method I have `Console.ReadKey()` for my application not exit before messages arrive. I set `AMQP_Receiver` callback to receive new messages sended to queue. 

To receive new messages after my application run and connect work fine, but to receive messages that already in queue while the service is down isn`t work.

**Comment by xinchen10** [comment]
I think this is specific to the MQ broker, rather something in the client or the AMQP protocol. AMQP receivers are subscribers of a topic. Maybe the subscription is not durable so the receiver can only get new messages. Or the message has TTL so they expired before the client connects. It might also be something else.

**Comment by rgaffo** [comment]
I think the same. I will keep trying and if i have news I post here.

Thanks for your time.
