### ISSUE TITLE
Should TaskCompletionSource objects be created with TaskCreationOptions.RunContinuationsAsynchronously?

### ISSUE THREAD

**Issue by billpoole-mi** [Azure/amqpnetlite#345]
Best practice for using TaskCompletionSource<TResult> seems to be that instances always be created passing TaskCreationOptions.RunContinuationsAsynchronously to the constructor.

See:
- https://blogs.msdn.microsoft.com/seteplia/2018/10/01/the-danger-of-taskcompletionsourcet-class/
- https://github.com/dotnet/corefx/issues/2454

Should the Amqp.Net Lite library be updated accordingly?

**Comment by xinchen10** [comment]
No plan to make this change.
