### ISSUE TITLE
Closed callback - fault handling

### ISSUE THREAD

**Issue by jan-maria** [Azure/amqpnetlite#348]
Hello,

I have an question about Closed callback and fault handling - do I need to attach callback on every layer - i.e. connection, session and link to get notification about all errors or they bubble up? In other words if I add an callback to link only, will it also notify about all errors in session and connection layer?

Thank you,
Best Regards,

**Comment by xinchen10** [comment]
Yes, it does. When a session is closed, it aborts all active links which will raise Closed event on each link. Connection does the same to sessions.

**Comment by jan-maria** [comment]
OK, thanks! :)
