### ISSUE TITLE
rabbitmq Fanout exchange type

### ISSUE THREAD

**Issue by gulzarahamed** [Azure/amqpnetlite#349]
I am using RabbitMq 3.7.7, and Erlang 21.0, if i am using raabitmq client with 'Fanout' exchange type to send message  ie., mention only the exchange name (no queue name), and from receiver end, create multiple receivers, so the Fanout Exchange publish messages to all the queues bound to that exchange name. then the receivers able to receive the message. How i can implement this using amqnetlite, without mention the queue name, how i can send and receive message.

as part of my analysis, i have tried the below test, but it throw error like 'Dynamic targets not supported' exception, when i run the below test

#if NETFX || NETFX35 || NETFX_CORE || DOTNET
        [TestMethod]
#endif
        public void TestMethod_DynamicSenderLink()
        {
            string testName = "DynamicSenderLink";
            Connection connection = new Connection(testTarget.Address);
            Session session = new Session(connection);

            string targetAddress = null;
            OnAttached onAttached = (link, attach) =>
            {
                targetAddress = ((Target)attach.Target).Address;
            };

            SenderLink sender = new SenderLink(session, "sender-" + testName, new Target() { Dynamic = true }, onAttached);
            Message message = new Message("hello");
            sender.Send(message);

            Assert.IsTrue(targetAddress != null, "dynamic target not attached");
            ReceiverLink receiver = new ReceiverLink(session, "receiver-" + testName, targetAddress);
            message = receiver.Receive();
            Assert.IsTrue(message != null, "no message was received.");
            receiver.Accept(message);

            sender.Close();
            receiver.Close();
            session.Close();
            connection.Close();
        }

**Comment by JimWeier-VeteransUnited** [comment]
Did you get any clarification on this? I am encountering same issue

**Comment by xinchen10** [comment]
The exchange concept is in an early AMQP version. It doesn't exist in the standardized AMQP 1.0. When you send to a target, it has to be named or dynamic, even though the protocol doesn't really care what is behind the target. I think RabbitMq would be a better place to ask how this can be mapped to the AMQP 1.0 protocol (if they ever support it).
