### ISSUE TITLE
Small memory devices

### ISSUE THREAD

**Issue by josesimoes** [Azure/amqpnetlite#35]
The current implementation for .NET Micro framework eats an incredible amount of RAM and FLASH. This is a killer issue in resource constrained devices.
That is mostly because of the way exception handling and trace messages are implemented: they are too verbose.
Also because of the very tidy organization of the classes and derived classes it often ends up with huge call stacks. This is an issue in devices with small memory because the argument objects are copied over and over eating a lot of precious RAM space.

I've send a pull request to address these issues. Basically it reworks the implementation of the exception, error codes and several method declarations where I've changed the arguments to be passed by reference. 

To use this just add SMALL_MEMORY to the project compiler definitions and reload the solution.
(this is required because I'm using that definition to include - or not - some files and the resource file in the project tree)

Follows the comparison of FLASH and RAM usage in the app I've tested this with (no other changes in code except for the recompilation of the AMQP library).
Current implementation: 
- deployment (FLASH) 170732 bytes 
- free RAM after boot 19262 bytes

Using the SMALL_MEMORY compilation:
- deployment (FLASH) 154732 bytes 
- free RAM after boot 31904 bytes

This is my contribution to this awesome library that is a great addition to the .NET Micro framework for IoT projects. 
Please review and comment! :smile:

**Comment by josesimoes** [comment]
@xinchen10 are you planning to release the tiny package to nugget any time soon?

**Comment by xinchen10** [comment]
@josesimoes yes I will release the nuget package in a couple of days.

**Comment by xinchen10** [comment]
Release AmqpNetMicro
