### ISSUE TITLE
Error in Encoding of custom type object while sending message

### ISSUE THREAD

**Issue by GaikwadPratik** [Azure/amqpnetlite#350]
@xinchen10 ,

I am following [this example](https://github.com/Azure/amqpnetlite/blob/master/Examples/PeerToPeer/PeerToPeer.CustomType/Person.cs#L97) to send custom object over amqp using sender. My code is as below:

```
[AmqpContract(Encoding = EncodingType.SimpleMap)]
public class Response
{
    [AmqpMember(Name = "responseCode")]
    public string ResponseCode { get; set; }
    [AmqpMember(Name = "responseMessage")]
    public object ResponseMessage { get; set; }
}
```
send function is as below:
```
var _response = new Response();
 _response.ResponseCode = "OK";
 _response.ResponseMessage = 1;
Message _message = new Message(body: _response);
this._sender = new SenderLink(session: this._session, name: "ServerResponse", address: replyTo);
_message.Properties = new Properties()
{
     CorrelationId = correlationId,
     Subject = this._subject,
};
_message.Header = new Header()
{
     Ttl = 10000
};
await this._sender.SendAsync(message: _message);
```

The `SendAsync` gives me below error:

```
{
    "Error": {
        "Condition": {},
        "Description": "The type 'AmqpNetLiteRpcCore.Response' is not a valid AMQP type and cannot be encoded.",
        "Info": null,
        "Descriptor": {
            "Name": "amqp:error:list",
            "Code": 29
        }
    },
    "Message": "The type 'AmqpNetLiteRpcCore.Response' is not a valid AMQP type and cannot be encoded.",
    "Data": {},
    "InnerException": null,
    "StackTrace": "   at Amqp.Types.Encoder.WriteObject(ByteBuffer buffer, Object value, Boolean smallEncoding)\n   at Amqp.Message.WriteToBuffer(ByteBuffer buffer)\n   at Amqp.Message.Encode(IBufferManager bufferManager, Int32 reservedBytes)\n   at Amqp.SenderLink.Send(Message message, DeliveryState deliveryState, OutcomeCallback callback, Object state)\n   at Amqp.SendTask..ctor(SenderLink link, Message message, DeliveryState state, TimeSpan timeout)\n   at Amqp.SenderLink.SendAsync(Message message, TimeSpan timeout)\n   at AmqpNetLiteRpcCore.RpcServer.SendResponse(String replyTo, String correlationId, String requestType, Object response, Exception ex) in /home/pratik/hive/dev/AmqpNetLiteRpc/AmqpNetLiteRpcCore/RpcServer.cs:line 180\n   at AmqpNetLiteRpcCore.RpcServer.<>c__DisplayClass8_0.<<ProcessIncomingRpcRequest>b__0>d.MoveNext() in /home/pratik/hive/dev/AmqpNetLiteRpc/AmqpNetLiteRpcCore/RpcServer.cs:line 98",
    "HelpLink": null,
    "Source": "Amqp.Net",
    "HResult": -2146233088
}
```

What am I missing?

**Comment by GaikwadPratik** [comment]
@xinchen10 ,

I am observing same behavior when I running [this line](https://github.com/Azure/amqpnetlite/blob/master/Examples/PeerToPeer/PeerToPeer.CustomType/Program.cs#L71) from the GitRepository directly.

Can you please assist?

**Comment by xinchen10** [comment]
@GaikwadPratik are you using the .net core package? This page explains how to create the message for serialization on .net core (bottom of the page).
https://github.com/Azure/amqpnetlite/blob/master/docs/articles/serialization.md

I will make sure the API doc or the exception message has enough information for this failure.

**Comment by GaikwadPratik** [comment]
@xinchen10 

That works.... :) May be you can make it bold or highlight it in some other way? 

Based on this I have another question. Since my class library is pointing to .netstandard 2.0, if I used it in .net framework project do I need to remove this specific process of serialization or this will work there too?

**Comment by xinchen10** [comment]
On .net framework you only need a reference to the AmqpNetLite package. If you target .net 4.6.1 or above, you can reference the .net core packages (.Core and .Serialization) since .net 4.6.1 supports netstandard 2.0 (you may need to package the dependent corefx assemblies in this case though).
