### ISSUE TITLE
amqpnetlite as Azure Service Bus host / MSSBCBS sasl mechanism

### ISSUE THREAD

**Issue by ondrej2286** [Azure/amqpnetlite#352]
I was trying to setup amqpnetlite as a server to [Microsoft.Azure.ServiceBus](https://github.com/Azure/azure-service-bus). Followed the link [here](https://github.com/Azure/amqpnetlite/issues/176) so I could run some integration tests and managed to set it up. However, there were a few issues I ran across:

1. Had to register additional MSSBCBS sasl mechanism (same as EXTERNAL) in a hacky way to make it work with the Microsoft.Azure.ServiceBus package:
```csharp
        void EnableAzureMechanism(ConnectionListener.SaslSettings sasl)
        {
            sasl.EnableExternalMechanism = true;
            var mechanisms = (IDictionary)sasl
                .GetType()
                .GetField("mechanisms", BindingFlags.Instance | BindingFlags.NonPublic)
                .GetValue(sasl);
            mechanisms[(Symbol)"MSSBCBS"] = mechanisms[(Symbol)"EXTERNAL"];
        }
```
2. Found out that the Microsoft.Azure.ServiceBus package works only with [16-byte delivery tags](https://github.com/Azure/azure-service-bus-dotnet/blob/bf6acc9f25d69aadc9b5c328a0331329cd3bca6b/src/Microsoft.Azure.ServiceBus/Amqp/AmqpMessageConverter.cs#L339) (guids) and thus replies sent back to the client were never correctly finalised. I had to modify the following code in Delivery.cs file to make it work (and thus could not use the nuget package):
```csharp
        public static byte[] GetDeliveryTag(uint tag)
        {
            byte[] buffer = Guid.NewGuid().ToByteArray();  // new byte[FixedWidth.UInt];
            AmqpBitConverter.WriteInt(buffer, 0, (int)tag);
            return buffer;
        }
``` 

Would it be possible to update amqpnetlite to support the above mechanism and update delivery tag to support other sizes than `FixedWidth.UInt`?

**Comment by xinchen10** [comment]
1. We will enable custom SASL mechanisms on the listener code.
2. It makes sense but we will need some time to come up with the right API to expose it. Besides delivery tag there are other properties user may need to access to have more control on the protocol.

**Comment by xinchen10** [comment]
This scenario is now supported with the following changes,
1. custom SASL mechanism on listener.
2. ConnectionListener.HandlerFacgtory and IHandler to support customization of IDelivery on SendDelivery event.

**Comment by ondrej2286** [comment]
Excellent, thank you very much.

**Comment by nanan1993** [comment]
Hi, @cw-engineering . Following guides above, I built a service that could receive messages from service bus client. 
However, how could the server send message to clients? I failed a lot of times trying to send messages to the client with a ServiceBusTrigger or a handler registed by function Microsoft.Azure.ServiceBus.QueueClient.RegisterSessionHandler.
Could you tell me how you did to send messages to the Service Bus Client?

**Comment by roend83** [comment]
@nanan1993 did you ever get this working? I would love to see some sample code.
