### ISSUE TITLE
sender.send timeout when receiverAsync is used

### ISSUE THREAD

**Issue by GaikwadPratik** [Azure/amqpnetlite#354]
@xinchen10 ,

I was following [this example](https://github.com/Azure/amqpnetlite/blob/master/Examples/Interop/Interop.Client/Interop.Client.cs#L98) for sending and receiving messages over QPID C++ broker. 

from the server I am sending the message using `sender.sendAsync`. In the client if I use `receiver.receiveAsync` then on server side I get an exception of `Timeout` for `sendAsync`. However in client if I use `receiver.receive` then it works fine. 

Why am I getting timeout in server for asynchronous version of receive in client?

**Comment by GaikwadPratik** [comment]
@xinchen10 

Any insights?

**Comment by xinchen10** [comment]
Can you post the code? Also there are issues and articles about deadlock when sync and async APIs are used together. Check them out. It may be related.

**Comment by GaikwadPratik** [comment]
@xinchen10 

I went through article about deadlocks. I am not sure if its related to that.

The failure code is to replace [this line](https://github.com/GaikwadPratik/AmqpNetLiteRpc/blob/master/AmqpNetLiteRpcCore/RpcClient.cs#L101) in `RpcClient` with ```var _response = this._receiver.ReceiveAsync();``` and then [this line](https://github.com/GaikwadPratik/AmqpNetLiteRpc/blob/master/AmqpNetLiteRpcCore/RpcServer.cs#L144) in `RpcServer` fails with timeout. To make it work I had to go with _sych_ version.

**Comment by xinchen10** [comment]
ReceiveAsync returns a task. Do you wait on it to get the message? If not, how do you pass the task to the Accept call?

**Comment by GaikwadPratik** [comment]
@xinchen10 ,

yes, I did wait on the message. but it was failing so I went with _sync_ version for now. Since _sync_ version is working, please feel free to close this. I just wanted to point it out to you.
