### ISSUE TITLE
Self-Locking - lock(this) => bad practice?

### ISSUE THREAD

**Issue by motmot80** [Azure/amqpnetlite#357]
Hi,

I made a "mistake" and used an AmqpLink as an object to lock. 
That was causing a complex dead-lock issue in my application. 

The **reason** was: AmqpNetLite itself uses `lock(this) ` everywhere (AmqpObject, Links, Session ...).

I know it is bad practice to use everyone elses objects to lock **BUT** it's also bad practice to use `lock(this)`.

https://stackoverflow.com/questions/251391/why-is-lockthis-bad

Maybe you could change:

```
internal object ThisLock
{
    get { return this; }
}
```

to f.e.

```
private readonly object lockObject = new object();
internal object ThisLock
{
    get { return this.lockObject; }
}
```

so nobody else will fall in this trap.

Thanks for the great work and best regards
Thomas

**Comment by Havret** [comment]
@xinchen10  I think we can close it as #382 was merged.
