### ISSUE TITLE
Several unit tests fail on master

### ISSUE THREAD

**Issue by clemensv** [Azure/amqpnetlite#361]
Several unit tests fail on master

Results               Top Level Tests
-------               ---------------
Failed                Test.Amqp.ContainerHostTests.ContainerHostWebSocketWildCardAddressTest
Failed                Test.Amqp.LinkTests.TestMethod_AdvancedLinkFlowControl
Failed                Test.Amqp.LinkTests.TestMethod_CloseBusyReceiver
Failed                Test.Amqp.LinkTests.TestMethod_DynamicSenderLink
Failed                Test.Amqp.LinkTests.TestMethod_LinkCloseWithSettledSend
Failed                Test.Amqp.LinkTests.TestMethod_LinkReopen
Failed                Test.Amqp.LinkTests.TestMethod_ModifyMessage
Failed                Test.Amqp.LinkTests.TestMethod_ReceiveFromNonExistingNode
Failed                Test.Amqp.LinkTests.TestMethod_ReleaseMessage
Failed                Test.Amqp.LinkTests.TestMethod_SendAck
Failed                Test.Amqp.LinkTests.TestMethod_SendEmptyMessage
Failed                Test.Amqp.LinkTests.TestMethod_SendToNonExistingNode
Failed                Test.Amqp.LinkTests.TestMethod_SessionCreateClose
Failed                Test.Amqp.LinkTests.TestMethod_SynchronousSend
Failed                Test.Amqp.TaskTests.BasicSendReceiveAsync
Failed                Test.Amqp.TaskTests.ConcurrentLinkCreateClose
Failed                Test.Amqp.TaskTests.CustomMessgeBody
Failed                Test.Amqp.TaskTests.CustomTransportConfiguration

...

**Comment by xinchen10** [comment]
WebSocket test requires admin privilege at least once to register with prefix with http.sys. Link tests need an external broker as they can also be run for netmf, nano, and the old phone/store platforms. I can make them work without the external broker for .net and .net core so they can executed in VS.
