### ISSUE TITLE
Optimize allocations in types derived from DescribedList

### ISSUE THREAD

**Issue by szehetner** [Azure/amqpnetlite#369]
I found an optimization possibility but wanted to discuss it first before creating a PR.

All classes derived from DescribedList store their properties in the Fields object array. The properties accessors store/retrieve the values by indexing into this array and casting from/to the property type. Example: https://github.com/Azure/amqpnetlite/blob/master/src/Framing/Flow.cs

This causes a lot of allocations (above all boxing of value types) and the object-based list encoding/decoding is slower than it could be. As the layout of these types is anyway defined by the AMQP spec, all properties could be changed into normal properties. The encoding/decoding methods would then write/read these fields explicitly in the right order. The "Azure AMQP" library uses a similar pattern already (see https://github.com/Azure/azure-amqp/blob/master/src/Framing/Flow.cs), so there shouldn't be a reason to not use this here as well.

The advantages of this are:
- A *lot* less allocations. Currently for reading one "Received" instance the decoding needs the object[], a temporary List<object> for reading and one object for each boxed value type. 
As most of the members of these classes are value types (bool, uint,...), a lot of allocations could be saved. When profiling our system these boxed values show up as one of the main sources of allocations of all AmqpNetLite-related allocations.
- Faster encoding/decoding because there is no lookup necessary for the serialization methods (in Encoder.ReadObject() and Encoder.WriteObject())
- Faster access to the properties (no boxing/unboxing)
- Better memory layout of these instances (regular fields instead of pointers for every member)  
If there are no objections I can create a PR for this.

**Comment by Havret** [comment]
Sounds like a great idea. +1
