### ISSUE TITLE
Missing field index mapping/documentation

### ISSUE THREAD

**Issue by cjwmorgan-sol** [Azure/amqpnetlite#377]
The pull request #370 added new methods for resetting and checking Fields of DescribedList instances, _DescribedList.ResetField(int index)_ and _DescribedList.HasField(int index)_. These methods must take the hard-coded index value that match the sub type of DescribedList however the index are not made available through a public type or interface and are not documented in each sub type of DescribedList. This means developer must look at the amqpnetlite source code to determine the proper values to pass to _DescribedList.ResetField(int index)_ and _DescribedList.HasField(int index)_. 

I think either documenting the DescribedList sub type fields with indexes and/or enhancing the amqpnetlite api to provide the indexed constants per sub type would be a really good idea.

I'm basing this off of the commits in #370 if I'm missing something here for developers to use these new methods please let me know.

@xinchen10 what do you think?

**Comment by xinchen10** [comment]
The two methods were added for a case which is not common in my opinion. Most of the time, the properties should be used. We can add field index in the property doc to improve usability. I think that should be sufficient.

**Comment by cjwmorgan-sol** [comment]
Looks like commit 46676080fb6f153b4ed961cdb4419b1e7ed575c2 added the documentation for the new methods. Thanks @xinchen10!
