### ISSUE TITLE
Target netstandard 2.0

### ISSUE THREAD

**Issue by iron9light** [Azure/amqpnetlite#379]
Based on this doc: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting

+ DO start with including a netstandard2.0 target.

> Most general-purpose libraries should not need APIs outside of .NET Standard 2.0. .NET Standard 2.0 is supported by all modern platforms and is the recommended way to support multiple platforms with one target.

+ AVOID including a netstandard1.x target.

> .NET Standard 1.x is distributed as a granular set of NuGet packages, which creates a large package dependency graph and results in developers downloading a lot of packages when building. Modern .NET platforms, including .NET Framework 4.6.1, UWP and Xamarin, all support .NET Standard 2.0. You should only target .NET Standard 1.x if you specifically need to target an older platform.

There will be some conflict when a project depends on System.Runtime (>= 4.3.0) and this project.
The work around is add all netstandard 1.3's dependencies with newer version.

**Comment by xinchen10** [comment]
Which platform and version do you target? The AmqpNetLite.Core package has a netstandard2.0 target. Do you get conflicts if you use that one? The 1.3's dependencies haven't been updated to 4.3 yet. If we update it now it will need a major release.

**Comment by iron9light** [comment]
[AMQPNetLite.Core@2.1.8](https://www.nuget.org/packages/AMQPNetLite.Core/2.1.8)
I think it's the latest published version and it seems it only targets .NETStandard 1.3

**Comment by xinchen10** [comment]
netstandard2.0 target was added in 2.2.0 release. Please try it to see if the dependency issue is resolved.

**Comment by iron9light** [comment]
I've updated the dependency version and, yes, it solved my problem perfectly. Thx @xinchen10 .
