### ISSUE TITLE
SenderLink leaks memory when a timeout sending a message occurs

### ISSUE THREAD

**Issue by robreeves** [Azure/amqpnetlite#38]
There is a memory leak when a timeout occurs calling SenderLink.Send. I am sending messages that will timeout at roughly a constant interval. Several objects appear to grow linearly with time. If the message sends successfully without a timeout no leak occurs. Here are the object types that are leaking.

Microsoft.Win32.SafeHandles.SafeWaitHandle
ManualResetEvent
Amqp.Message
Amqp.Framing.AmqpValue
Amqp.SenderLink+<>c__DisplayClass3
Amqp.OutcomeCallback
Amqp.Delivery
Amqp.ByteBuffer

The problem is the delivery object gets added to the outgoingList in SenderLink, but never gets removed when a timeout occurs.

Here is my test client.

    class Program
    {
        static void Main(string[] args)
        {
            var address = "amqp://guest:guest@127.0.0.1:5672";
            var conn = new Connection(new Address(address));
            var sess = new Session(conn);
            var link = new SenderLink(sess, "test-client", "msg-queue");

            while (true)
            {
                try
                {
                    link.Send(new Message("hi"), 10);
                }
                catch (TimeoutException)
                {
                }
            }
        }
    }
    
And here is my test server.

    class Program
    {
        static void Main(string[] args)
        {
            var address = new Uri("amqp://guest:guest@127.0.0.1:5672");
            var host = new ContainerHost(new List<Uri>() { address }, null, address.UserInfo);
            host.RegisterMessageProcessor("msg-queue", new MsgProcessor());
            host.Open();

            Console.WriteLine("ready");
            Console.Read();
        }
    }

    class MsgProcessor : IMessageProcessor
    {
        public int Credit
        {
            get { return 1; }
        }

        public void Process(MessageContext messageContext)
        {
            Thread.Sleep(20);
            messageContext.Complete();
        }
    }

Here are my findings. All object counts grow at the same rate.

![amqp_timeout_leak](https://cloud.githubusercontent.com/assets/5604993/10373137/5ea05fca-6da0-11e5-826f-954508aabeef.PNG)

**Comment by rr118** [comment]
@xinchen10 I ran my test again and can confirm that commit https://github.com/Azure/amqpnetlite/commit/c0a0dfe4b5172f700bb2e10cc4654ae77dfe5c14 resolves the issue. Thanks for the quick fix!

**Comment by xinchen10** [comment]
Thanks for verifying the fix.
