### ISSUE TITLE
Support ReceiverLink.ReceiveNoWait()

### ISSUE THREAD

**Issue by tyamashi-oss** [Azure/amqpnetlite#383]
- Support ReceiverLink.ReceiveNoWait(). This method receives a message if one is immediately available, or null if one is not available.
- amqpnetlite provides only ReceiverLink.Receive(timeout). if there is no timeout parameter, this method wait 60 seconds until receiving a message as default.
- JMS(Java Message Service) API provides MessageConsumer.ReceiveNoWait().

- By the  way, if use ReceiverLink.Receive() with small time out value, such as 1 millisecond, the client will be disconnected by Apache artemis server.

**Comment by michaelandrepearce** [comment]
two bits, the apache project is about to release an NMS AMQP client (wrapping around amqpnetlite) as such if you want JMS like api and behaviours go have a look, its about to go for release.

For the specific feature, you may want to look how this is implemented there (which is roughly inline with how the qpid jms one works)
https://github.com/apache/activemq-nms-amqp/blob/master/src/NMS.AMQP/NmsMessageConsumer.cs
