### ISSUE TITLE
Expose IsDetaching on SenderLink

### ISSUE THREAD

**Issue by Havret** [Azure/amqpnetlite#387]
In nms amqp we would like to determine upfront if SenderLink is going to throw an exception on Send. To do so we would like to expose:

https://github.com/Azure/amqpnetlite/blob/4ad528de1654861065ba9d553dc962251047fd4b/src/Link.cs#L103-L106

as public property. 

@xinchen10 What do you think? Is this a good approach or should we think about sth else? 

Currently as a temporary workaround I'm just making a check if Link.Error != null.

**Comment by xinchen10** [comment]
We can expose LinkState and similarly the state of connection and session.

**Comment by Havret** [comment]
@xinchen10 Sounds good to me. I will submit PR.
