### ISSUE TITLE
Add option to set context on amqp object

### ISSUE THREAD

**Issue by Havret** [Azure/amqpnetlite#389]
As we have adapted handler model from proton clients, I think it might be a good idea to make another step forward and add option to set context on amqp objects the same way it is possible with proton endpoints:
https://github.com/apache/qpid-proton-j/blob/ab8e98b0ab18114bfaa2f78f548672cff311522f/proton-j/src/main/java/org/apache/qpid/proton/engine/Endpoint.java#L69-L78

The context is heavily used alongside with handler api in qpid-jms client and we would like to leverage it the same way in nms-amqp. 

@xinchen10 What do you think? Can I submit PR?

**Comment by xinchen10** [comment]
`IHandler` is already a custom implementation at the connection level. The context is only useful for session and link. Do you have scenarios where it is needed?
