### ISSUE TITLE
Forcefully close a client connection

### ISSUE THREAD

**Issue by rr118** [Azure/amqpnetlite#4]
Here is the use case I have in mind. One application is acting as the broker or server using Amqp.Listener.ContainerHost. Another application is acting as the client using an Amqp.Connection (or a different AMQP client library). The client must authenticate with any SASL authentication mechanism (i.e. plain or external). The client authenticates successfully and starts sending messages. At some point down the road the server needs to revoke the permissions from the client (i.e. client is sending malicious data, is stale, no longer is allowed to send data to this server, etc). At this point the server needs to force the client connection to close. This should close the connection and clean up the links associated with the connection.

**Comment by xinchen10** [comment]
Fixed https://github.com/Azure/amqpnetlite/commit/30249ad33e50357e9eee2e11a10b2001d445f4d3

Made Link.Session and Session.Connection public so user can access them from the link object and control their lifetime based on user's requirement.
