### ISSUE TITLE
This repo needs a LICENSE.TXT file

### ISSUE THREAD

**Issue by jeffwilcox** [Azure/amqpnetlite#40]
Hi,
This repo needs to have licensing information.

Thanks!

**Comment by xinchen10** [comment]
Do you mean this file?
https://github.com/Azure/amqpnetlite/blob/master/license.txt

**Comment by jeffwilcox** [comment]
Ah, our system for checking is case sensitive, I'll fix that. Many projects have a `LICENSE.TXT` file. No worries - appreciate the quick response!
