### ISSUE TITLE
Question about send method ack

### ISSUE THREAD

**Issue by vasicvuk** [Azure/amqpnetlite#401]
Hi everyone,

I wanted to know when using **SenderLink** Send method like this `sender.Send(messageAmqp, null, null)` is AMQP Lite waiting for a request to be processed by the server and just do not wait for Receiver acknowledgment or it is not waiting for anything and just sends request asynchronously.

I am testing with the ActiveMQ Artemis cluster and I have messages Send without exception from code but not received by any of Subscribers (topic is durable). I want to be sure that the problem is the Server, not the client code. This happens when Master crashes immediately after sending the message. 

I also tried to pass **OutcomeCallback** doing nothing but I got the same behavior since I read that it will deliver the message with BestEffort without it but I am not sure that I understood this correctly.

In Artemis documentation, I found that every request to master is synchronized with the slave before sending confirmation to the client, but I am not sure if the client is waiting for that confirmation at all.

Thanks in advance

**Comment by xinchen10** [comment]
The send methods are explained here.
https://github.com/Azure/amqpnetlite/blob/master/docs/articles/building_application.md#sending-messages

**Comment by vasicvuk** [comment]
Hi @xinchen10,

I already read text from this link, but as asked in question i don't understand if acknowledgment mentioned in text is acknowledgment that someone received the message (consumer) or that server received the message for forwarding to consumers.

Also, when I have OutcomeCallback still message is lost so I am not sure what is the difference.

**Comment by xinchen10** [comment]
Acknowledgement is a disposition from the remote link endpoint. Most, if not all, brokers send the ack once a message is accepted. You could also have a listener that sends acks once the messages are processed by a subscriber. For the library this is implementation detail of the remote container.

The send method you are using is **not blocking**. If you do not provide a callback, the message is sent pre-settled (no ack is required). If you do provide a callback, it is invoked when the ack comes with the outcome. In this case you need to keep the app running before the ack comes.

**Comment by vasicvuk** [comment]
@xinchen10  Thanks for the explanation. I also tried blocking **Send** method that is waiting for ACK synchronously but still, I have the same behavior so I assume that this is a server error since it is receiving the ACK but the message is never delivered to any of consumers.
