### ISSUE TITLE
Release 2.4.0 doesn't contain any changes

### ISSUE THREAD

**Issue by Havret** [Azure/amqpnetlite#409]
Hi, strange thing, I've just pulled the new version of the library from nuget but I don't see my changes  from #399 either from #398. Is it possible that the wrong artifacts were released?

**Comment by xinchen10** [comment]
Can you check again? I downloaded the 2.4.0 package and it looks fine. The tcp keep alive change is available only in the netstandard2.0 file.

**Comment by xinchen10** [comment]
I couldn't repro this with Visual Studio 2017 and netcoreapp2.1. In Visual Studio if you select any type from the library and press F12, it should give you the code from metadata. What about the assembly info? This is mine.
```
#region Assembly Amqp.Net, Version=2.1.0.0, Culture=neutral, PublicKeyToken=905a7b1e6458e0c3
// C:\Users\xinchen\.nuget\packages\amqpnetlite.core\2.4.0\lib\netstandard2.0\Amqp.Net.dll
#endregion
```

**Comment by Havret** [comment]
My assembly info looks the same to me:

```
#region Assembly Amqp.Net, Version=2.1.0.0, Culture=neutral, PublicKeyToken=905a7b1e6458e0c3
// C:\Users\havre\.nuget\packages\amqpnetlite.core\2.4.0\lib\netstandard2.0\Amqp.Net.dll
#endregion
```

But if I open ContainerHost in VS 2019, it doesn't look up to date. 

```

**Comment by xinchen10** [comment]
yes, I have the following code (netcoreapp2.1) that works just fine.
```
    class Program
    {
        static void Main(string[] args)
        {
            Address a = new Address("amqp://localhost:5672");
            var host = new ContainerHost(a);
            host.Open();
            Console.ReadLine();
        }
    }
```

**Comment by Havret** [comment]
Ok, so it seems I've got sth broken with the nuget on my machine. It compiled just fine in my CI pipeline. 

https://github.com/Havret/ActiveMQ.Net/pull/68/checks?check_run_id=560693135

Closing, then.
