### ISSUE TITLE
Maximum number of concurrent messages processed by broker

### ISSUE THREAD

**Issue by robreeves** [Azure/amqpnetlite#41]
Is there a way to limit the number of messages being processed concurrently on the broker? Here is my use case. I am using a ConnectionListener for my broker. There are many clients each creating a SenderLink, which creates a ReceiverLink on the broker side. In most cases they send messages at a slow enough rate where all messages can be handled in a timely manner. However let’s say the broker becomes unavailable and each client buffers data. When the broker becomes available they all send messages at one time. The broker will create a new thread for each incoming messages. I have seen that 100 clients (100 SenderLinks from 100 independent connections) will use about 100 threads to receive messages on the broker (I counted in a memory dump) when each SenderLink is sending messages as fast as they can to catch up.  

I was thinking of keeping track of the number of messages being processed in IMessageProcessor.Process and returning error “amqp:resource-limit-exceeded” when it exceeds a threshold to minimize the problem. However this doesn't stop the messages from being sent over the network (1MB each) or AMQP.NET Lite from doing the work to receive and decode the messages. It would be nice to stop the incoming message as soon as possible to avoid this expensive work.

I can limit the number of messages per ReceiverLink using the credit, but even at a credit of 1 if I have a lot of ReceiverLinks this can still result in many threads handling incoming messages from each ReceiverLink. 

Since each client creates its own connection and session I could limit the total number of connected clients by using AmqpSettings.MaxSessionsPerConnection. However I don’t want to limit the number of connections just how many messages can be processed at once time. 

Thanks for the help.

**Comment by ChugR** [comment]
You are trying to assert some kind of flow control from you server end when the clients might overwhelm you. A mechanism built in to AMQP to help with this is the Flow performative's 'drain' flag.

Suppose you have 100 clients and you only want 20 incoming messages at a time. 
* Start them all off with zero credits: **receiver.SetCredit(0);**
No client sends messages.
* For the first 20 clients send a Flow with **credit=1, drain=true**.
Each clients is supposed to send enough messages to consume its outstanding credit, one message in this case, or if it has no messages to send then it updates its flow state with the delivery count advanced to consume all available credit. This lets each client send one message or come right back with a Link OnFlow event saying that it has no messages. Either way if the client has more messages in its queue or generates its next message right away it will not send any more until you issue some credit.
* As messages and OnFlow events arrive you send Flow with credit=1, drain=true to the next client in turn.

**Comment by xinchen10** [comment]
It is not an easy problem to solve. As ChugR mentioned, the server can use the drain mechanism to distribute limited credits to clients. However, without client's cooperation, the server now needs to "drain" clients constantly in case some of them have messages to send. It may be fine if clients always have messages to send, but if there are 1000 links and most of them are idle, the server will end up sending and receiving flows most of the time. If you have control of the clients, you can set flow with available field set on the client to request credits from the server. However, the library does not give you control at such low level right now.

The message processor API is designed such that credits are not sent to client until MessageContext.Complete is called. By controlling how fast you complete the message context objects, you are actually controlling how fast clients can send messages. For example, if you want to have a max 20 messages being processed at the server, you can delay completing the message context until the concurrent request count is below 20. If you also want to control the initial messages after link is attached, you would need to implement ILinkProcessor on the listener side and add AttachContext processing to the flow controlling logic.

The listener API is designed to give different levels of flexibility/control to the user.
1. IMessageProcessor: the easiest way to process messages but no control of links.
2. ILinkProcessor: user needs to manage attach request and link events (transfer, flow and disposition) which gives more control to the protocol.
3. IContainer: user has full control of the protocol but needs to manage everything.

It should not be difficult to use a Semaphore to control the max allowed concurrent requests (AttachContext and MessageContext).

**Comment by robreeves** [comment]
@xinchen10 Thanks, Xin. The flow control feature and example look like they should give us the control we need. I'll play around with it, but I think those changes and suggestions are sufficient to close the issue. I can open a new issue if I have specific questions.

@ChugR Thanks for the suggestions. I have not had time to fully prototype them. It taught me something new about AMQP. I will likely think about variations that do not require as much back and forth communication when the client has no messages to send.
