### ISSUE TITLE
ScheduledMessage sequence-number for cancellation

### ISSUE THREAD

**Issue by OlegOLK** [Azure/amqpnetlite#410]
Hello. I am using the latest version of amqpnetlite = 2.4.0 

Question is the next: I have pushed a new scheduled message to the queue. And according to the documentation [schedule message](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/service-bus-messaging/service-bus-amqp-request-response.md#schedule-message) I need to receive back sequence number of sended message in order to remove message [cancel scheduled message](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/service-bus-messaging/service-bus-amqp-request-response.md#cancel-scheduled-message).
But I cannot find any possible ways to do that. 
Is it possible at all in the current version of amqpnetlite?

**Comment by xinchen10** [comment]
According to the doc, the sequence number is returned in the message body (an AMQP value containing a map object). Is the issue about not getting the body or you couldn't find a way to read the body. If the body is present, you should be able to access it from the response message object.
