### ISSUE TITLE
How to identify the topic on which message is received, if wildcard subscription is used?

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/amqpnetlite#411]
I used below code to subscribe to IBM MQ wildcard topic `test/#`. I am able to receive the message. But, I am not sure if the message is received on `test/a` or `test/b`. Which field in Amqp.Message should be used to identify the same?

```csharp
using System;
using System.Threading.Tasks;
using Amqp;
using Amqp.Sasl;

namespace example
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var connection = new Connection(new Address("localhost:5672"), SaslProfile.Anonymous, null, null);
            var session = new Session(connection);
            var recvLink = new ReceiverLink(session, "recv-link", "test/#");
            var message = await recvLink.ReceiveAsync();
            Console.WriteLine($"Message: {message.Body}");
        }
    }
}

```

<sub>Kindly guide if this query should go to stackoverflow or similar communities. </sub>

**Comment by xinchen10** [comment]
This is not defined in AMQP. It is IBM MQ specific. Have you inspected the message object under debugger to see if any properties might be telling that?

**Comment by kiranpradeep** [comment]
Thanks @xinchen10. Closing.
