### ISSUE TITLE
UWP Application become unresponsive when trying to connect to host

### ISSUE THREAD

**Issue by rua26x** [Azure/amqpnetlite#416]
i am trying to build uwp application using ActiveMQ, but when the app trying to connect to the server host the app become unresponsive
i receive this error from server
AMQ224088: Timeout (10 seconds) on acceptor "amqp" during protocol handshake with /0:0:0:0:0:0:0:1:64562 has occurred.
can anyone help me with the issue?

**Comment by xinchen10** [comment]
How did you create the connection? Trying calling one of the `CreateAsync` methods from `ConnectionFactory` and await on the task to create a connection. The connection constructors have blocking I/O calls. If you call it from the UI thread, it may cause deadlocks due to synchronization context.
