### ISSUE TITLE
Integration with Azure Managed Identities

### ISSUE THREAD

**Issue by ymorozov** [Azure/amqpnetlite#423]
We use AmqpNetLite library to send and receive messages to/from Azure Service Bus using user/password credentials. We have requirement to support Azure Managed Identities. Is it possible to do with AmqpNetLite?

**Comment by xinchen10** [comment]
It is possible. The OAuth2 token is sent to the service through the CBS put-token call. The Service Bus CBS example shows how to send tokens. This [example](https://github.com/Azure/azure-service-bus/blob/master/samples/DotNet/Microsoft.ServiceBus.Messaging/RoleBasedAccessControl/Program.cs) shows different options for getting the OAuth2 token.
