### ISSUE TITLE
Error: The format code '111' at frame buffer offset '47' is invalid

### ISSUE THREAD

**Issue by tereshechkin** [Azure/amqpnetlite#424]
From RabbitMq the message is sent:

type:	amqp-1.0
message_id:	000001615000000000000000151974
delivery_mode:	2

headers:	
x-amqp-1.0-properties:	Not UTF-8, base64 is: AFNz0AAAADEAAAAIoR4wMDAwMDE2MTUwMDAwMDAwMDAwMDAwMDAxNTE5NzRAQEBAQECjBVVURi04
content_encoding:	UTF-8

Body: Test

But on recieve it returns the error: The format code '111' at frame buffer offset '47' is invalid

**Comment by xinchen10** [comment]
@tereshechkin do you have the exception callstack? To debug this issue we will need to get the message payload received by the library, but currently there is no easy way to get that using this library directly. I will add an option in the logger to output raw bytes sent/received over a connection.

**Comment by xinchen10** [comment]
Please following the [tracing doc](https://github.com/Azure/amqpnetlite/blob/master/docs/articles/tracing.md) and set the level to Buffer and share the output. The bytes from the SASL handshake may contain your credentials, so you can either remove them before posting or use something that doesn't matter.

**Comment by xinchen10** [comment]
Please reopen the issue when you have the log available for debugging.
