### ISSUE TITLE
"Ticks must be between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks.\r\nParameter name: ticks"

### ISSUE THREAD

**Issue by hendem** [Azure/amqpnetlite#425]
When try to receive message I get the following error message
{amqp:internal-error}
"Ticks must be between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks.\r\nParameter name: ticks"

**Comment by johnnybegood** [comment]
Hi,

we started receiving the same error on production, connected to Azure Service Bus. Is there a way to resolve this without upgrading and redeploying?

**Comment by johnnybegood** [comment]
> Hi,
> 
> we started receiving the same error on production, connected to Azure Service Bus. Is there a way to resolve this without upgrading and redeploying?

I followed the suggestion on https://github.com/Azure/amqpnetlite/issues/295#issuecomment-430681648 to add a message expiration and the processing started again. On our quality system the message expiration is still unbounded and processing is working.

**Comment by akshaym-dev** [comment]
Hi,
I am still facing this issue with .net core 3.1 project with AMQPNetLite.Core 2.4.0 lib. I am able to receive message using same code in .net framework project and lib. 

I have tried to add TTL(time to live) to my message header. Also added Absolute expiration in message properties. 
While receiving I have added timeout timespan. Still getting the same error. Any thoughts? 

             //sender code
             msg.Header = new Header() { Ttl = 1000000 };
             msg.Properties = new Properties() { GroupId = sessionId, AbsoluteExpiryTime = DateTime.UtcNow.AddMinutes(60) };
             sender.Send(msg);

           //receiver code 
           Message message = receiver.Receive(TimeSpan.FromSeconds(4));

**Comment by xinchen10** [comment]
@akshaym-dev can you try version 2.4.1 and share the Buffer level logs? You can do Frame level first and then Buffer level and share just the buffer for the transfer frame. The SASL buffers may contain your credentials so don't share them here.

Instructions for enabling logging is here: https://github.com/Azure/amqpnetlite/blob/master/docs/articles/tracing.md

**Comment by akshaym-dev** [comment]
@xinchen10.. Thanks a lot for your response. updating to 2.4.1 resolved that issue.
