### ISSUE TITLE
[Question] Is it possible to connect to partitioned topic in Azure Service Bus with AMQP.Net Lite library?

### ISSUE THREAD

**Issue by yansklyarenko** [Azure/amqpnetlite#427]
My client .NET Core application uses AMQP.Net Lite library to work with Azure Service Bus. When the topic in the service bus namespace is NOT partitioned (`Enable Partitioning` is turned *OFF*), everything works fine - I'm able to connect and create `ReceiverLink` object to receive messages.

However, as soon as the topic is partitioned (`Enable Partitioning` is turned **ON**), I get the following error immediately after `ReceiverLink` object creation. 
The error description is: "*Cannot open a Topic client for entity type Subscriber.*"

The error code translates to the AMQP map as `amqp:not-allowed`. According to [the docs][2], it means "*The peer tried to use a frame in a manner that is inconsistent with the semantics defined in the specification.*" To be honest, I can hardly understand what it means in terms of Azure Service Bus abstractions, but it sounds depressing and similar to "*not possible*" to me...

On the other hand, [the MS docs state][3] that AMQP can be used to send and receive messages:
> AMQP is now supported for sending and receiving messages to and from a **partitioned** entity.

So, the question is whether it is at all possible to use AMQP.NET Lite library to receive messages from a partitioned topic in Azure Service Bus?

  [2]: https://azure.github.io/amqpnetlite/api/Amqp.ErrorCode.html#Amqp_ErrorCode_NotAllowed
  [3]: https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-partitioning#latest-added-features

**Comment by xinchen10** [comment]
Sounds like a bug in ASB. Partitioned entity should behave the same as non-partitioned entity. Can you post the line where the receiver link is created?

**Comment by yansklyarenko** [comment]
Basically, this is it:

`connection.CreateSession().CreateReceiver(settings.LinkName, settings.Address)`

The `settings.LinkName` and `settings.Address` contain perfectly valid values, verified with non-partitioned topic.
The connection itself is an `IConnection`, created like this:

`await _connectionFactory.CreateAsync(address).ConfigureAwait(false);`

The `address` is an instance of `Amqp.Address` class, again composed out of valid settings taken from the configuration.

**Comment by yansklyarenko** [comment]
@xinchen10 I posted the same question on StackOverflow, and @pranavq212 made an interesting note, that MS has just published the info about Amqp support last month, while Amqp.Net Lite library has its most recent release earlier. Could it be the case that the library just does not comply with the latest changes in ASB?

**Comment by xinchen10** [comment]
It should not be the case. ASB supports standard AMQP. It's probably something missing in handling partitioned topics.

Let's assume your topic is named "t1" and has a subscription named "s1". There are two ways to create a receiver link.
1. address topic directly and use the subscription name as the link name.
```
var r = new ReceiverLink(s, "s1", "t1");
```
2. address subscription and use anything for link name.
```
var r = new ReceiverLink(s, "receiver", "t1/Subscriptions/s1");
```

Both ways work with regular topic but the first doesn't work with partitioned topic (the second works though). It is a bug in ASB when a topic is partitioned.

**Comment by yansklyarenko** [comment]
@xinchen10 Thanks a lot for the explanation! I've verified the second approach, and it DOES work for the partitioned topic! This workaround perfectly fits my solution, so I'm closing the issue. 

Thanks again for your support!

**Comment by yansklyarenko** [comment]
@xinchen10 it might sound weird, but it seems that both ways of creating a `ReceiverLink` started to work for both regular and partitioned topics... Could it be that some fixes were silently rolled out to the Azure subscription?

I failed to find any release notes and I hate to disturb you on this matter again, @xinchen10, but as long as you managed to reproduce the initial problem and if you still have that test code around, could you be so kind to verify the scenario again? I would appreciate some evidence I'm not going insane... :-)
