### ISSUE TITLE
how to send "Type" ?

### ISSUE THREAD

**Issue by eagle275** [Azure/amqpnetlite#428]
I am tasked with writing .Net application using amqpnetlite to interact with a cloud version of activeMQ - But the target system will validate what I send. And it fails as "invalid" because now all header fields are set 
With some twiddling I managed to find most necessary header / properties / messageAnnotations and applicationproperties  but ONE ...
Its listed in activeMQ in the message display as "Type" - according to activeMQ documentation its JMSType containing string-data.
It's not ApplicationProperties["type"] ... which will display a second "Type" field, but under properties in the message display 

Now my simple question is - what do I need to set to modify said "Type" field in the "header-list" ?

**Comment by xinchen10** [comment]
This is something beyond the scope of AMQP. Are you using JMS? This doc might help you.
https://www.oasis-open.org/committees/download.php/60251/amqp-bindmap-jms-v1.0-wd08.pdf

JMSType should be message properties.subject.
