### ISSUE TITLE
Problem when accessing AMQP on Amazon MQ

### ISSUE THREAD

**Issue by torsannes** [Azure/amqpnetlite#430]
I have a problem connecting to Amazon MQ since the url has a scheme like **amqp+ssl** instead of the normal **amqps**.
Does anyone know if it is possible to change the scheme in Amazon MQ?

I also made a simple test with just limited code changes:
- By changing the amqps scheme to amqp+ssl it worked.
- The same thing if I changed the internal logic within amqpnetlite to say that all schemes that starts with amqp other than amqp, is amqps.

**Comment by xinchen10** [comment]
I think "amqp+ssl" is the Amazon MQ way of saying amqp over SSL, which is the same as amqps implemented in the library. The scheme is not sent over the wire and checked by both sides. Did you try using the amqps schemed address to connect to Amazon MQ? Did it not work?

**Comment by torsannes** [comment]
Thank you - that fixed my problem 👍 
Using amqps instead of amqp+ssl in the url worked perfectly 😊
