### ISSUE TITLE
Problem receiving "Cloud-to-device" message on ESP32 device running nanoframework and amqpnetlite.

### ISSUE THREAD

**Issue by RGSholmesr** [Azure/amqpnetlite#433]
Hi,

I am quite new to the nanoframework and the amqp protocol, so I suspect I am doing something wrong, but I have been looking at this issue for a while and I'm getting nowhere! :¬( 

My environment is C# and .netNanoFramework (latest preRelease), running on an ESP32 IOT Azure Devkit flashed with the latest image of nanoframework from nuGet.

I am using the sample amqp app (ampq.samples) and I've managed to get the device to connect and send messages to the cloud, which is great! I am using the Azure IoT Explorer app to set up the device and then monitor the messages using the "Telemetry" option. When I press the required button on the board, the message appears in Azure IoT Explorer. 8¬D

However, when I try to send a message from Azure to the device (using Azure IoT Explorer) I get the following error;

RECV (ch=0) transfer(handle:1,delivery-id:0,delivery-tag:CB9E8677226B8043836D8C27AA7CCF1C,message-format:0,settled:False,more:False,rcv-settle-mode:0,resume:False,aborted:False,batchable:False) payload 224
    ++++ Exception System.ArgumentOutOfRangeException - 0x00000000 (4) ++++
    ++++ Message: 
    ++++ System.DateTime::.ctor [IP: 001b] ++++
    ++++ System.DateTime::.ctor [IP: 0005] ++++
    ++++ Amqp.Types.Encoder::TimestampToDateTime [IP: 0016] ++++
    ++++ Amqp.Types.Encoder::ReadTimestamp [IP: 000f] ++++
    ++++ Amqp.Types.Encoder+<>c::<Initialize>b__8_27 [IP: 0005] ++++
    ++++ Amqp.Types.Encoder::ReadObject [IP: 0011] ++++
    ++++ Amqp.Types.Encoder::ReadObject [IP: 000a] ++++
    ++++ Amqp.Types.Encoder::ReadMap [IP: 0054] ++++
    ++++ Amqp.Types.DescribedMap::DecodeValue [IP: 0009] ++++
    ++++ Amqp.Types.Encoder::ReadDescribed [IP: 0036] ++++
    ++++ Amqp.Framing.Codec::Decode [IP: 0008] ++++
    ++++ Amqp.Message::Decode [IP: 000b] ++++
    ++++ Amqp.ReceiverLink::OnTransfer [IP: 0056] ++++
    ++++ Amqp.Session::OnTransfer [IP: 00c2] ++++
    ++++ Amqp.Session::OnCommand [IP: 0060] ++++
    ++++ Amqp.Connection::OnSessionCommand [IP: 000e] ++++
    ++++ Amqp.Connection::OnFrame [IP: 00bb] ++++
    ++++ Amqp.Connection+Pump::PumpThread [IP: 003e] ++++
Exception occurred: System.ArgumentOutOfRangeException: Exception was thrown: System.ArgumentOutOfRangeException
SEND (ch=0) close(error:error(condition:amqp:internal-error,description:Exception was thrown: System.ArgumentOutOfRangeException))

The message I tried to send was very simple, it just read "Test" and included a timestamp (which is an option in Azure IoT Explorer).

Does anyone have any suggestions as to what I might be doing wrong here?

Many thanks in advance.

R.

**Comment by xinchen10** [comment]
It seems that the cloud-to-device message has a timestamp value in the message annotations or application properties. It is causing the message decoding error on the device. In AMQP the timestamp is encoded as Unix epoch but with a precision of milliseconds. I think the library has a bug in decoding the value on the nanoframework.

**Comment by RGSholmesr** [comment]
Thanks @xinchen10 - sounds like nothing I can fix / work around!? - I guess I need to await an update?

**Comment by josesimoes** [comment]
Fixed with #435
