### ISSUE TITLE
Potential bug

### ISSUE THREAD

**Issue by jasonholloway** [Azure/amqpnetlite#436]
Hi, I've been hacking about in the codebase, and have come across the below, which is surely a bug:

https://github.com/Azure/amqpnetlite/blob/975ef84c82af63fa45548843c3f1a06e48a19af3/src/Listener/ContainerHost.cs#L591-L595

Presumably that should be an `&&`?

**Comment by xinchen10** [comment]
Yes, you are absolutely correct. It's a bug.
