### ISSUE TITLE
Cannot allocate more handles

### ISSUE THREAD

**Issue by kennethmyhra** [Azure/amqpnetlite#440]
We are getting the error 'Cannot allocate more handles. The maximum number of handles is 256'. Is there something we can do to increase the number of handles above 256?

If you could shed some light on what we might be doing wrong which makes us hit this ceiling, that would be very much appreciated

**Comment by xinchen10** [comment]
Can you try the following?
```
    ConnectionFactory factory = new ConnectionFactory();
    factory.AMQP.MaxSessionsPerConnection = 5000;
    factory.AMQP.MaxLinksPerSession = 5000;
    Connection connection = await factory.CreateAsync(address);
```

**Comment by kennethmyhra** [comment]
Thanks for the reply @xinchen10. We will try this out, and I think we can close this.

**Comment by jbertram** [comment]
Is there any way to set these via a URL parameter?
