### ISSUE TITLE
Windows Embedded Compact support

### ISSUE THREAD

**Issue by stoyanj** [Azure/amqpnetlite#441]
Hello,

I got following error on windows embedded compact:

{
System.MissingMethodException:
    Method not found: xOf rlib, Version=3.9.0.0, Culture=neutral, PublicKeyToken=969DB8053D3322AC.System.Array.
    at amqpnetlite.Program.Main(String[] args)
}	System.Exception {System.MissingMethodException}

caused by very simple code:
client.Connect(client.HostName, 443, true, deviceId, accessKey);

Any idea?

**Comment by xinchen10** [comment]
Which version is it? Compact Framework is supported only in 1.x.
Client.Connect method is from the NETMFMicro package which is for .Net Micro Framework. How did you get it into your windows embedded project?

**Comment by stoyanj** [comment]
Hello,

Thank you very much for coming back!
Sorry I am not sure what do you mean?
I am using nanoFramework.System.Net.1.6.1

and I can see that the root of the issues is 
Socket socket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);

it throws the missing method exception.
My device is Windows Embedded Compact 2013 .Net compact 3.9

I can send you sample project if needed?

Best regards:
Stoyan

**Comment by xinchen10** [comment]
I am not sure how nanoFramework is supposed to do with Windows Embedded Compact 2013 .Net compact 3.9. My understanding is that they are different. @josesimoes may be able to share more information.

For Windows Embedded .Net compact 3.9, you need the net-cf target from https://www.nuget.org/packages/AMQPNetLite/1.2.3. It is no longer available in later versions.

**Comment by josesimoes** [comment]
That is correct, of course. . NET nanoFramework assemblies can't be used in Windows Embedded Compact. This has already been explained to @stoyanj on Stackoverflow.
