### ISSUE TITLE
exception calling ReceiverLink.Receive() on session enabled queue from service bus in ASP.NET core

### ISSUE THREAD

**Issue by akshaym-dev** [Azure/amqpnetlite#442]
When try to receive message I get the following error message
{amqp:internal-error}
"Ticks must be between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks.\r\nParameter name: ticks"

ASPNet core 3.1
AMQPNetLite.Core 2.4.0

**Comment by xinchen10** [comment]
Should be fixed in 2.4.1.
