### ISSUE TITLE
ReceiverLink settlement true/false in Disposition Frame

### ISSUE THREAD

**Issue by andyyeh-maersk** [Azure/amqpnetlite#443]
It seems the ReceiverLink only ever sends settlement=false whenever a transaction is involved.  Otherwise, reject/release/modify on the ReceiverLink always sends settlement=true with corresponding state in the Disposition frame.  Is there or should there be a way to set the settlement attribute on the Disposition frame to false to indicate that the message has not been processed successfully by the client and the message needs to be re-delivered by the broker?

**Comment by xinchen10** [comment]
Settlement is for tracking the delivery state of a message. When it is true, it simply means that both sides should forget about the delivery state of the message. Depending on the outcome, the message can be deleted, archived or made available for redelivery. For example, if you cannot process a message, you can release it, or modify it to have more control of the redelivery.

**Comment by andyyeh-maersk** [comment]
I think there are brokers that require that the settled attribute is set to false explicitly in order to achieve the desired behavior.  E.g. from IBM MQ documentation:

> If you are using a different AMQP client, set the settled attribute of the transfer frame (for publishers), **or the disposition frame (for subscribers) to true or false, depending on the quality of service you want to achieve.**"

> 

Shouldn't the library allow the possibility for the clients to set this in the process of releasing, rejecting, modifying the message to allow the client to satisfy the requirements set by the broker?

**Comment by xinchen10** [comment]
That's true but it shouldn't affect message redelivery.

If the client needs to get the outcome of a disposition update from the broker, it has to set settled to false when sending the disposition. This will be supported later. Take a look at this issue #408.
