### ISSUE TITLE
Advertised idle timeout should be divided by 2

### ISSUE THREAD

**Issue by serbrech** [Azure/amqpnetlite#444]
I've been discussing this on the `go-amqp` implementation here : https://github.com/Azure/go-amqp/issues/16#issuecomment-769548134

- idle timeout are exchanged by peers during connections
- each client is responsible to respect its peer's timeout by emitting empty frames as hearbeat, if no other message is emitted.

It seems the amqnetlite, (as well as go-amqp) chose to implement the spec by emitting a heartbeat at half the timeout threshold advertised by the remote peer.

As concluded in the linked issue, **the qpid implementation decided to advertise half the timeout setting**.

It seems that other implementations understood the advertised timeout to not be a hard limit, so **their client emit the heartbeat ON the idle timeout**.
That works with qpid, since the actual timeout is double what's advertised.
It will drop connection systematically if implemented like go-amqp or amqplite.

Advertising a shorter timeout than what is set in the settings seems strange to me, but does ensure that no client hits the idle timeout because it decided to emit heartbeat when the timeout expires.

Anyone has thoughts on this?

links for reference : 

- conclusion comment on original issue : https://github.com/Azure/go-amqp/issues/16#issuecomment-769548134
- spec section : http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transport-v1.0-os.html#doc-doc-idle-time-out 
- qpid commit to advertise half the timeout to the peer : https://github.com/apache/qpid-proton/pull/15

Man

**Comment by xinchen10** [comment]
I also think that's a strange behavior but it is recommended by the spec so it should be followed by implementations.
