### ISSUE TITLE
SetTimer in Heartbeat throws ObjectDisposedException

### ISSUE THREAD

**Issue by lothar7** [Azure/amqpnetlite#445]
Connection.cs line 932:
this.timer.Change(due > int.MaxValue ? int.MaxValue : (int)due, -1);

This throws an ObjectDisposedException if the connection ends/Stops while SetTimer runs. 

Not a critical issue though.

**Comment by xinchen10** [comment]
The exception is handled now by the fix for #438. If you see a first-chance exception, it is expected.
