### ISSUE TITLE
Address when connecting does not handle special characters

### ISSUE THREAD

**Issue by JonathanLamarre** [Azure/amqpnetlite#446]
When connecting to AMQP, the Address class seems unable to handle some characters when they are in the user or password section.

Internally the class Adress, when parsing the string representing the connection (something like amqp[s]://user:password@a.contoso.com:port/foo/bar), use a private method Parse, and this method does not support escaping, so at first glance the characters ":", "/", "@" cannot be included in the user or password.

I would propose to allow escaping inside the user and password part of the address string.

**Comment by xinchen10** [comment]
Like other URLs, user and password need to be URL encoded.
