### ISSUE TITLE
How do I authenticate to add a message to a queue

### ISSUE THREAD

**Issue by scott-david-walker** [Azure/amqpnetlite#451]
I have a Service Bus with a queue that has a shared access policy. How can authenticate via this method?

Apologies if this is obvious but I couldn't see it in the docs :-)

**Comment by xinchen10** [comment]
You have two options. Use the key name and key as user name and password when establishing a connection. Or use CBS to put a token before opening a link. There is a sample in the source code showing the CBS approach.
