### ISSUE TITLE
SSl settings with net35

### ISSUE THREAD

**Issue by Viktorstst** [Azure/amqpnetlite#452]
Is there a way to access connection SSL settings under .NET 3.5?

**Comment by xinchen10** [comment]
It is not accessible currently. Which SSL setting(s) do you need to control?

**Comment by Viktorstst** [comment]
CheckCertificateRevocation and ClientCertificates.

**Comment by xinchen10** [comment]
It can be done. However, the SSL and TCP settings are part of the `ConnectionFactory` API which is not available to net35. One option is the enhance the IHandler interface with two events: SocketConnected and SslNegotiation, where user can configure the socket or SslStream settings.

**Comment by xinchen10** [comment]
Socket and SslStream are exposed through new handler events. To set socket properties or perform custom SslStream authentication, do something as follows.
```
            var handler = new TestHandler(e =>
            {
                if (e.Id == EventId.SocketConnect)
                {
                    ((System.Net.Sockets.Socket)e.Context).SendBufferSize = 4096;
                }
                else if (e.Id == EventId.SslAuthenticate)
                {
                    ((System.Net.Security.SslStream)e.Context).AuthenticateAsClient("localhost");
                }
            });
```
