### ISSUE TITLE
Cannot re-connect immediately to Azure Iot-Hub unless code disconnect first

### ISSUE THREAD

**Issue by hbraasch** [Azure/amqpnetlite#456]
Can someone please give me some advise with a problem during my debug cycle?

I'm using AMQPLite in the nanoFramework ESP32 environment. I'm using the stock standard Azure-Iot-Hub sample in the nanoFramework samples folder https://github.com/nanoframework/Samples/tree/master/samples/AMQP/Azure-IoT-Hub, slightly modifies to exit and close the connection after 3 transmissions to Azure.
When running the Visual Studio debugger, once connected to Azure Iot-Hub, sending and receiving works fine.
However, if I stop the debug session before running the code that CLOSES the connection, I get a connection authentication exception if I immediately start a new debugging session.
If I wait a few minutes between debugging sessions, I can restart debugging without any connection problems.
Also, if I'm patient and step my code through the connection.Close() line, I can restart debugging immediately without problems.
This indicates to me that in my setup Azure IOT Hub dissallows new connections to the same device if already connected (unless idle timed-out). 

I'm using the following simple connection command:

```Connection connection = new Connection(new Address(hostName, 5671, userName, sasToken));```

Question: Is there a way to instruct the Azure IOT Hub to reconnect always, even if already connected? Or maybe I'm completely on the wrong track?

Help shall be much appreciated!

**Comment by xinchen10** [comment]
If the question is about how to setup IOT Hub to allow multiple connections to the same device, I am not sure if anyone can answer that here. You may need to contact the IOT Hub team.

If you have questions about nanoframework, @josesimoes should be able to help you.

**Comment by hbraasch** [comment]
Thanks for the prompt reply. Much appreciated.

It simply has to do with me unable to run the same app in quick succession. 

Let's say I put a breakpoint just after the first SEND instruction, and run the debugger for the first time in the morning. It will connect to the IOT Hub successfully, then sent the message to the hub, and stop at the breakpoint.

Now, if I immediately stop the debug session. then restart it, the connection to the IOT Hub will fail.
If I then wait approx 5 minutes and restart the debugger, everything will work fine again.

However, I've noticed if I run it outside VS, just looking at the debug messages with a monitor app, it runs flawlessly.
So the problem probably lies on the VS=>nanoFramework side. I'll therefore mention this to @josesimoes.

**Comment by josesimoes** [comment]
That's probably a side effect of running it in debugger mode... When stepping through the code you're probably causing some timeouts and/or disconnection. Recall this AMQP it's a binary protocol so, very sensitive to disturbances and glitches.

I haven't looked into the code, but this could be explained by the socket lingering option, and/or the closing "ceremony" of the protocol not happening because of the sudden end of the execution...
