### ISSUE TITLE
Encoder.WriteList cannot handle nested IList interfaces of arbitrary type

### ISSUE THREAD

**Issue by wim-cpp** [Azure/amqpnetlite#459]
The Encoder.WriteList method accepts an IList interface and writes it to a ByteBuffer. This method accepts any instance that implements IList. However, nested entries that implement IList _must_ have the specific AMQPNetLite List type, or an exception is thrown. Preferably, WriteList should accept any nested types that implement IList, or otherwise change its signature to accept a List instead of an IList to make its behavior more obvious.

**Comment by woppa684** [comment]
So, inserting an extra if [here](https://github.com/Azure/amqpnetlite/blob/762616b2244433495c09e35d8f0d54cb8415bf70/src/Types/Encoder.cs#L438) before `TryGetCodec` might help? Something like 
```cs
if (value is IList) {
    encoder = serializers[18].Encoder;
} else if (...) {
```
Don't know if that's the best place to put it but I guess it should work. Another option is in the `TryGetCodec` method itself but then you need to use `IsAssignableFrom` to match the type.

**Comment by woppa684** [comment]
@xinchen10 Is this a bug? Would you accept a PR for this?

**Comment by xinchen10** [comment]
A PR is welcome. Just note that after decoding the consumer will get the `List` type instead of the original `IList` type.
