### ISSUE TITLE
Upgraded project to .Net5, factory.CreateAsync(amqpsAddress) throws exception

### ISSUE THREAD

**Issue by kzeeshan-git** [Azure/amqpnetlite#463]
Hi,
Is there a change the way amqps certificates are validated for tls1.2. Project was working without any issue, just upgraded to .net5 and cannot create connection with error "Authentication failed, see inner exception". All certificates are in trust and root store, can you tell what is changed?
Regards,
![image](https://user-images.githubusercontent.com/53715743/118611243-32116680-b7ef-11eb-8f59-7e50ab5c5e79.png)

**Comment by xinchen10** [comment]
Are you using the same version of the amqp library after you upgraded to .net 5? That would mean any change would be inside  .net 5. There was another issue about client cert issue on mono runtime and was resolved by also setting LocalCertificateSelectionCallback. Maybe you could try that first.

**Comment by kzeeshan-git** [comment]
You are a saviour xinchen10. Since .net5 is platform independent, thus the client stores are not the local certificate stores. Just adding an extra line for Local Certificate Validation. and all worked like charm :-).

![image](https://user-images.githubusercontent.com/53715743/119428172-fa4e7580-bd3e-11eb-890a-cf73099c2be2.png)
