### ISSUE TITLE
Help on removing client-side buffer

### ISSUE THREAD

**Issue by felipegiacomozzi** [Azure/amqpnetlite#464]
Hello,

Reading the ActiveMQ docs there's a way to remove the client side buffer by setting consumerWindowSize to 0 (https://activemq.apache.org/components/artemis/documentation/latest/flow-control.html).
Looking at the amqpnetlite library I couldn`t find anything like that config.
I tried the SetCredit method with value 1 or setting the BufferManager to a small byte size ( 128 bytes) but the client still cached messages.

Is there a way to accomplish this?

Thanks for the help.

**Comment by xinchen10** [comment]
The library only supports credit based link flow control. I think you can get the same behavior by using CreditMode.Manual in SetCredit method. That means you would need to call SetCredit every time before you call Receive to get messages.

**Comment by felipegiacomozzi** [comment]
Setting the CreditMode to Manual worked.
Thanks for the help @xinchen10
