### ISSUE TITLE
Can I read out the name or version of the used broker with this lib?

### ISSUE THREAD

**Issue by PassionateDeveloper86** [Azure/amqpnetlite#465]
Hi,

we are upgrading from ActiveMQ 5 Classig to ActiveMQ Artemis in our projects.
We still have to run both message brokers for at least 2 years because we have a lot of projects which can't be migrated very fast.
So the new broker has a new addressing method for virtual topics which I have allready implemented and tested.
Sadly i have to support the old broker addressing as well.
To difference between them I want to read out the version and / or name of the used broker.

Is that possible?

**Comment by Havret** [comment]
Hello @PassionateDeveloper86,

I am not sure if this is valid for ActiveMQ Classic, but ActiveMQ Artemis sends you this information in Open Frame.

You need to inspect Open.Properties and there you should have the following fields available:

![image](https://user-images.githubusercontent.com/9103861/120916859-52c13380-c6ac-11eb-8e7e-81e8ff9358fa.png)

For reference: https://github.com/Havret/dotnet-activemq-artemis-client/blob/be7b8711ba755495e595164b621bca03361392c2/src/ActiveMQ.Artemis.Client/Builders/ConnectionBuilder.cs#L45-L50
