### ISSUE TITLE
Resending a message after receiving before accepting / rejecting leads to an error.

### ISSUE THREAD

**Issue by PassionateDeveloper86** [Azure/amqpnetlite#468]
Hi guys,

we are using your lib within our microservice-stack. On idea of our stack is that we have a router-application in which other microservice stacks can register each other and the router will have business logic behaviour to route to the right service.

I found a bug while implementing your library which will result in the Exception "Message was not received by this link." coming from the https://github.com/Azure/amqpnetlite/blob/master/src/ReceiverLink.cs from Line 483.

The reason is basicly, that when I have a message recieved by a ReceiverLinkand I publish the same exact message before I accept or rejecting this, the Delivery-Property is no longer the ReceiverLink, it is the SenderLink then which leeds to a false in the if-statement in the ReceiverLink in Line 482.

I workarounded this by simply copy the message before resend it, but dunno it maybe should get fixed.

So our code looks like this:

            Connection connection = new Connection(new Address(address));
            Session session = new Session(connection);
            ReceiverLink rec = new ReceiverLink(session, "test", "MyTestAddress");
            while (true)
            {
                Message msg = rec.Receive(TimeSpan.FromSeconds(5));

                SenderLink sl = new SenderLink(session, "myTestSender", "MyTestAddress");
                await sl.SendAsync(msg);

                // ERROR! 
                rec.Accept(msg);
            }

To get the question ahead why not accepting directly after receiving, it is simple:
Because within the businesslogic of our so called router, there could be a Exception -> When this occurs the message should be rejected instead of accepted. (But this also throws the same "Message was not received by this link." error, if the message would be send before).

**Comment by Havret** [comment]
Hi @PassionateDeveloper86,

During the send, the library is overwriting the original delivery object associated with the message, which is necessary to send the disposition frame (accept the message). If this error hadn't been sent, you still wouldn't be able to accept the message (as the information you need to do it is lost at this point. 

If we eventually implement this https://github.com/Azure/amqpnetlite/issues/449, it should be possible, as `MessagePointer` will preserve the bits that are necessary to ack the message.

As a side note (to be ignored if you wish) I would be really careful with content base routing in your architecture. https://udidahan.com/2011/03/20/careful-with-content-based-routing/

**Comment by xinchen10** [comment]
Close for now. #449 tracks the potential improvement we could do.
