### ISSUE TITLE
Question: Can I get IP of a user that is connecting to my AMQP Broker?

### ISSUE THREAD

**Issue by gorazspajzer** [Azure/amqpnetlite#473]
HI!

I have 
`public class CBroker : IContainer`
and I would like to get user IP in method
`Link IContainer.CreateLink(ListenerConnection connection, ListenerSession session, Attach attach)`

Or maybe in my class
`sealed class APISaslProfile : SaslProfile, IAuthenticated`
in method 
`SaslCode ValidateCredentials(SaslInit init)`

I tried to find a way to get client IP but without success :( 

Any thoughts? any suggestions?

Thenx!

Gorazd

**Comment by xinchen10** [comment]
This information is not exposed today. We can look into a way to expose that. Should not be too difficult.

**Comment by xinchen10** [comment]
With ffc33658b59e57493cd4beb8fdb82d97bbafa203, transport objects are exposed to IHandler implementation. When you create the ConnectionListener, provide a HandlerFactory. The implementation will get notified for events and it can handle those of interests. In this scenario, you would be interested in the following events:
* SocketAccept: the context is a Socket object which you can check the remote and local Endpoints.
* HttpAccept and WebSocketAccept: for websockets listener. Endpoints are available in HttpListenerContext.
* ConnectionAccept: the listener connection and a socket or a web-socket.

If you need extra information from the client to make a decision, you can set some custom properties (e.g. the IP address) in ListenerConnection.Properties in ConnectionAccept, and then handle the following event,
* ConnectionRemoteOpen: the context is the Open performative received from the client and has the extra information.

**Comment by gorazspajzer** [comment]
The speed of response shocked me in a positive way!!! Thanx!!!!!
