### ISSUE TITLE
[Question] How to create a ByteBuffer from an array of bytes?

### ISSUE THREAD

**Issue by BOLT04** [Azure/amqpnetlite#475]
Hi everyone 👋,

I'm having some trouble getting an instance of `Amqp.Message` when receiving a message from a AMQP broker (RabbitMQ in this case). All I have in the receiving end is an array of bytes, here is a code snippet:

```csharp
byte[] body = //something...
Amqp.Message message = Amqp.Message.Decode(new ByteBuffer(body, 0, body.Length, body.Length));
```

This results in this error: `System.InvalidOperationException: 'buffer too small'`. 

I've also tried doing `Message.Decode(new ByteBuffer(body, 0, 0, body.Length))` instead, but I get a `System.NullReferenceException` in another line of code since all fields in the `Amqp.Message` are `null`. For further context on my use case, I'm using `CloudNative.CloudEvents` and `CloudNative.CloudEvents.Amqp` which uses AMQP.Net Lite, so I'm trying to get an `Amqp.Message` in order to get a CloudEvent instance: `CloudEvent decodedMessage = message.ToCloudEvent(new JsonEventFormatter());`

Any help is much appreciated,
Thank you!

**Comment by xinchen10** [comment]
What is the byte[] you received from RabbitMQ? Message.Decode requires a buffer that contains a serialized message. If the byte[] you received is just the body of a message (opaque user payload), you can still create a message object by just calling its constructor.
```
var message = new Message(body);
```

I think CloudEvent has its own schema. To convert the message to a cloud event, the message may also need some extra properties or annotations.

**Comment by BOLT04** [comment]
@xinchen10 when I decode the bytes with UTF8 I get a string in a weird format, here is an example: `"\0Ss�%\a@@@@@@�\u001capplication/cloudevents+json\0St��\n�\u0017cloudEvents:specversion�\u00031.0�\u000ecloudEvents:id�\bevent-id�\u0010cloudEvents:type�\nevent-type�\u0012cloudEvents:source�\u0017https://cloudevents.io/�\u0010cloudEvents:time�\0\0\u0001{�}]�\0Su�\0\0\u0001b{\"specversion\":\"1.0\",\"id\":\"event-id\",\"type\":\"event-type\",\"source\":\"https://cloudevents.io/\",\"time\":\"2021-09-01T22:31:47.4349102Z\",\"datacontenttype\":\"application/json\",\"data\":{\"Id\":\"event-id\",\"Type\":\"event-type\",\"Source\":\"https://cloudevents.io/\",\"Time\":\"2021-09-01T22:31:47.4351068+00:00\",\"DataContentType\":\"text/plain\",\"Data\":\"This is CloudEvent data\"}}\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"`.
From my understanding, it contains the message payload and "headers" in there.

I tried using `var message = new Message(body);` but most properties are still null when I try to convert to a cloud event. Could it be something related to the buffer that is sent to the broker? When I publish the message I have something like this:

```csharp
Amqp.Message message = // transform CloudEvent object to Amqp.Message...
var buffer = message.Encode().Buffer;
model.BasicPublish("demoExchange", "directexchange_key", properties, buffer);
```

**Comment by xinchen10** [comment]
Can you share one byte array that is failing `Message.Decode` (if it doesn't contain any confidential information)? The utf8 decoded string has some information but is missing some of the important values.

**Comment by BOLT04** [comment]
@xinchen10 could you help me understand how I could share the byte array? Can I simply log each byte and put them in a comment here, or do you prefer another way?

**Comment by xinchen10** [comment]
That is fine if it is not too much work for you. Since you have it in code, you could also encode it as BASE64 string and post the string here.

**Comment by BOLT04** [comment]
@xinchen10 Here is the byte array:
`
0 83 115 192 37 7 64 64 64 64 64 64 163 28 97 112 112 108 105 99 97 116 105 111 110 47 99 108 111 117 100 101 118 101 110 116 115 43 106 115 111 110 0 83 116 193 159 10 161 23 99 108 111 117 100 69 118 101 110 116 115 58 115 112 101 99 118 101 114 115 105 111 110 161 3 49 46 48 161 14 99 108 111 117 100 69 118 101 110 116 115 58 105 100 161 8 101 118 101 110 116 45 105 100 161 16 99 108 111 117 100 69 118 101 110 116 115 58 116 121 112 101 161 10 101 118 101 110 116 45 116 121 112 101 161 18 99 108 111 117 100 69 118 101 110 116 115 58 115 111 117 114 99 101 161 23 104 116 116 112 115 58 47 47 99 108 111 117 100 101 118 101 110 116 115 46 105 111 47 161 16 99 108 111 117 100 69 118 101 110 116 115 58 116 105 109 101 131 0 0 1 123 208 250 227 23 0 83 117 176 0 0 1 98 123 34 115 112 101 99 118 101 114 115 105 111 110 34 58 34 49 46 48 34 44 34 105 100 34 58 34 101 118 101 110 116 45 105 100 34 44 34 116 121 112 101 34 58 34 101 118 101 110 116 45 116 121 112 101 34 44 34 115 111 117 114 99 101 34 58 34 104 116 116 112 115 58 47 47 99 108 111 117 100 101 118 101 110 116 115 46 105 111 47 34 44 34 116 105 109 101 34 58 34 50 48 50 49 45 48 57 45 49 48 84 49 56 58 51 49 58 52 56 46 50 52 55 53 55 56 54 90 34 44 34 100 97 116 97 99 111 110 116 101 110 116 116 121 112 101 34 58 34 97 112 112 108 105 99 97 116 105 111 110 47 106 115 111 110 34 44 34 100 97 116 97 34 58 123 34 73 100 34 58 34 101 118 101 110 116 45 105 100 34 44 34 84 121 112 101 34 58 34 101 118 101 110 116 45 116 121 112 101 34 44 34 83 111 117 114 99 101 34 58 34 104 116 116 112 115 58 47 47 99 108 111 117 100 101 118 101 110 116 115 46 105 111 47 34 44 34 84 105 109 101 34 58 34 50 48 50 49 45 48 57 45 49 48 84 49 56 58 51 49 58 52 56 46 50 52 55 55 56 53 54 43 48 48 58 48 48 34 44 34 68 97 116 97 67 111 110 116 101 110 116 84 121 112 101 34 58 34 116 101 120 116 47 112 108 97 105 110 34 44 34 68 97 116 97 34 58 34 84 104 105 115 32 105 115 32 67 108 111 117 100 69 118 101 110 116 32 100 97 116 97 34 125 125 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0`

and here is the Base64 encoded string: `AFNzwCUHQEBAQEBAoxxhcHBsaWNhdGlvbi9jbG91ZGV2ZW50cytqc29uAFN0wZ8KoRdjbG91ZEV2ZW50czpzcGVjdmVyc2lvbqEDMS4woQ5jbG91ZEV2ZW50czppZKEIZXZlbnQtaWShEGNsb3VkRXZlbnRzOnR5cGWhCmV2ZW50LXR5cGWhEmNsb3VkRXZlbnRzOnNvdXJjZaEXaHR0cHM6Ly9jbG91ZGV2ZW50cy5pby+hEGNsb3VkRXZlbnRzOnRpbWWDAAABe9D9bnwAU3WwAAABYnsic3BlY3ZlcnNpb24iOiIxLjAiLCJpZCI6ImV2ZW50LWlkIiwidHlwZSI6ImV2ZW50LXR5cGUiLCJzb3VyY2UiOiJodHRwczovL2Nsb3VkZXZlbnRzLmlvLyIsInRpbWUiOiIyMDIxLTA5LTEwVDE4OjM0OjM1LjAwNDMxNDJaIiwiZGF0YWNvbnRlbnR0eXBlIjoiYXBwbGljYXRpb24vanNvbiIsImRhdGEiOnsiSWQiOiJldmVudC1pZCIsIlR5cGUiOiJldmVudC10eXBlIiwiU291cmNlIjoiaHR0cHM6Ly9jbG91ZGV2ZW50cy5pby8iLCJUaW1lIjoiMjAyMS0wOS0xMFQxODozNDozNS4wMDQ1ODA2KzAwOjAwIiwiRGF0YUNvbnRlbnRUeXBlIjoidGV4dC9wbGFpbiIsIkRhdGEiOiJUaGlzIGlzIENsb3VkRXZlbnQgZGF0YSJ9fQ==`

**Comment by BOLT04** [comment]
Actually, if I encode with Base64 and send those bytes through the broker, I'm able to decode the message and get the cloud event.
This seems to work:
```csharp
// Sender side
Amqp.Message message = cloudEvent.ToAmqpMessage(ContentMode.Binary, new JsonEventFormatter<>());
var byteBuffer = message.Encode();
var bytes = Convert.ToBase64String(byteBuffer.Buffer, byteBuffer.Offset, byteBuffer.Length);
var bytesToSend = Encoding.UTF8.GetBytes(bytes);

// Receiver side
byte[] body = //...
var temp = Encoding.UTF8.GetString(body);
body = Convert.FromBase64String(temp);
var decodedMessage = Amqp.Message.Decode(new ByteBuffer(body, 0, body.Length, body.Length));
var receivedCloudEvent = decodedMessage.ToCloudEvent(new JsonEventFormatter<>());
```

**Comment by xinchen10** [comment]
Is this the exact code you use to send the payload?
```
Amqp.Message message = // transform CloudEvent object to Amqp.Message...
var buffer = message.Encode().Buffer;
model.BasicPublish("demoExchange", "directexchange_key", properties, buffer);
```

The RabbitMQ API `BasicPublish` has a `ReadOnlyMemory<byte>` type for the payload. You are passing a `ByteBuffer` object. Do you have some implicit conversion code not shown here?

Can you explicitly create a `ReadOnlyMemory<byte>` struct from the `ByteBuffer` object from its `Buffer, Offset, and Length` properties?

**Comment by BOLT04** [comment]
I'm passing the `byte[]` like you have on your snippet. The `ByteBuffer`  object is the returned value from `message.Encode()`, I'm passing the `Buffer` field of that object 🙂.

Here is the exact code to send the payload (without the Base64 encoding):
```csharp
Amqp.Message message = cloudEvent.ToAmqpMessage(ContentMode.Binary, new JsonEventFormatter<>());
var byteBuffer = message.Encode();
model.BasicPublish("demoExchange", "directexchange_key", properties, byteBuffer.Buffer);
``` 

I tried creating the `ReadOnlyMemory<byte>` but I still can't decode the message with this code:
```csharp
byte[] body = deliveryEventArgs.Body.ToArray();
var decodedMessage = Amqp.Message.Decode(new ByteBuffer(body, 0, body.Length, body.Length));
var receivedCloudEvent = decodedMessage.ToCloudEvent(new JsonEventFormatter<>());
``` 

Creating the `ByteBuffer` this way `new ByteBuffer(body, 0, 0, body.Length)` also doesn't work.

**Comment by xinchen10** [comment]
On the sender side, it should use `new ReadOnlyMemory<byte>(byteBuffer.Buffer, byteBuffer.Offset, byteBuffer.Length)`. This is the part that contains the message.

BTW I can decode a message from the BASE64 encoded string you posted just fine.
```
            string s = "AFNzwCUHQEBAQEBAoxxhcH......YSJ9fQ==";
            byte[] b = Convert.FromBase64String(s);
            var message = Message.Decode(new ByteBuffer(b, 0, b.Length, b.Length));
```

**Comment by BOLT04** [comment]
@xinchen10 thank you, it works with `ReadOnlyMemory` 👍. Not sure why it wasn't working with the snippet I sent before for decoding, but your explanation makes sense.
I'll close this issue since it's now resolved, thanks again for all the help 😃
