### ISSUE TITLE
API methods should get Interfaces as parameters

### ISSUE THREAD

**Issue by ldwedari** [Azure/amqpnetlite#478]
This is related to issue #197 which is already closed. Unfortunately the changes perform in that commit are not enough to allow the API mocked in unit tests.
These are my suggestions:
- Session constructor should receive an IConnection.
- ReceiverLink constructor should receive an ISession.
- SenderLink constructor should receive an ISession.

In general all methods should receive an interface parameter. Ideally they should also return interfaces also this could be a breaking change.

**Comment by Havret** [comment]
Can you elaborate a bit why do you need this changes for?

**Comment by ldwedari** [comment]
As I mentioned, it is for unit testing. Let's say I have a class that takes care of creating links, connections and sessions. The classes also takes care of reconnecting when there is an error. 
Currently, there is no way for me to plug in mocked ISessions and IConnections because the constructors in your API are getting the classes as parameters instead of interfaces. But, I don't want to setup a queue to run unit test. It should be possible to just use mocks with the behavior I need to test.
I hope it is clearer now.

**Comment by xinchen10** [comment]
The constructors require concreate types. If you need to use interfaces, use them as factories to create child objects. For example,
```
            IConnectionFactory factory = new ConnectionFactory();
            IConnection connection = await factory.CreateAsync(this.testTarget.Address);
            ISession session = connection.CreateSession();
            ISenderLink sender = session.CreateSender("sender-" + testName, testTarget.Path);

            for (int i = 0; i < nMsgs; ++i)
            {
                Message message = new Message();
                message.Properties = new Properties() { MessageId = "msg" + i, GroupId = testName };
                message.ApplicationProperties = new ApplicationProperties();
                message.ApplicationProperties["sn"] = i;
                await sender.SendAsync(message);
            }

            IReceiverLink receiver = session.CreateReceiver("receiver-" + testName, testTarget.Path);
            for (int i = 0; i < nMsgs; ++i)
            {
                Message message = await receiver.ReceiveAsync(Timeout.InfiniteTimeSpan);
                Trace.WriteLine(TraceLevel.Information, "receive: {0}", message.ApplicationProperties["sn"]);
                receiver.Accept(message);
            }

            await sender.CloseAsync();
            await receiver.CloseAsync();
            await session.CloseAsync();
            await connection.CloseAsync();
```

However, today there might be some gaps between the constructors and the interface factory methods. We can always add them as needed.
