### ISSUE TITLE
Connection to ipv4 host from Azure does not work

### ISSUE THREAD

**Issue by ericlindersson** [Azure/amqpnetlite#48]
When connecting to amqp host that uses ipv4, a connection cannot be established from Azure (Cloud service). 

I changed to the following in \Net\TcpTransport.cs:66
Socket socket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);

By providing AddressFamily the connection worked. Can you add support for different address families?

Regards

**Comment by xinchen10** [comment]
The issue should be fixed now. Let me know if it is still not working for you.

Thanks.

**Comment by ericlindersson** [comment]
Are you planning a release with this fix any time soon?

**Comment by xinchen10** [comment]
I just released v1.1.4.
