### ISSUE TITLE
Open performative on connection open has idle timeout property set to 0

### ISSUE THREAD

**Issue by jziolkow** [Azure/amqpnetlite#483]
The open performative that's returned in the OnOpened event has 0 for the IdleTimeOut property despite a non-zero value being set on the connection factory or when setting it on a manually created Open object when creating a connection.

This appears to have the effect of not starting the heartbeat timer, which appears to result in links, sessions, and connections dropping from the broker.

I enabled FRAME level tracing and have confirmed there are no heartbeats being sent by the client.

**Comment by xinchen10** [comment]
The returned Open performative is configured by the remote peer independently. Settings on the connection factory only affects the Open performative created locally. Have you checked that the remote peer indeed set a value on IdleTimeOut? If you have the frame traces, do you see a value of this field on the returned open to the client?

**Comment by jziolkow** [comment]
For the purposes of testing, I set _connectionFactory.AMQP.IdleTimeout = (int)TimeSpan.FromMinutes(1).TotalMilliseconds

The frame trace that appears in the log comes back as timeout:600, but when I look at the returned instance of the Open performative, the IdleTimeOut property is 0. There seems to be a disconnect between what's returned logged in the frame trace vs what's reported by the object. And the latter seems to prevent a heartbeat from being sent over the connection as I've never seen a "SEND (ch=0) empty" message in the logs.

**Comment by xinchen10** [comment]
The timeout set on connection factory is sent to the broker and requests the broker to send heartbeats when idle. The value 0 in the returned open from broker means that the broker does not require heartbeats from client to keep the connection alive. There might be some configuration on broker you can set to enable it but that depends on what broker you are using. The open frames to and from the broker are totally independent. 
Did the broker send empty frames to the client over an idle connection when you set a 60s idle time on the factory? If not, the broker is not doing it right.
Did the broker cut the idle connection when it sent an open with 0 idle timeout? If yes, the broker does it wrong too.
