### ISSUE TITLE
Configure the use of Proxy on connection

### ISSUE THREAD

**Issue by vteixeira87** [Azure/amqpnetlite#485]
I'm trying to communicate with my broker but I have to inform a proxy, I'm not finding where I pass this information.

**Comment by xinchen10** [comment]
There is no built-in support of proxy for .net Socket which is used by the connection underneath. There are examples online for implementing a proxy using a socket. It should be possible to take that solution and build a proxy transport provider. Details for writing a transport provider can be found in example PeerToPeer.CustomTransport.
