### ISSUE TITLE
Support for lists and dictionary message bodies

### ISSUE THREAD

**Issue by rr118** [Azure/amqpnetlite#5]
Does the library support messages with a body of type list or dictionary? It seems like natural fit since the AMQP specification defines a list and map in its type system. The following tests both throw NullReferenceExceptions.

        [TestMethod]
        public void AmqpListTest()
        {
            var inputList = new List<string>() { "abc", "def" };
            var inputMessage = new Message(inputList);

            //Simulate sending the message
            var msgBytes = inputMessage.Encode();
            var outputMessage = Message.Decode(msgBytes);

            var outputList = outputMessage.GetBody<List<string>>(); //throws NullReferenceException
            CollectionAssert.AreEqual(inputList, outputList);
        }

        [TestMethod]
        public void AmqpDictionaryTest()
        {
            var inputDict = new Dictionary<string, string>() { { "a", "1" }, { "b", "2" } };
            var inputMessage = new Message(inputDict);

            //Simulate sending the message
            var msgBytes = inputMessage.Encode();
            var outputMessage = Message.Decode(msgBytes);

            var outputDict = outputMessage.GetBody<Dictionary<string, string>>(); //throws NullReferenceException
            CollectionAssert.AreEqual(inputDict, outputDict);
        }

Right now my workaround options are to manually iterate over the list or map body and create the typed list and dictionary object myself or wrap the collection in an AMQP serializable type.

        [AmqpContract]
        public class CollectionWrapper
        {
            [AmqpMember]
            public List<string> Collection { get; set; }
        }

**Comment by xinchen10** [comment]
Fixed https://github.com/Azure/amqpnetlite/commit/4c0f6a90a0f45a20fedcedd289dc9cfc038bc331

**Comment by rr118** [comment]
Thanks, Xin! Do you know when you plan to release the next NuGet package?
