### ISSUE TITLE
Adding ProductInfo as link property

### ISSUE THREAD

**Issue by josesimoes** [Azure/amqpnetlite#504]
@xinchen10 I'm currently in conversations in Azure SDK team about adding telemetry data from nanoFramework devices.
Their recommendation goes towards adding an equivalent of ProductInfo (from the C# SDK).

Looking at the C# SDK, [this is](https://github.com/Azure/azure-iot-sdk-csharp/blob/bc19934a3cecb45deeec43b914fd274c5868132c/iothub/device/src/Transport/AmqpIot/AmqpIotSession.cs#L227) the place where it's being added.

Now, in AMQPLite, the equivalent to this seems to be Attach.Properties. Can you please confirm? Any thoughts on this?

**Comment by josesimoes** [comment]
@xinchen10 you feedback on this please?

**Comment by xinchen10** [comment]
Yes, `Attach.Properties` is the equivalent of `AmqpLinkSettings.Properties`.

Even though it is not defined in the AMQP spec, there is an established pattern for passing client information to the broker/service for telemetry and diagnosis purposes. It involves a few properties in the connection's properties (`Open.Properties` for amqpnetlite). 

I do not know whether Azure IOT reads `open.properties` or not, or just `attach.properties`.

For reference, these are the client SDKs that follow the produce/version/platform pattern.

Azure Event Hubs (Service Bus does the same):
https://github.com/Azure/azure-sdk-for-net/blob/12e0be17d2fd59a093caeb7cf44671b71d566cb0/sdk/eventhub/Azure.Messaging.EventHubs/src/Amqp/AmqpConnectionScope.cs#L1315
https://github.com/Azure/azure-sdk-for-net/blob/12e0be17d2fd59a093caeb7cf44671b71d566cb0/sdk/eventhub/Azure.Messaging.EventHubs/src/Core/ClientLibraryInformation.cs#L66

Apache Qpid JMS
https://github.com/apache/qpid-jms/blob/f9b6e245ea9aad481d319208b16df265313a5ebb/qpid-jms-client/src/main/java/org/apache/qpid/jms/provider/amqp/builders/AmqpConnectionBuilder.java#L129
