### ISSUE TITLE
Exception on custom type

### ISSUE THREAD

**Issue by kvegeta** [Azure/amqpnetlite#518]
Hi there,

i have created a new object named _ComplexMessage_ with some primitive objects inside and decorated with **_[AmqpContract(Name = "ComplexMessage", Encoding = EncodingType.Map)]_** and every property with **_[AmqpMember]_**.
Every time i try to send this object in the queue i always receive this exception message  'The type 'APIProducer.Model.ComplexMessage' is not a valid AMQP type and cannot be encoded.'
Any hint?
I have also tried with SimpleMap EncodingType with no result.

Thanks a lot to everyone.
Alessandro

**Comment by xinchen10** [comment]
Which nuget package and version do you use?

It seems like the serialization component is not referenced in your project. On regular .net framework, it is part of the core library and the issue should not happen. But if you use the .net core version, you would need to add a reference to Amqp.Serialization and create a message like this `var message = new Message() { BodySection = new AmqpValue<ComplexMessage>(value) };`. By doing this the extended serialization component will be loaded. See more details [here](https://github.com/Azure/amqpnetlite/blob/master/docs/articles/serialization.md).
