### ISSUE TITLE
Closing AMQPS connection does not close TCP connection

### ISSUE THREAD

**Issue by johansme** [Azure/amqpnetlite#525]
When a `Connection` object is set up to use AMQPS, the underlying `TcpTransport` uses an `SslStream` for the TCP communication. The `SslStream` wraps a `NetworkStream`, and is correctly set up so that disposing the `SslStream` also disposes the `NetworkStream`. However, the `NetworkStream` is set up using only the `Socket` object as a constructor argument. The single parameter constructor of `NetworkStream` means that the `NetworkStream` does not own the `Socket` object, and so disposing the `NetworkStream` does not close the `Socket`. To properly close the `Socket`, and the corresponding TCP connection, the constructor on [this line](https://github.com/Azure/amqpnetlite/blob/1978cc179182d8772b6cd7f9af7492665bc0b10f/src/Net/TcpTransport.cs#L131) should be `new NetworkStream(socket, true)` instead of `new NetworkStream(socket)`.

**Comment by kennethmyhra** [comment]
@xinchen10 do you have an ETA for the next release? This is a fix that would be nice to get tested as soon as possible for us.

**Comment by xinchen10** [comment]
v2.4.5 is released.
