### ISSUE TITLE
Flow control drain flag

### ISSUE THREAD

**Issue by robreeves** [Azure/amqpnetlite#56]
I am trying to understand the drain flag described in 2.6.7 Flow Control of the AMQP 1.0 spec. 

http://docs.oasis-open.org/amqp/core/v1.0/cos01/amqp-core-transport-v1.0-cos01.html#doc-flow-control

From what I understand if the drain flag is true and the sender link does not have any messages to send it should basically “return” the credit by consuming the credit and sending the flow state to the receiver link. I am not seeing that behavior with SenderLink and I’m not sure if my understanding of the drain flag is incomplete or if this is a possible bug. 

In SenderLink.OnFlow I see nowhere that the Flow.Drain property is honored. I see no place in the entire Amqp.Net project where the Flow.Drain property is used besides being set actually. Instead if SenderLink.OnFlow has no outgoing messages it just returns and keeps the credit. Is this a bug? 

Here is a sample application where I updated the sender link’s credit with drain set to true and the sender keeps the credit. 

    class Program
    {
        const string Address = "amqp://localhost:5462";
        const string MsgQueue = "queue";

        static void Main(string[] args)
        {
            var host = new ContainerHost(new Uri(Address));
            host.RegisterMessageProcessor(MsgQueue, new MessageProcessor());
            host.Open();

            var conn = new Connection(new Address(Address));
            var sess = new Session(conn);
            var sender = new SenderLink(sess, "client", MsgQueue);

            sender.Send(new Message("1"));

            //Shouldn't sender.credit be 0 here?
        }
    }

    class MessageProcessor : IMessageProcessor
    {

        public int Credit
        {
            get { return 1; }
        }

        public void Process(MessageContext messageContext)
        {
            Console.WriteLine(messageContext.Message.Body);
            messageContext.Link.SetCredit(10, true);
            messageContext.Complete();
        }
    }

**Comment by xinchen10** [comment]
@robreeves Your understanding is correct. The library does not support the drain flag yet. If the sender honors the flag and consumes all available credits, it would have to block the next Send call since there is no credit available. It could send another flow with available field set to inform the remote peer that it has something to send and hopefully gets back credit to send messages to avoid timeout exceptions.

For a client receiver, this flag may be more useful if it is talking to a broker. If the application only processes messages at certain intervals, it could use the drain flag to poll messages from the broker without having messages being pushed to the client even though the app is not processing them.

**Comment by robreeves** [comment]
@xinchen10 Thanks for the explanation. I don't have a tangible use case to implement the drain flag right now. Just exploring my options and making sure I understand the things properly. 

Regardless of the drain flag the first paradigm you described sounds interesting - A sender link with no credit requesting credits when it has a message to send. I don't see access to the flow methods in SenderLink or Link. Is there a way to do this in the library on the client side? I know I could control the flow on the broker side using an ILinkProcessor.

**Comment by xinchen10** [comment]
@robreeves if there is a valid use case we can expose some method to send a flow from the sender. It could be used to communicate the available value or to transmit some custom data in the flow.properties field.

**Comment by robreeves** [comment]
@xinchen10 Thanks. Right now I don't have an immediate use case. Just exploring ways to prevent the clients from overloading the broker. For now I am going forward with using a semaphore to limit message processing concurrently to keep things simple. If that proves not to be good enough I might decide to explore a slightly more complex option like this.
