### ISSUE TITLE
[Doubt] Possibility of creating new resources - (new queues/topics)

### ISSUE THREAD

**Issue by meciasbueno** [Azure/amqpnetlite#560]
With this lib is it possible to create new resources? for example:
- Create a new exchange/queue in rabbitmq?
- Create a new topic/subscription on azure servicebus?

**Comment by xinchen10** [comment]
This library lets you control all the protocol behavior defined by the standard, where the only way to create a new resource is to use a dynamic Source/Target when a link is created. Some brokers allow autocreation of resources if the address specified by the client does not exist but that's a broker specific implementation detail, and you would need to contact the broker owner to find which configurations are needed for that.
