### ISSUE TITLE
Multicast queue message filtering in ActiveMq Artemis

### ISSUE THREAD

**Issue by ldwedari** [Azure/amqpnetlite#563]
Amqpnet lite is able to create multicast queues automatically in ActiveMq Artemis.
But I have not yet being able to find out how to specify the message filter attribute of the queue. 
I want the filtering to be done at the topic queue when receiving it from the address. I've tried with FilterSet but the attribute is left empty:

![image](https://user-images.githubusercontent.com/10748521/230994845-ee960db1-310e-4d16-b5fb-6f5835ac4788.png)

In any case, I'm not interesting in using the FilterSet property of Source because this filtering is done at the consumer terminus. That means that there are message left in the queue that will never being processed.

Additionally, I would like to be able in the future to modify the filter of the queue if needed.

Is there a way to specify this filter in amqpnetlite just for the queue? Could the filter be updated? If not is there an alternative way to do it?

**Comment by xinchen10** [comment]
I don't know if ActiveMQ Artemis supports subscription queue management through standard AMQP protocol. In this page https://activemq.apache.org/components/artemis/documentation/latest/amqp.html, it says that `By default any receiving link that attaches to an address that has only multicast enabled will be treated as a subscription and a corresponding subscription queue will be created.`, but it is not clear if the filter-set is used or not.

It might be more useful to ask this question in the ActiveMQ Artemis community.
