### ISSUE TITLE
Invalid DateTime conversion

### ISSUE THREAD

**Issue by miqm** [Azure/amqpnetlite#579]
The method used to convert DateTime to miliseconds is invalid. 

Following code returns different results:
```
const long epochTicks = 621355968000000000; // 1970-1-1 00:00:00 UTC
const long TicksPerMillisecond = 10000;

// The AmqpNetLite way:
Console.WriteLine((DateTime.MaxValue.ToUniversalTime().Ticks - epochTicks) / TicksPerMillisecond);

// The proper way:
Console.WriteLine((DateTime.MaxValue - DateTime.UnixEpoch).TotalMilliseconds);
```

result:
```
253402297199999
253402300800000
```

This blocks passing DateTime.MaxValue to Azure Service Bus `get-message-sessions` to retrieve all sessions as per discussion here: https://github.com/MicrosoftDocs/azure-docs/issues/119766

**Comment by miqm** [comment]
Thanks @xinchen10 , it works now. Looking forward for releasing new nuget package!

**Comment by miqm** [comment]
@xinchen10 any eta when you'll publish new nuget version with corrected timestamp?

**Comment by xinchen10** [comment]
Release 2.4.9 is out.
