### ISSUE TITLE
Calling SendAsync while the connection is closing/closed results in an UnobservedTaskException

### ISSUE THREAD

**Issue by RusuIonut21** [Azure/amqpnetlite#584]
I am using the library to send/receive messages to a message broker (ActiveMQ Artemis). Also I have a handler for TaskScheduler.UnobservedTaskException to close the process if any exception occurs. 

If I send a message while the connection with the message broker is down, I receive an exception (as expected).
The problem is that I also get an UnobservedTaskException containing a TimeoutException because of it.

It seems that the problem is in **SendTask** class:
```CS 
public SendTask(SenderLink link, Message message, DeliveryState state, TimeSpan timeout)
{
	this.timer = new Timer(onTimer, this, (int)timeout.TotalMilliseconds, -1);
	link.Send(message, state, onOutcome, this);
}
```

The call **link.Send** can fail, but if that happens, the timer is not disposed and the timeout exception is thrown in an unobserved task.
This king of behavior also happens when the **link.Send** fails, but **onOutcome** callback is still fired.

**Comment by xinchen10** [comment]
Thank you for reporting and fixing the issue.

**Comment by RusuIonut21** [comment]
@xinchen10 When can I expect a new release with this fix?
