### ISSUE TITLE
AMQP client connecting via Proxy server

### ISSUE THREAD

**Issue by CSHinUK** [Azure/amqpnetlite#594]
I'm having trouble using this client library to connect via a proxy server.  I'm writing an application using .NET Framework 4.8 and this allows a proxy to be defined in the normal app.config file.  However I'm having trouble making the intiial connection and our network admin have monitored the proxy server and can't see any traffic from my dev PC when it initialises the connection.

Can you confirm the client library will obey a proxy defined in the app.config file and if not is there another way to define the proxy address?

I can't see anything mention at all in the documentation in relation to a proxy.

Any help would be appreciated.

**Comment by xinchen10** [comment]
How did you set the proxy in app.config? Something like this?
https://learn.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/defaultproxy-element-network-settings

**Comment by CSHinUK** [comment]
Yes, we've used that technique numerous times for various other Windows Services that use web services.

**Comment by xinchen10** [comment]
This proxy is used for HTTP protocol only. AMQP by default uses TCP. You could try the WebSocket transport (changing the address scheme to "wss", e.g. "wss://contoso.com").

**Comment by CSHinUK** [comment]
This just gives this exception "Failed to send : System.NotSupportedException: wss"

**Comment by xinchen10** [comment]
Please reopen the issue if the suggested code does not work.

**Comment by xinchen10** [comment]
Which package do you reference in your project, AMQPNetLite or AMQPNetLite.Core? On .NET Framework 4.8, you can reference the main package AMQPNetLite.

Is the code you shared complete? How do you create the ConnectionFactory object? Can you try this?
```
var wssFactory = new WebSocketTransportFactory();
wssFactory.Options = o =>
{
    o.Proxy = new WebProxy("X.X.X.X:3128",true);
};
var connectionFactory = new ConnectionFactory(new TransportProvider[] { wssFactory });
var connection = await connectionFactory.CreateAsync(new Address(hostName, port, user, password));
```

If your proxy requires authentication, you would need to set the credentials on WebProxy instance.

**Comment by CSHinUK** [comment]
Thanks for the prompt response.  I've included the full sample code up to the point where the exception occurs.  Our proxy does not require credentials.  To specify the proxy I've tried the standard technique for a .NET where the proxy is specified in the App.Config file and also when creating the transport factory (as below).  Neither technique is going via the proxy.

We tested with firewall rules and we can make a connection, however that was just a test.  It is a requirement that this project uses the proxy server.  Thanks

Packages referenced:

AMQPNetLite, AMQPNetLite.Core, AMQPNetLite.WebSockets

                var p12CertLocation = "XXXXX";
                var p12CertPassword = "XXXXX";
                var hostName = @"XXXXX";     //Just the host name, no prefixed scheme
                var user = "XXXXX";
                var password = "XXXXX";
                var port = 443;


                //Load the certificate 
                var certs = HelperFunctions.GetClientCert(p12CertLocation, p12CertPassword);

                var wssFactory = new WebSocketTransportFactory();
                wssFactory.Options = o =>
                {
                    o.ClientCertificates = certs;   //Is this line necessary as certs passed to SSL 
                    o.Proxy = new WebProxy("XXX.XXX.XXX.XXX:3128", true);
                };

                var factory = new ConnectionFactory(new TransportProvider[] { wssFactory });
                factory.TCP.NoDelay = true;
                factory.TCP.SendBufferSize = 16 * 1024;
                factory.TCP.SendTimeout = 30000;

                factory.SSL.ClientCertificates = certs;
                factory.SSL.Protocols = SslProtocols.None;
                factory.SSL.RemoteCertificateValidationCallback = RemoteCertificateValidationCallback;

                //No need for this line, by passing the user & password with the Address to CreateSync then this switches to SaslProfile - plain
                //factory.SASL.Profile = SaslProfile.External;

                factory.AMQP.MaxFrameSize = 64 * 1024;
                factory.AMQP.HostName = hostName;
                factory.AMQP.ContainerId = "container:Test";

                //Exception thrown on this line - System.Net.Sockets.SocketException: 'No connection could be made because the target machine actively refused it'
                var connection = await factory.CreateAsync(new Address(hostName, port, user, password));

**Comment by xinchen10** [comment]
Create the address like this,
```
new Address(hostName, port, user, password, scheme="WSS")
```

**Comment by CSHinUK** [comment]
Thanks, the connection  is now going via the proxy!
