### ISSUE TITLE
Valid Values for Error Condition 

### ISSUE THREAD

**Issue by rajeshganesh** [Azure/amqpnetlite#6]
I am fairly new to AMQP protocol and I am using AMQP.Net Lite to implement my server. This server application might eventually be exposed to third party developers to send data.

My question is on the correct usage of Error Object while returning a response. The Error object has three properties Condition, Description, Info. The Description and Info properties seems like it can be user defined which helps me to set information that my developers would understand around my data. 

But I am not sure what are the best practices around using Condition property. The specification ( http://docs.oasis-open.org/amqp/core/v1.0/cos01/amqp-core-transport-v1.0-cos01.html#type-amqp-error ) indicates a set of valid values for this property but I am not sure if I Can use my custom values here. It is hard to map my errors to these preset values in the protocol(I don't have a straight forward one to one mapping).

**Comment by xinchen10** [comment]
I will share some information based on my interpretation of the spec. The best practice would be using the standard error conditions whenever possible but I think you are allowed to define your own error condition symbols and pass it around in the Error object, as long as they are understood and appropriately dealt with by the application. This is usually not an issue if you control everything of the application but may run into interoperability issues if specific actions must be taken based on the error conditions you return. For example,
1. part of the application uses a different client library to access your server but the library does not expose the error condition.
2. the client library transforms the received error conditions to some other exceptions/errors and it is not possible to get the original error conditions.
