### ISSUE TITLE
Cancelable SenderLink.Send method

### ISSUE THREAD

**Issue by robreeves** [Azure/amqpnetlite#73]
I think the library could benefit from the SenderLink.Send methods to be cancelable. For example I may be in the middle of sending a large message and receive a stop request of some sorts (i.e. a Windows service stop). I think it would also be helpful for SenderLink.SendAsync to be cancelable. 

What do you think? Is this a feature you'd be open to?

Here is a quick example of what I mean with some borrowed code from the synchronous SenderLink.Send.

    public static class SenderLinkExtensions
    {
        public static void Send(this SenderLink sender, Message message, CancellationTokenSource cancelToken)
        {
            using (var mres = new ManualResetEvent(false))
            {
                Outcome outcome = null;
                OutcomeCallback callback = (m, o, s) =>
                {
                    outcome = o;
                    mres.Set();
                };

                sender.Send(message, callback, null);

                while (true)
                {
                    //Check if canceled
                    //TODO - remove message from outgoingList if canceled?
                    cancelToken.Token.ThrowIfCancellationRequested();

                    if (mres.WaitOne(100))
                    {
                        //Handle error outcomes
                        if (outcome != null)
                        {
                            if (outcome.Descriptor.Code == 38)
                            {
                                Released released = (Released)outcome;
                                throw new AmqpException(ErrorCode.MessageReleased, null);
                            }
                            else if (outcome.Descriptor.Code == 37)
                            {
                                Rejected rejected = (Rejected)outcome;
                                throw new AmqpException(rejected.Error);
                            }
                        }

                        return;
                    }
                }
            }
        }
    }

**Comment by xinchen10** [comment]
Cancelling a network operation is tricky. If the message is in the middle of transmission, we need to marked it as canceled, remove delivery/tracking state from link/session and send a signal to the remote peer to release the partial transfers. If the message is already transmitted, throwing on cancelation causes an in-doubt delivery. In your case, can you close the link when the service is shutting down? That should release all pending deliveries.

**Comment by robreeves** [comment]
It seems like the same procedure that has to be taken with the timeout version of SenderLink.Send. In that case it is basically a cancel caused by a timeout limit. In my specific case I can rely on closing the link. Thanks.
