### ISSUE TITLE
Any plans for a WCF Binding?

### ISSUE THREAD

**Issue by rschiefer** [Azure/amqpnetlite#77]
I'm really impressed with this framework.  Looks like it hits almost all the possible use cases.

Any plans to build a WCF binding?  Or do you know if anyone else is?

**Comment by xinchen10** [comment]
@rschiefer hi, there is no plan to support WCF binding right now. If anyone is interested in building one, we will be very happy to help with any blocking issues or new feature requests of this library.

In general we want this library to support the standard AMQP protocol and provide an easy-to-use API set for it. We'd like other extensions/bindings to be built on top of this library as separate projects.

Another reason for not supporting WCF right now is the lack of a binding specification (how WCF channels/messages are mapped to AMQP ones). Without that it would be difficult to achieve inter-operability with any other clients.

Regards,
Xin
