### ISSUE TITLE
Message decoding requires previous warmup for cached types

### ISSUE THREAD

**Issue by ctetzlaff** [Azure/amqpnetlite#79]
Hello community,

in reference to my last issue "Amqp.Message is not serializable #72" I have thank you for your fast support. The library is also very helpful, great work!
Today I have found a some behaviour which was a little bit painful for me and I didn't found any documentation about it. It took me some time to figure out that the library needs a "warmup" to prepare cached types for the internal serializers. The problem occur when you encode data by using message.Encode() and try to decode it back in another application instance. In this case the static Message Decode method was not able to cast Encoder.ReadObject(buffer) to RestrictedDescribed.
Maybe you can extend the documentation for this case. I think a additional generic method to register custom types could also be helpful.

Kind regards

ctetzlaff

**Comment by xinchen10** [comment]
@ctetzlaff hey, this is a bug. I just fixed it. Message.Decode should work on the bytes you read directly from file or other storage. If you have a custom type in the message body, it can be read by calling message.GetBody<T>() where T is your custom type name.

Thanks.

**Comment by xinchen10** [comment]
I did some testing and verified the fix in v1.1.6. Please reopen the issue if it still happens.
