### ISSUE TITLE
Links are not assigned a handle ID

### ISSUE THREAD

**Issue by rr118** [Azure/amqpnetlite#8]
According to section 2.6.2 of the AMQP 1.0 specification each link should be assigned a numeric handle. All handles return a value of 0. Here is a test to reproduce the issue.

        [TestMethod]
        public void LinkHandleTest()
        {
            const string MsgProcName = "msg_processor";
            const string Endpoint = "amqp://guest:guest@127.0.0.1:5762";

            var processor = new Moq.Mock<IMessageProcessor>();

            processor.Setup(proc => proc.Credit).Returns(300);

            processor.Setup(proc => proc.Process(It.IsAny<MessageContext>()))
                .Callback<MessageContext>(msg =>
                {
                    Console.WriteLine("Name: {0}, Handle: {1}", msg.Link.Name, msg.Link.Handle);
                    msg.Complete();
                });

            var uri = new Uri(Endpoint);
            var host = new ContainerHost(new List<Uri> { uri }, null, uri.UserInfo);
            host.RegisterMessageProcessor(MsgProcName, processor.Object);
            host.Open();

            var conn1 = new Connection(new Address(Endpoint));
            var sess1 = new Session(conn1);
            var link1 = new SenderLink(sess1, "link1", MsgProcName);
            link1.Send(new Message("1"), 5000); //output in msg processor: Name: link1, Handle: 0

            var conn2 = new Connection(new Address(Endpoint));
            var sess2 = new Session(conn2);
            var link2 = new SenderLink(sess2, "link2", MsgProcName);
            link2.Send(new Message("2"), 5000); //output in msg processor: Name: link2, Handle: 0
        }

**Comment by xinchen10** [comment]
A Link Endpoint is associated with a Session, so the handle is scope to that session. If you create the two links within the same session, they will have different handles.

**Comment by rr118** [comment]
I tested and the handle value is different if I share a session. Thanks for the clarification.
