### ISSUE TITLE
System.Net.Sockets.SocketException

### ISSUE THREAD

**Issue by jornbeyers** [Azure/amqpnetlite#80]
Hi, 

I'm trying to run the Interop.Server/Client examples in DNXCore5.0, but I get the following System.Net.Sockets.SocketException: "No connection could be made because the target machine actively refused it". 

Is this just because websockets aren't supported by DNXCore5.0? 
Googling this error told me to make firewall rules for the 5672 port, but this doesn't help. I also looked if the port is already used by any application by running the "netstat" command in cmd, but this is not the case. I'm just trying to run the examples locally for now.

Curious to hear your responses!

**Comment by xinchen10** [comment]
It should not be a firewall issue. The examples do not use WebSockets either. These two examples require a broker listening on the endpoint specified in the example code. It also needs a pre-configured queue named "service_queue" and dynamic node support from the broker. Do you have a broker set up that meet these requirements?

Did you retarget the projects to dnxcore50 or run the examples binary as is?

**Comment by jornbeyers** [comment]
Thanks @xinchen10 , I forgot about the dynamic node support.
