### ISSUE TITLE
customize attach for ContainerHost outgoing links

### ISSUE THREAD

**Issue by mbroadst** [Azure/amqpnetlite#83]
I see that it's possible to customize attaches for incoming links using a LinkProcessor, however I don't see how it's possible to customize it for outgoing links. For instance, the amqp spec indicates that I can specify a `apache.org:legacy-amqp-topic-binding:string` property to match subjects to a given endpoint. How would I attach this information to the link created for a `RegisterMessageProcessor`?

**Comment by mbroadst** [comment]
Oh I see, I may have misunderstood the intent of this class. It seems that ContainerHost is meant explicitly to be a server (i.e. broker-less)?

**Comment by xinchen10** [comment]
@mbroadst you are right. ContainerHost class is for hosting listeners in a server application.

If I understand your question correctly, you want to customize the attach object for client link (talking to a broker). For that you can use the constructor that takes an Attach object which you create and customize. Below is one example (I didn't test it but you can get the idea).
```
    Connection connection = new Connection(address);
    Session session = new Session(connection);
    Attach attach = new Attach();
    attach.Target = new Target();
    Source source = new Source() { Address = "my-exchange" };
    source.FilterSet = new Map();
    source.FilterSet[new Symbol("topic-filter")] = new DescribedValue(
        new Symbol("apache.org:legacy-amqp-topic-binding:string"),
        "*.stock.#");
    attach.Source = source;
    ReceiverLink receiver = new ReceiverLink(session, "receiver-0", attach, null);
    Message message = receiver.Receive();
    receiver.Accept(message);
```

**Comment by mbroadst** [comment]
@xinchen10 hey thanks for the quick response. I was already doing it this way with the `ReceiverLink` directly actually to create my own command processor :) I just thought I could reduce code duplication by using the `ContainerHost`, and misread its intent. Whoops.

Thanks!
