### ISSUE TITLE
serialization of enum types

### ISSUE THREAD

**Issue by mbroadst** [Azure/amqpnetlite#84]
Is it possible to have an [AmqpMember] for an enum type? I'm getting a `NotSupportedException`, but I'm not sure if that's because the enum is actually a region from a DllImport (I'm unfortunately maintaining a legacy codebase here and C# isn't my strongest suit!)

I couldn't find any examples of serializing an enum type in the tests, so I'm thinking maybe it's not supported (yet)

**Comment by mbroadst** [comment]
To clarify a little bit more, these used to be plain `DataContract`s, and those worked just fine when serializing to JSON - but I imagine I need to teach the AMQP serializer a little more about them. Here is an example:

```
        #region enum
        public enum WTS_CONNECTSTATE_CLASS
        {
            Active,
            Connected,
            ConnectQuery,
            Shadow,
            Disconnected,
            Idle,
            Listen,
            Reset,
            Down,
            Init
        }
        #endregion


        [AmqpContract(Encoding = EncodingType.SimpleMap)]
        public class TerminalSessionData
        {
            [AmqpMember]
            public int SessionId { get; set; }

            [AmqpMember]
            public WTSHelper.WTS_CONNECTSTATE_CLASS ConnectionState { get; set; }

            [AmqpMember]
            public string StationName { get; set; }
        }
```

**Comment by mbroadst** [comment]
We also have cases from that same class of structs defined in the imported dll like:

```
        [StructLayout(LayoutKind.Sequential)]
        public struct WTS_CLIENT_ADDRESS
        {
            public uint AddressFamily;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 20)]
            public byte[] Address;
        }
```

which we used to be able to just make a `DataMember` for. Is there an example of how to educate the AMQP serializer to interpret those types? Obviously there are examples of using custom types in an `AmqpContract`, but that's for types that are also annotated as `AmqpContract`. In this case, it's already a `StructLayout`, can I just further annotate it as an `AmqpContract`?

**Comment by xinchen10** [comment]
enum type is not supported currently. I will consider supporting it in the next release. Before that, you can workaround the issue by doing:
```
        [AmqpContract(Encoding = EncodingType.SimpleMap)]
        public class TerminalSessionData
        {
            [AmqpMember]
            public int SessionId { get; set; }

            [AmqpMember]
            int connectionState;
            public WTSHelper.WTS_CONNECTSTATE_CLASS ConnectionState
            {
              get { return (WTSHelper.WTS_CONNECTSTATE_CLASS)this.connectionState; }
              set { this.connectionState = (int)value; }
            }

            [AmqpMember]
            public string StationName { get; set; }
        }
```

The serializer only understands AmqpContract attribute. If a custom type is not annotated with this attribute, the serializer throws NotSupportedException. It's goal is to enable passing C# object easily with other clients using a standard type system, but not to support all features supported by existing .Net serializers.

For the struct type, you could just add AmqpContract/Member to it and it should work.

**Comment by mbroadst** [comment]
@xinchen10 okay thanks, I'll give it a shot as soon as I figure out getting this working with .NET 4.0 locally :)
