### ISSUE TITLE
.NET 4.0 target is missing constant for defining Message.GetBody (NETFX40)

### ISSUE THREAD

**Issue by mbroadst** [Azure/amqpnetlite#85]
definition: https://github.com/Azure/amqpnetlite/blob/master/src/Message.cs#L111
constants for net40 project: 
  * https://github.com/Azure/amqpnetlite/blob/master/src/Amqp.Net40.csproj#L22
  * https://github.com/Azure/amqpnetlite/blob/master/src/Amqp.Net40.csproj#L30

**Comment by xinchen10** [comment]
Fixed in v1.1.7
