### ISSUE TITLE
amqp:connection:forced AmqpException in EventHub .NETMF sample

### ISSUE THREAD

**Issue by maiorfi** [Azure/amqpnetlite#88]
Hi.

What is the most likely cause for AmqpException with amqp:connection:forced description?

I'm currently working with a AMQP (not AMQPS) connection since my board doesn't support AMQPS.

Thanks!

**Comment by xinchen10** [comment]
@maiorfi the Azure EventHub service requires SSL. The error means the tcp connection was established but then reset (by the service because SSL handshake failed). To talk to Azure Service Bus/Event Hub, the device needs to support SSL.

**Comment by maiorfi** [comment]
Thanks.
