### ISSUE TITLE
Operation cannot be performed against publisher

### ISSUE THREAD

**Issue by maiorfi** [Azure/amqpnetlite#89]
Hi, running EventHub sample on reference .NETMF 4.4 board I get following exception for SendToEventHubPublisher() test case:

Amqp.AmqpException: The operation cannot be performed against publisher 'device0001' because the targeted namespace 'iae-test-ns' is of Basic tier. TrackingId:4b329eec2b2a43cb8fbdbc21115888b5_G39,TimeStamp:2/4/2016 1:53:54 PM

What does it mean?

Thanks!

**Comment by josesimoes** [comment]
Hey,

Without looking into the code I'm guessing you are trying to perform an operation that is not supported in the Basic tier (which is probably the tier you have configured your Event Hub).
Check this to see the differences:
https://azure.microsoft.com/en-us/pricing/details/event-hubs/

You may want to change to the Standard tier for your testing to succeed... :wink:

**Comment by maiorfi** [comment]
Just got that I did't spot this issue until yesterday just because Azure IoT Hub went GA...yesterday :smile:
