### ISSUE TITLE
Unique link names are not enforced

### ISSUE THREAD

**Issue by robreeves** [Azure/amqpnetlite#9]
According to section 2.6.1 of the AMQP 1.0 specification all links in the same direction between two containers must have the a unique name. This is not enforced in ContainerHost/ConnectionListener. I would expect a second link with the same name, in the same direction to be rejected. 

If a connection and session is used per link they both are attached and can send data. Here is a test to reproduce it.

        [TestMethod]
        public void TwoLinksSameName_SeparateConnection()
        {
            const string MsgProcName = "msg_processor";
            const string LinkName = "duplicate name";
            const string Endpoint = "amqp://guest:guest@127.0.0.1:5762";

            var processor = new Mock<IMessageProcessor>();

            processor.Setup(proc => proc.Credit).Returns(300);

            processor.Setup(proc => proc.Process(It.IsAny<MessageContext>()))
                .Callback<MessageContext>(msg =>
                {
                    Console.WriteLine("Name: {0}, Handle: {1}", msg.Link.Name, msg.Link.Handle);
                    msg.Complete();
                });

            var uri = new Uri(Endpoint);
            var host = new ContainerHost(new List<Uri> { uri }, null, uri.UserInfo);
            host.RegisterMessageProcessor(MsgProcName, processor.Object);
            host.Open();

            var conn1 = new Connection(new Address(Endpoint));
            var sess1 = new Session(conn1);
            var link1 = new SenderLink(sess1, LinkName, MsgProcName);
            link1.Send(new Message("1"), 5000); //output in msg processor: Name: duplicate name, Handle: 0

            var conn2 = new Connection(new Address(Endpoint));
            var sess2 = new Session(conn2);
            var link2 = new SenderLink(sess2, LinkName, MsgProcName);
            link2.Send(new Message("2"), 5000); //output in msg processor: Name: duplicate name, Handle: 0

            link1.Send(new Message("12"), 5000); //output in msg processor: Name: duplicate name, Handle: 0
            link2.Send(new Message("22"), 5000); //output in msg processor: Name: duplicate name, Handle: 0
        }

If two links share a session the second link attaches, but hangs and eventually times out when it tries to send data.

        [TestMethod]
        public void TwoLinksSameName_SharedSession()
        {
            const string MsgProcName = "msg_processor";
            const string LinkName = "duplicate name";
            const string Endpoint = "amqp://guest:guest@127.0.0.1:5762";

            var processor = new Mock<IMessageProcessor>();

            processor.Setup(proc => proc.Credit).Returns(300);

            processor.Setup(proc => proc.Process(It.IsAny<MessageContext>()))
                .Callback<MessageContext>(msg => 
                    {
                        Console.WriteLine("Name: {0}, Handle: {1}", msg.Link.Name, msg.Link.Handle);
                        msg.Complete();
                    });

            var uri = new Uri(Endpoint);
            var host = new ContainerHost(new List<Uri> { uri }, null, uri.UserInfo );
            host.RegisterMessageProcessor(MsgProcName, processor.Object);
            host.Open();

            var conn = new Connection(new Address(Endpoint));
            var sess = new Session(conn);
            var link1 = new SenderLink(sess, LinkName, MsgProcName);
            var link2 = new SenderLink(sess, LinkName, MsgProcName);

            link1.Send(new Message("a"), 5000);
            link2.Send(new Message("a"), 5000); //times out
        }

**Comment by xinchen10** [comment]
You are right. Link names MUST be unique in the same direction between two containers. It doesn't seem to be an urgent issue so I will add this enforcement later. Let me know if it is not true. The timeout issue needs to be fixed sooner.

**Comment by rr118** [comment]
The link name constraint is important for me within a month or two, but it is not urgent this moment. Thanks.

**Comment by xinchen10** [comment]
Added link name validation in container host.
