### ISSUE TITLE
.NET Micro Framework reference hardware?

### ISSUE THREAD

**Issue by maiorfi** [Azure/amqpnetlite#90]
Hi. What kind of reference hardware is your project tested on for .NETMF?

Thanks!

**Comment by xinchen10** [comment]
I have used the STM32F4 discovery board mainly for the codec testing and the emulator for inter-op with brokers. I know @ppatierno and @josesimoes also tried the library on other devices.

**Comment by josesimoes** [comment]
I've work on the NETMF version and been using it on my company GPRS IoT module based on the SIM800: http://eclo.github.io/SIM800h-IoT-module

The support for network and in particular SSL/TLS in 4.4 is only working in the Keil reference board. As far as I know there is no other hardware running 4.4+network+SSL/TLS.
