### ISSUE TITLE
Potential Deadlock

### ISSUE THREAD

**Issue by anirudhsanthiar** [Azure/amqpnetlite#91]
The ```Connect``` method in TcpTransport.cs could deadlock. The method is:
```
 public void Connect(Connection connection, Address address, bool noVerification)
 {
    this.connection = connection;
    var factory = new ConnectionFactory();
    if (noVerification)
    {
    	factory.SSL.RemoteCertificateValidationCallback = noneCertValidator;
    }

    this.ConnectAsync(address, factory).GetAwaiter().GetResult();
}
```
A GUI client (such as a Windows Forms app) or an MVC client will deadlock if it calls the method as follows:

```
const string Endpoint = "amqp://guest:guest@localhost:5765";           
Address address = new Address(Endpoint);
var connection = new Connection(address);
```
(The constructor for the ```Connection object``` eventually calls the Connect method above.)

Note that the connect method blocks on a Task object because of the call to ```GetResult```: 
```this.ConnectAsync(address, factory).GetAwaiter().GetResult();```
Blocking on Task objects (Via Task.Wait() or Task.Result or Task.GetAwaiter().GetResult()) 
is dangerous and could result in deadlocks.
(See, for example http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html)

**Comment by xinchen10** [comment]
@anirudhsanthiar you are right. There are also other methods (e.g. SenderLink.Send, ReceiverLink.Recieve) that are blocking on an underlying task. If they are called from a UI thread, the same issue will happen. In such cases, the async methods should be called. For example, 
```
    Connection connection = await Connection.Factory.CreateAsync(address);
    ....
    await connection.CloseAsync();
```
I think we could either improve the documentation to make it obvious or remove the blocking APIs on certain platforms.

**Comment by anirudhsanthiar** [comment]
Yes, that would be great. Another option is to configure the await statements in ampqnetlite to not capture context via ConfigureAwait(false) [see, for example, the section under "avoiding context" in [1](http://blog.stephencleary.com/2012/02/async-and-await.html)]

**Comment by xinchen10** [comment]
The documentation for connection constructors has been updated. The code is also updated to not capture context.
