### ISSUE TITLE
Feature request: TLS Server Name Indication support

### ISSUE THREAD

**Issue by ChugR** [Azure/amqpnetlite#92]
The [Wikipedia article on SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) describes the feature. Essentially the code needs optionally to coerce the TLS Client Hello handshake frame to include the hostname extension field.

This is a requirement for some cloud services connection routing.

**Comment by xinchen10** [comment]
Now Address.Host should be sent as the SNI from the client. Is that not working as expected? Or should we allow a different target host to be set for TLS handshake, just like how open.host-name can be set through ConnectionFactory.AMQP.HostName?

**Comment by ChugR** [comment]
No, it was not working for me but you are correct in that it actually works. The hint came from a fellow testing the same thing with Java. He discovered if he was using a straight numeric IP address then the TLS did not send SMI but if he used a FQDN then the SMI was sent. The Lite client does the same thing.

Lite Url | Sends SMI
--------- | --------------
amqps://10.10.10.10:5671  |    no
amqps://photoserver:5671  |    yes
amqps://photoserver.com:5672 | yes
