### ISSUE TITLE
A null address throws a null reference exception in the listener

### ISSUE THREAD

**Issue by robreeves** [Azure/amqpnetlite#94]
If the client does not send an address, the listener throws a null reference exception trying to find the correct processor. An AMQPException with an error code of internal error is returned to the client. This makes it hard to troubleshoot.

I know this is a minor issue, but I ran into it using a python Qpid Proton client. I had to use the AMQP.Net Lite source to figure out my mistake since the return error code was not helpful. This fix is to reduce friction between popular AMQP implementations and make it easier to use them together. 

For reference here is the client code I ran into the issue with.

    from proton import *

    address = "amqp://host:port"

    mng = Messenger()
    mng.start()

    msg = Message();
    msg.address = address

    mng.put(msg)
    mng.send()

Here is what I needed to have. 

    from proton import *

    address = "amqp://host:port/queuename"

    mng = Messenger()
    mng.start()

    msg = Message();
    msg.address = address

    mng.put(msg)
    mng.send()

**Comment by xinchen10** [comment]
PR merged.
