### ISSUE TITLE
Any plans for continuous integration?

### ISSUE THREAD

**Issue by robreeves** [Azure/amqpnetlite#97]
I think it would be nice to have the test build setup to use continuous integration with the different supported platforms (.NET, mono, .NETMF, etc). This would help to maintain the projects high quality going forward. I doubt most people making changes have the infrastructure to run the tests on every supported platform.

**Comment by xinchen10** [comment]
Yes that would be very useful. Before that I need to figure out how to automate the tests for some platforms.

**Comment by xinchen10** [comment]
Enabled build on appveyor.

**Comment by robreeves** [comment]
Great to see this!
