### ISSUE TITLE
A session with the default handle-max throws an exception with more than one link

### ISSUE THREAD

**Issue by robreeves** [Azure/amqpnetlite#98]
The default value for the begin performative handle-max is 4294967295, or uint.Max (section 2.7.2 of the AMQP 1.0 spec). In Amqp.Session.AddLink it expands the localLinks array when a link is attached and the array is full. If the default handle-max of uint.Max is used, then expanding the localLinks array throws an argument exception because the array is out of bounds. The first expansion occurs when a second link is created with the session.

Session.handleMax is a uint. In Session.AddLink it is cast to an int, which returns -1. When calculating the new size this returns 0.

    int size = Math.Min(count * 2, (int)this.handleMax + 1);

This causes the exception because the expanded array is size 0. Any AMQP implementation that uses the spec's default handle max value will have problems. Apache Qpid Proton uses the default handle max value in the begin performative. I experienced this issue with an AMQP.Net Lite listener and a python Qpid Proton client. The client had a receiver link and a sender link that shared a session.

    from proton import *
    from proton.reactor import *
    from proton.handlers import *
    import time

    class HelloWorld(MessagingHandler):
        def __init__(self, server, address):
            super(HelloWorld, self).__init__()
            self.server = server
            self.loop = 0

        def on_start(self, event):
            print("on_start")
            conn = event.container.connect(self.server)
            event.container.create_sender(context=conn, target="toserver", name="python-client")
            event.container.create_sender(context=conn, source="toclient", name="python-client2")

        def on_sendable(self, event):
            print("on_sendable")
            self.loop += 1
            event.sender.send(Message(str(self.loop))
            time.sleep(1)

        def on_message(self, event):
            print("on_message")
            print(event.message.body)

    cont = Container(HelloWorld("host:port", ""))
    cont.sasl_enabled = False
    cont.run()

**Comment by xinchen10** [comment]
Fixed in v1.1.7
